<?php

class BotDeSeptLieues
{
  private $lieux = array(
 array("bois",0),
 array("bibliothèque",1),
array("canyon",0),
array("champ",0),
array("château",0),
array("chemin",0),
array("cimetière",0),
array("cité oubliée",1),
array("colline",1),
array("continent",0),
array("dédale",0),
array("donjon",0),
array("étang",0),
array("ferme",1),
array("forêt",1),
array("glacier",0),
array("grotte",1),
array("gué",0),
array("hameau",0),
array("île",1),
array("jardin",0),
array("jungle",1),
array("lac",0),
array("lande",1),
array("labyrinthe",0),
array("lieu",0),
array("marais",0),
array("montagne",1),
array("monument",0),
array("musée",0),
array("océan",0),
array("palais",0),
array("parc",0),
array("passerelle",1),
array("pays",0),
array("plage",1),
array("plaine",1),
array("prairie",1),
array("pont",0),
array("ravin",0),
array("région",1),
array("souterrain",0),
array("temple",0),
array("village",0),
array("ville engloutie",1)
 );

 private $noms = array(
  array("abeille", 1, null),
  array("abricot", 0, null),
  array("acrobate", 0, null),
  array("adulte", 0, null),
  array("aéroport", 0, null),
  array("affiche", 1, null),
  array("agneau", 0, null),
  array("aigle", 0, null),
  array("aiguille", 1, null),
  array("aile", 1, null),
  array("album", 0, null),
  array("aliment", 0, null),
  array("allumette", 1, null),
  array("ambulance", 1, null),
  array("ami", 0, null),
  array("ampoule", 1, null),
  array("ananas", 0, null),
  array("âne", 0, null),
  array("angle", 0, null),
  array("animal", 0, "animaux"),
  array("anorak", 0, null),
  array("appareil", 0, null),
  array("appartement", 0, null),
  array("aquarium", 0, null),
  array("araignée", 1, null),
  array("arbre", 0, null),
  array("arc", 0, null),
  array("arc-en-ciel", 0, "arcs-en-ciel"),
  array("armoire", 1, null),
  array("arrosoir", 0, null),
  array("ascenseur", 0, null),
  array("assiette", 1, null),
  array("aspirateur", 0, null),
  array("assiette", 1, null),
  array("avion", 0, null),
  array("bague", 1, null),
  array("balai", 0, null),
  array("balançoire", 1, null),
  array("balcon", 0, null),
  array("baleine", 1, null),
  array("ballon", 0, null),
  array("banane", 1, null),
  array("banc", 0, null),
  array("bande dessinée", 1, "bandes dessinées"),
  array("barque", 1, null),
  array("bassine", 1, null),
  array("bateau", 0, null),
  array("bâton", 0, null),
  array("bavoir", 0, null),
  array("bébé", 0, null),
  array("bête", 1, null),
  array("biberon", 0, null),
  array("bibliothèque", 1, null),
  array("bicyclette", 1, null),
  array("bifteck", 0, null),
  array("bijou", 0, "bijoux"),
  array("bille", 1, null),
  array("billet", 0, null),
  array("biscuit", 0, null),
  array("boeuf", 0, null),
  array("boîte", 1, null),
  array("bol", 0, null),
  array("bonbon", 0, null),
  array("bonhomme", 0, null),
  array("bonnet", 0, null),
  array("bonsaï", 0, null),
  array("bosse", 1, null),
  array("botte de foin", 1, "bottes de foin"),
  array("bouche", 1, null),
  array("boucherie", 1, null),
  array("bouchon", 0, null),
  array("bouée", 1, null),
  array("boulanger", 0, null),
  array("boulangerie", 1, null),
  array("boule", 1, null),
  array("bouquet", 0, null),
  array("bourgeon", 0, null),
  array("bouteille", 1, null),
  array("boutique", 1, null),
  array("bouton", 0, null),
  array("bracelet", 0, null),
  array("branche", 1, null),
  array("bras", 0, null),
  array("bretelle", 1, null),
  array("bricolage", 0, null),
  array("brosse", 1, null),
  array("brouette", 1, null),
  array("brouillard", 0, null),
  array("bûche", 1, null),
  array("buisson", 0, null),
  array("bulle", 1, null),
  array("bureau", 0, null),
  array("bus", 0, null),
  array("cabane", 1, null),
  array("cabinet", 0, null),
  array("cadavre", 0, null),
  array("cadeau", 0, null),
  array("cadenas", 0, null),
  array("cadre", 0, null),
  array("café", 0, null),
  array("cage", 1, null),
  array("cage à écureuil", 1, "cages à écureuils"),
  array("cagoule", 1, null),
  array("cahier", 0, null),
  array("caillou", 0, "cailloux"),
  array("caisse", 1, null),
  array("calendrier", 0, null),
  array("caméscope", 0, null),
  array("camion", 0, null),
  array("canapé", 0, null),
  array("canard", 0, null),
  array("caniveau", 0, null),
  array("canne à pêche", 1, "cannes à pêche"),
  array("car", 0, null),
  array("caravane", 1, null),
  array("carnet", 0, null),
  array("carotte", 1, null),
  array("carrefour", 0, null),
  array("cartable", 0, null),
  array("carton", 0, null),
  array("casier", 0, null),
  array("casque", 0, null),
  array("casquette", 1, null),
  array("casserole", 1, null),
  array("catalogue", 0, null),
  array("cauchemar", 0, null),
  array("cd-rom", 0, null),
  array("ceinture", 1, null),
  array("cerceau", 0, null),
  array("céréale", 1, null),
  array("cerf", 0, null),
  array("cerf-volant", 0, "cerfs-volants"),
  array("cerise", 1, null),
  array("chaîne", 1, null),
  array("chaise", 1, null),
  array("chambre", 1, null),
  array("champignon", 0, null),
  array("chance", 1, null),
  array("chanson", 1, null),
  array("chapeau", 0, null),
  array("chariot", 0, null),
  array("chasseur", 0, null),
  array("chat", 0, null),
  array("châtaigne", 1, null),
  array("chaussette", 1, null),
  array("chausson", 0, null),
  array("chaussure", 1, null),
  array("cheminée", 1, null),
  array("chemise", 1, null),
  array("chêne", 0, null),
  array("chenille", 1, null),
  array("cheval", 0, "chevaux"),
  array("cheveu", 0, "cheveux"),
  array("cheville", 1, null),
  array("chèvre", 1, null),
  array("chien", 0, null),
  array("chiffon", 0, null),
  array("chiffre", 0, null),
  array("barre chocolatée", 1, "barres chocolatées"),
  array("chose", 1, null),
  array("chou", 0, "choux"),
  array("chouette", 1, null),
  array("cigarette", 1, null),
  array("cigogne", 1, null),
  array("cil", 0, null),
  array("paire de ciseaux", 1, "paires de ciseaux"),
  array("citron", 0, null),
  array("citrouille", 1, null),
  array("clé", 1, null),
  array("clémentine", 1, null),
  array("cloche", 1, null),
  array("clocher", 0, null),
  array("clou", 0, null),
  array("clown", 0, null),
  array("coccinelle", 1, null),
  array("cochon", 0, null),
  array("cochon d’inde", 0, "cochons d’inde"),
  array("coeur", 0, null),
  array("coffre", 0, null),
  array("coffret", 0, null),
  array("coiffeur", 0, null),
  array("collant", 0, null),
  array("pot de colle", 0, "pots de colle"),
  array("collier", 0, null),
  array("colline", 1, null),
  array("coloriage", 0, null),
  array("concombre", 0, null),
  array("confiture", 1, null),
  array("copain", 0, null),
  array("coq", 0, null),
  array("coquelicot", 0, null),
  array("coquetier", 0, null),
  array("coquillage", 0, null),
  array("coquille", 1, null),
  array("coquin", 0, null),
  array("corbeau", 0, null),
  array("corbeille", 1, null),
  array("corde", 1, null),
  array("corps", 0, null),
  array("côté", 0, null),
  array("cou", 0, null),
  array("coude", 0, null),
  array("couette", 1, null),
  array("couleur", 1, null),
  array("couronne", 1, null),
  array("coussin", 0, null),
  array("couteau", 0, null),
  array("couvercle", 0, null),
  array("couverture", 1, null),
  array("crabe", 0, null),
  array("craie", 1, null),
  array("crapaud", 0, null),
  array("cravate", 1, null),
  array("crayon", 0, null),
  array("crèche", 1, null),
  array("crêpe", 1, null),
  array("crevette", 1, null),
  array("cri", 0, null),
  array("crochet", 0, null),
  array("crocodile", 0, null),
  array("croix", 1, null),
  array("croûte", 1, null),
  array("cube", 0, null),
  array("cuillère", 1, null),
  array("cuisinière", 1, null),
  array("cuisse", 1, null),
  array("culotte", 1, null),
  array("cuvette", 1, null),
  array("cygne", 0, null),
  array("dame", 1, null),
  array("dauphin", 0, null),
  array("dé", 0, null),
  array("déguisement", 0, null),
  array("dent", 1, null),
  array("tube de dentifrice", 0, "tubes de dentifrice"),
  array("dentiste", 0, null),
  array("départ", 0, null),
  array("désordre", 0, null),
  array("dessert", 0, null),
  array("dessin", 0, null),
  array("dictionnaire", 0, null),
  // array("différence", 1, null),
  array("dimanche", 0, null),
  array("dindon", 0, null),
  array("dinosaure", 0, null),
  array("directeur", 0, null),
  array("docteur", 0, null),
  array("doigt", 0, null),
  array("domino", 0, null),
  array("drap", 0, null),
  array("drapeau", 0, null),
  array("écharpe", 1, null),
  array("échasse", 1, null),
  array("échelle", 1, null),
  array("éclair", 0, null),
  array("école", 1, null),
  array("écorce", 1, null),
  array("écran", 0, null),
  array("écureuil", 0, null),
  array("église", 1, null),
  array("élastique", 0, null),
  array("éléphant", 0, null),
  array("élève", 0, null),
  array("embouteillage", 0, null),
  array("endive", 1, null),
  array("enfant", 0, null),
  array("engin", 0, null),
  array("entonnoir", 0, null),
  array("enveloppe", 1, null),
  array("épaule", 1, null),
  array("épée", 1, null),
  array("épingle", 1, null),
  array("épluchure", 1, null),
  array("éponge", 1, null),
  array("escabeau", 0, null),
  array("escalier", 0, null),
  array("escargot", 0, null),
  array("étagère", 1, null),
  array("étiquette", 1, null),
  array("étoile", 1, null),
  array("évier", 0, null),
  array("facteur", 0, null),
  array("sac de farine", 0, "sacs de farine"),
  array("fauteuil", 0, null),
  array("fée", 1, null),
  array("femme", 1, null),
  array("fenêtre", 1, null),
  array("fer à repasser", 0, "fers à repasser"),
  array("fermier", 0, null),
  array("fesse", 1, null),
  array("feuille", 1, null),
  array("feutre", 0, null),
  array("fève", 1, null),
  array("ficelle", 1, null),
  array("figure", 1, null),
  array("filet", 0, null),
  array("fille", 1, null),
  array("flamme", 1, null),
  array("flaque", 1, null),
  array("flèche", 1, null),
  array("fleur", 1, null),
  array("fleuriste", 0, null),
  array("flocon", 0, null),
  array("foire", 1, null),
  array("fontaine", 1, null),
  array("forme", 1, null),
  array("four", 0, null),
  array("fourchette", 1, null),
  array("fourmi", 1, null),
  array("fraise", 1, null),
  array("framboise", 1, null),
  array("frite", 1, null),
  array("fromage", 0, null),
  array("fruit", 0, null),
  array("fumée", 1, null),
  array("fusée", 1, null),
  array("fusil", 0, null),
  array("galette", 1, null),
  array("gant", 0, null),
  array("garage", 0, null),
  array("garçon", 0, null),
  array("gardien", 0, null),
  array("gare", 1, null),
  array("gâteau", 0, null),
  array("géant", 0, null),
  array("genou", 0, "genoux"),
  array("girafe", 1, null),
  array("glace", 1, null),
  array("glaçon", 0, null),
  array("gobelet", 0, null),
  array("gomme", 1, null),
  array("gorge", 1, null),
  array("gourde", 1, null),
  array("goût", 0, null),
  array("goutte", 1, null),
  array("grain", 0, null),
  array("graine", 1, null),
  array("grand-mère", 1, "grands-mères"),
  array("grand-père", 0, "grands-pères"),
  array("grenouille", 1, null),
  array("griffe", 1, null),
  array("grue", 1, null),
  array("guêpe", 1, null),
  array("guirlande", 1, null),
  array("gymnaste", 1, null),
  array("hamster", 0, null),
  array("hanche", 1, null),
  array("haricot", 0, null),
  array("hélicoptère", 0, null),
  array("hérisson", 0, null),
  array("hibou", 0, "huboux"),
  array("hippopotame", 0, null),
  array("hirondelle", 1, null),
  array("homme", 0, null),
  array("hôpital", 0, "hôpitaux"),
  array("horloge", 1, null),
  array("hôtel", 0, null),
  array("humeur", 1, null),
  array("idée", 1, null),
  array("image", 1, null),
  array("immeuble", 0, null),
  array("incendie", 0, null),
  array("infirmier", 0, null),
  array("insecte", 0, null),
  array("instituteur", 0, null),
  array("instrument", 0, null),
  array("intrus", 0, null),
  array("jambe", 1, null),
  array("jambon", 0, null),
  array("jonquille", 1, null),
  array("jouet", 0, null),
  array("journal", 0, "journaux"),
  array("jupe", 1, null),
  array("kangourou", 0, null),
  array("kiwi", 0, null),
  array("lacet", 0, null),
  array("lampadaire", 0, null),
  array("lampe", 1, null),
  array("langue", 1, null),
  array("lapin", 0, null),
  array("larme", 1, null),
  array("lavabo", 0, null),
  array("lave-linge", 0, null),
  array("légume", 0, null),
  array("lettre", 1, null),
  array("lèvre", 1, null),
  array("lézard", 0, null),
  array("ligne", 1, null),
  array("lion", 0, null),
  array("liquide", 0, null),
  array("liste", 1, null),
  array("lit", 0, null),
  array("livre", 0, null),
  array("loup", 0, null),
  array("loupe", 1, null),
  array("luge", 1, null),
  array("lumière", 1, null),
  array("lune", 1, null),
  array("lutin", 0, null),
  array("machine", 1, null),
  array("magasin", 0, null),
  array("magazine", 0, null),
  array("magicien", 0, null),
  array("magnétoscope", 0, null),
  array("maillot", 0, null),
  array("main", 1, null),
  array("maison", 1, null),
  array("manège", 0, null),
  array("manteau", 0, null),
  array("maquillage", 0, null),
  array("marchand", 0, null),
  array("strapontin", 0, null),
  array("mare", 1, null),
  array("marguerite", 1, null),
  array("amoureux", 0, null),
  array("marin", 0, null),
  array("marionnette", 1, null),
  array("marteau", 0, null),
  array("masque", 0, null),
  array("matelas", 0, null),
  array("médecin", 0, null),
  array("médicament", 0, null),
  array("melon", 0, null),
  array("mensonge", 0, null),
  array("menton", 0, null),
  array("mère", 1, null),
  array("meuble", 0, null),
  array("micro", 0, null),
  array("mine", 1, null),
  array("minute", 1, null),
  array("moineau", 0, null),
  array("monde", 0, null),
  array("montre", 1, null),
  array("morceau", 0, null),
  array("morceau de pain", 0, "morceaux de pain"),
  array("mot", 0, null),
  array("moteur", 0, null),
  array("moto", 1, null),
  array("mouche", 1, null),
  array("mouchoir", 0, null),
  array("mouette", 1, null),
  array("moule", 1, null),
  array("moulin", 0, null),
  array("moustache", 1, null),
  array("moustique", 0, null),
  array("mouton", 0, null),
  array("mur", 0, null),
  array("mûre", 1, null),
  array("muscle", 0, null),
  array("musique", 1, null),
  array("navet", 0, null),
  array("navire", 0, null),
  array("flocon de neige", 1, "flocons de neige"),
  array("nez", 0, null),
  array("nid", 0, null),
  array("noeud", 0, null),
  array("noisette", 1, null),
  array("noix", 1, null),
  array("nom", 0, null),
  array("nombre", 0, null),
  array("noyau", 0, null),
  array("nuage", 0, null),
  array("nuit", 1, null),
  array("objet", 0, null),
  array("odeur", 1, null),
  array("oeil", 0, "yeux"),
  array("oeuf", 0, null),
  array("ogre", 0, null),
  array("oie", 1, null),
  array("oignon", 0, null),
  array("oiseau", 0, null),
  array("ombre", 1, null),
  array("ongle", 0, null),
  array("orage", 0, null),
  array("orange", 1, null),
  array("orchestre", 0, null),
  array("ordinateur", 0, null),
  array("ordonnance", 1, null),
  array("oreille", 1, null),
  array("oreiller", 0, null),
  array("os", 0, null),
  array("ouragan", 0, null),
  array("ourson", 0, null),
  array("outil", 0, null),
  array("ouvrier", 0, null),
  array("page", 0, null),
  array("paille", 1, null),
  array("pamplemousse", 0, null),
  array("panda", 0, null),
  array("panier", 0, null),
  array("panneau", 0, null),
  array("pansement", 0, null),
  array("pantalon", 0, null),
  array("panthère", 1, null),
  array("pantoufle", 1, null),
  array("papier", 0, null),
  array("papillon", 0, null),
  array("pâquerette", 1, null),
  array("paquet", 0, null),
  array("parapluie", 0, null),
  array("parasol", 0, null),
  array("parfum", 0, null),
  array("parking", 0, null),
  array("pâtisserie", 1, null),
  array("patte", 1, null),
  array("paysan", 0, null),
  array("paysage", 0, null),
  array("pêcheur", 0, null),
  array("peigne", 0, null),
  array("peinture", 1, null),
  array("pelle", 1, null),
  array("peluche", 1, null),
  array("pendule", 1, null),
  array("pente", 1, null),
  array("père", 0, null),
  array("perle", 1, null),
  array("perroquet", 0, null),
  array("personne", 1, null),
  array("petit pois", 0, "petits pois"),
  array("petite fille", 1, "petites filles"),
  array("petit garçon", 0, "petits garçons"),
  array("peur", 1, null),
  array("pharmacie", 1, null),
  array("pharmacien", 0, null),
  array("phoque", 0, null),
  array("photo", 1, null),
  array("pied", 0, null),
  array("pierre", 1, null),
  array("pigeon", 0, null),
  array("pile", 1, null),
  array("pilote", 0, null),
  array("pin", 0, null),
  array("pinceau", 0, null),
  array("piscine", 1, null),
  array("placard", 0, null),
  array("planche", 1, null),
  array("plante", 1, null),
  array("plat", 0, null),
  array("plateau", 0, null),
  array("plâtre", 0, null),
  array("pliage", 0, null),
  array("plongeoir", 0, null),
  array("pluie", 1, null),
  array("plume", 1, null),
  array("pneu", 0, null),
  array("poche", 1, null),
  array("poêle", 1, null),
  array("poignet", 0, null),
  array("poing", 0, null),
  array("poire", 1, null),
  array("poireau", 0, null),
  array("poisson", 0, null),
  array("policier", 0, null),
  array("pomme", 1, null),
  array("pomme de terre", 1, "pommes de terre"),
  array("pompe", 1, null),
  array("pompier", 0, null),
  array("poney", 0, null),
  array("pont", 0, null),
  array("porte", 1, null),
  array("portemanteau", 0, null),
  array("portière", 1, null),
  array("pot", 0, null),
  array("potage", 0, null),
  array("poubelle", 1, null),
  array("pouce", 0, null),
  array("pouf", 0, null),
  array("poule", 1, null),
  array("poulet", 0, null),
  array("poupée", 1, null),
  array("poussette", 1, null),
  array("poussière", 1, null),
  array("poussin", 0, null),
  array("prince", 0, null),
  array("princesse", 1, null),
  array("prise", 1, null),
  array("prune", 1, null),
  array("pull-over", 0, null),
  array("purée", 1, null),
  array("puzzle", 0, null),
  array("pyjama", 0, null),
  array("radiateur", 0, null),
  array("radio", 1, null),
  array("radis", 0, null),
  array("grain de raisin", 0, "grains de raisin"),
  array("raquette", 1, null),
  array("rasoir", 0, null),
  array("rat", 0, null),
  array("râteau", 0, null),
  array("réfrigérateur", 0, null),
  array("regard", 0, null),
  array("reine", 1, null),
  array("renard", 0, null),
  array("requin", 0, null),
  array("restaurant", 0, null),
  array("réveil", 0, null),
  array("rhinocéros", 0, null),
  array("rideau", 0, null),
  array("rivière", 1, null),
  array("grain de riz", 0, "grains de riz"),
  array("robe", 1, null),
  array("robinet", 0, null),
  array("rocher", 0, null),
  array("roi", 0, null),
  array("roue", 1, null),
  array("route", 1, null),
  array("ruban", 0, null),
  array("rue", 1, null),
  array("grain de sable", 0, "grains de sable"),
  array("sac en plastique", 0, "sacs en plastique"),
  array("saison", 1, null),
  array("salade", 1, null),
  array("saladier", 0, null),
  array("sapin", 0, null),
  array("sardine", 1, null),
  array("barre de savon", 1, "barres de savon"),
  array("scie", 1, null),
  array("seau", 0, null),
  array("salière en faïence", 0, "salières en faïence"),
  array("semelle orthopédique", 1, "semelles orthopédique"),
  array("serpent", 0, null),
  array("serrure", 1, null),
  array("serviette", 1, null),
  array("siège", 0, null),
  array("sifflet", 0, null),
  array("signe", 0, null),
  array("silence", 0, null),
  array("singe", 0, null),
  array("soeur", 1, null),
  array("soldat", 0, null),
  array("sole", 1, null),
  array("soleil", 0, null),
  array("sonnette", 1, null),
  array("sorcier", 0, null),
  array("sorcière", 1, null),
  array("soupe", 1, null),
  array("sourcil", 0, null),
  array("sourire", 0, null),
  array("souris", 1, null),
  array("squelette", 0, null),
  array("stylo", 0, null),
  array("cube de sucre", 0, "cubes de sucre"),
  array("table", 1, null),
  array("tableau", 0, null),
  array("tablier", 0, null),
  array("tabouret", 0, null),
  array("taille-crayon", 0, null),
  array("talon", 0, null),
  array("tambour", 0, null),
  array("tampon", 0, null),
  array("tapis", 0, null),
  array("tas", 0, null),
  array("tasse", 1, null),
  array("taupe", 1, null),
  array("télécommande", 1, null),
  array("téléphone", 0, null),
  array("télévision", 1, null),
  array("tempête", 1, null),
  array("tente", 1, null),
  array("terrier", 0, null),
  array("tête", 1, null),
  array("tasse de thé", 1, "tasses de thé"),
  array("thermomètre", 0, null),
  array("tigre", 0, null),
  array("timbre", 0, null),
  array("tiroir", 0, null),
  array("toboggan", 0, null),
  array("tomate", 1, null),
  array("torchon", 0, null),
  array("tortue", 1, null),
  array("tour", 1, null),
  array("tournevis", 0, null),
  array("tracteur", 0, null),
  array("train", 0, null),
  array("traîneau", 0, null),
  array("trampoline", 0, null),
  array("tranche", 1, null),
  array("tricot", 0, null),
  array("tricycle", 0, null),
  array("trompette", 1, null),
  array("trottoir", 0, null),
  array("trou", 0, null),
  array("tube", 0, null),
  array("tulipe", 1, null),
  array("tunnel", 0, null),
  array("tuyau", 0, null),
  array("uniforme", 0, null),
  array("univers", 0, null),
  array("usine", 1, null),
  array("vache", 1, null),
  array("vague", 1, null),
  array("valise", 1, null),
  array("vase", 0, null),
  array("véhicule", 0, null),
  array("vélo", 0, null),
  array("vent", 0, null),
  array("ventre", 0, null),
  array("ver", 0, null),
  array("verre", 0, null),
  array("veste", 1, null),
  array("vétérinaire", 0, null),
  array("bouteille de vin", 1, "bouteilles de vin"),
  array("visage", 0, null),
  array("voile", 0, null),
  array("voisin", 0, null),
  array("voiture", 1, null),
  array("wagon", 0, null),
  array("xylophone", 0, null),
  array("pot de yaourt", 0, "pots de yaourt"),
  array("zèbre", 0, null),

  array("banquier", 0, null),
  array("orbe", 0, null),
  array("communiste", 0, null),
  array("loutre", 1, null),
  array("artichaut", 0, null),
  array("poète", 0, null),
  array("prêtre", 0, null),
  array("esclave", 0, null),
  array("philosophe", 0, null),
  array("ermite", 0, null),
  array("sage", 0, null),
  array("monstre", 0, null),
  array("dragon", 0, null),
  array("salopette", 1, null),
  array("ivrogne", 0, null),
  array("troll", 0, null),
  array("voyageur", 0, null),
  array("machine", 0, null),
  array("moine", 0, null),
  array("saule", 0, null),
  array("garde-barrière", 0, "gardes-barrières"),
  array("rabbin", 0, null),
  array("rongeur", 0, null),
 );

   private $adverbes = array(
    "anormalement",
    "avec un air",
    "beaucoup trop",
    "délicieusement",
    "étrangement",
    "pas assez",
    "perpétuellement",
    "que j'ai trouvé€ trop",
    "qui m'a semblé€ particulièrement",
    "qui parfois devenait",
    "qui m'a trouvé",
    "tendrement",
    "terriblement"
   );


   private $adjectifs = array(
"abîmé€",
"affamé€",
"aimable",
"amusant€",
"aristocratique",
"bizarre",
"bleu€",
"blond€",
"brillant€",
"brûlant€",
"bruyant€",
"calme",
"carnivore",
"herbivore",
"pacifiste",
"cassé€",
"chaud€",
"clair€",
"colérique",
"confortable",
"décevant€",
"difficile",
"dur€",
"effrayé€",
"électrique",
"énervé€",
"enflé€",
"énorme",
"étroit€",
"foncé€",
"fragile",
"froid€",
"gai€",
"gelé€",
"gigantesque",
"gonflable",
"gourmand€",
"gris€",
"handicapé€",
"hilare",
"humide",
"immense",
"immobile",
"impossible",
"inégal€",
"instable",
"intéressant€",
"jaune",
"lent€",
"lisse",
"lourd€",
"maigre",
"malade",
"maladroit€",
"méchant€",
"méfiant€",
"meilleur€",
"moite",
"mort€",
"mouillé€",
"multicolore",
"mûr€",
"nain€",
"noble",
"noir€",
"nu€",
"obèse",
"pâle",
"patient€",
"pointu€",
"poli€",
"profond€",
"propre",
"rapide",
"riche",
"rond€",
"rouge",
"satisfait€",
"solide",
"solitaire",
"sombre",
"souple",
"sourd€",
"terrifiant€",
"tordu€",
"tranquille",
"transparent€",
"triste",
"usé€",
"vert€",
"vide",
"violent€",
"vivant€",
"volant€",
"vulgaire",
 );
 
 private $structures = array
 (
  array
  (
   array(
    "J'ai dormi près de %un_sujet%",
    "J'ai longé %un_sujet%",
    "J'ai visité %un_sujet%",
    "J'ai pique-niqué près de %un_sujet%",
    "J'ai découvert %un_sujet%",
    "J'ai exploré %un_sujet%",
    "J'ai passé la nuit à côté de %un_sujet%",
    "J'ai contourné %un_sujet%",
    "J'ai admiré %un_sujet%",
    "J'ai cartographié %un_sujet%",
    "Je me suis reposé près de %un_sujet%",
    "Je me suis recueilli devant %un_sujet%",
	"J'ai nagé jusqu'à atteindre %un_sujet%",
	"J'ai découvert le plan de %un_sujet%",
	"J'ai lu un livre qui parlait de %un_sujet%",
    ),
   array(
    "plein€ de %noms2% %comp3%",
     "où vivent %des_noms2% %comp1%",
     "peuplé€ de %noms2% %comp3%",
     "envahi€ de %noms2% %comp3%",
     "habité€ par un peuple de %noms2% %comp1%",
     "où poussent %des_noms2% %comp1%",
     "où traînaient quelques %noms2% %comp3%",
     "orné€ de rangées de %noms2%",
     "où quelqu'un a planté %des_noms2% %comp1%",
     "qui avait la forme de %un_nom2%",
     "où se promenait %un_nom2% %comp2%",
     "où erraient %des_noms2% %comp3%",
     "où se cachaient deux ou trois %noms2% %comp3%",
     "d'où sortait parfois %un_nom2% %comp2%",
     "entièrement constitué€ de %noms2% %comp3%",
     "où s'affrontaient deux tribus de %noms2% %comp3%",
     "où j'ai croisé une famille de %noms2% %comp3%",
     ),
   "lieu" // Type de sujet
  ),

  array
  (
   array(
    "J'ai chevauché %un_sujet%",
    "J'ai poursuvi %un_sujet%",
    "J'ai ramassé %un_sujet%",
    "J'ai pourchassé %un_sujet%",
    "J'ai domestiqué %un_sujet%",
    "J'ai nourri %un_sujet%",
    "J'ai mangé %un_sujet%",
    "J'ai été mordu par %un_sujet%",
    "J'ai escaladé %un_sujet%",
    "J'ai vu %un_sujet%",
    "J'ai observé %un_sujet%",
    "J'ai photographié %un_sujet%",
    "J'ai suivi %un_sujet%",
    "J'ai recontré %un_sujet%",
    "J'ai discuté avec %un_sujet%",
    "J'ai pris des notes sur %un_sujet%",
    // "J'ai dessiné %un_sujet%",
    "J'ai planté %un_sujet%",
    "je suis tombé amoureux de %un_sujet%",
    "je suis devenu ami avec %un_sujet%",
    "je me suis battu avec %un_sujet%",
    "J'ai découvert %un_sujet%",
    "J'ai été fait prisonnier par %un_sujet%",
    "J'ai parlé philosophie avec %un_sujet%",
    "J'ai été surpris par %un_sujet%",
    "J'ai écouté le chant de %un_sujet%",
    "J'ai sauvé de la noyade %un_sujet%",
    "J'ai pêché %un_sujet%",
    "J'ai capturé %un_sujet%",
	"J'ai vu une statue à l'effigie de %un_sujet%",
	"J'ai bu un verre avec %un_sujet%",
	"J'ai fait un bout de chemin en compagnie de %un_sujet%",
	"J'ai fleuri la tombe de %un_sujet%",
	"J'ai visité un musée dont toutes les œuvres représentaient %un_sujet%",
	"J'ai entendu une rumeur au sujet de %un_sujet%",
	"J'ai rencontré un artiste qui rêvait de peindre %un_sujet%",
    ),
   array(
    "%comp2%",
    "%adj%"
     ),
   "nom" // Type de sujet
  )
 );
 
 private $complements = array
 (
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),
  array("", "", "", "", ""),

  array("qui ressembl* à +", "e", "ent", "ait", "aient", "%un_nom%", "%des_noms%"),
  array("en forme de +", "e", "ent", "ait", "aient", "%nom%", "%noms%"),
  array("à l'odeur de %nom%", "e", "ent", "ait", "aient"),
  array("qui m'* parlé de %noms%", "a", "ont", "a", "ont"),
  array("qui chant* un hymne à la gloire %des_noms%", "e", "ent", "ait", "aient"),
  array("qui ador* un dieu-%nom%", "e", "ent", "ait", "aient"),
  array("qui rêv* chaque nuit de %un_nom%", "e", "ent", "ait", "aient"),
  array("qui se nourri* de %noms%", "t", "ssent", "ssait", "ssaient"),
  array("qui chaque matin donn* naissance à %un_nom%", "e", "ent", "ait", "aient"),
  array("en guerre contre %les_noms%", "", "", "", ""),
  array("qui se transform* lentement en +", "e", "ent ", "ait", "aient", "%nom%", "%noms%"),
  array("qui psalmodi* une prière aux %noms%", "e", "ent", "ait", "aient"),
  array("qui aurai* aimé être +", "t", "ent", "t", "ent", "%un_nom%", "%des_noms%"),
  array("qui aim* %un_nom%", "e", "ent", "ait", "aient"),
  array("qui collectionn* %les_noms%", "e", "ent", "ait", "aient"),
  array("qui rêv* de posséder +", "e", "ent", "ait", "aient", "%un_nom%", "%des_noms%"),
  array("qui recherch* %un_nom% depuis des siècles", "e", "ent", "ait", "aient"),
  array("qui m'* demandé %un_nom% en offrande", "a", "ont", "a", "ont"),
  array("dont toute la métaphysique repos* sur %les_noms%", "e", "e", "ait", "ait"),
  array("qui écri* des poèmes sur %les_noms%", "t", "vent", "vait", "vaient"),
  array("qui parl* la langue %des_noms%", "e", "ent", "ait", "aient"),
  array("qui ne s'intéress* qu'aux %noms%", "e", "ent", "ait", "aient"),
  array("qui pass* le temps en inventant des histoires de %noms%", "e", "ent", "ait", "aient"),
  array("qui * une peur panique %des_noms%", "a", "ont", "avait", "avaient"),
  array("qui, la nuit, se déguis* en +", "e", "ent", "ait", "aient", "%nom%", "%noms%"),
  array("qui cultiv* un champ de %noms%", "e", "ent", "ait", "aient"),
  array("qui fabriqu* %des_noms%", "e", "ent", "ait", "aient"),
  array("que poursuivaient %des_noms%", "", "", "", ""),
  array("qui se consacr* à l'élevage %des_noms%", "e", "ent", "ait", "aient"),
  array("qui maîtris* la science %des_noms%", "e", "ent", "ait", "aient"),
 );


 private function randArray($arr)
 { return $arr[mt_rand(0, count($arr) - 1)]; }

 private function creerPluriel($nom)
 {
  if ($nom[2] !== null) return $nom[2];

  if ($this->endsWith($nom[0], "s")) return $nom[0];
  if ($this->endsWith($nom[0], "x")) return $nom[0];
  if ($this->endsWith($nom[0], "z")) return $nom[0];
  if ($this->endsWith($nom[0], "eau")) return $nom[0]."x";

  return $nom[0]."s";
 }

 private function endsWith($haystack, $needle)
 {
  $length = strlen($needle);
  if ($length == 0) return true;
  return (substr($haystack, -$length) === $needle);
 }

 private function faireElision($avant, $apres, $texte)
 {
  $texte = str_replace(" ".$avant."a", " ".$apres."a", $texte);
  $texte = str_replace(" ".$avant."à", " ".$apres."à", $texte);
  $texte = str_replace(" ".$avant."â", " ".$apres."â", $texte);
  $texte = str_replace(" ".$avant."ä", " ".$apres."ä", $texte);
  $texte = str_replace(" ".$avant."e", " ".$apres."e", $texte);
  $texte = str_replace(" ".$avant."é", " ".$apres."é", $texte);
  $texte = str_replace(" ".$avant."è", " ".$apres."è", $texte);
  $texte = str_replace(" ".$avant."ê", " ".$apres."ê", $texte);
  $texte = str_replace(" ".$avant."ë", " ".$apres."ë", $texte);
  $texte = str_replace(" ".$avant."i", " ".$apres."i", $texte);
  $texte = str_replace(" ".$avant."î", " ".$apres."î", $texte);
  $texte = str_replace(" ".$avant."ï", " ".$apres."ï", $texte);
  $texte = str_replace(" ".$avant."o", " ".$apres."o", $texte);
  $texte = str_replace(" ".$avant."ô", " ".$apres."ô", $texte);
  $texte = str_replace(" ".$avant."ö", " ".$apres."ö", $texte);
  $texte = str_replace(" ".$avant."œ", " ".$apres."œ", $texte);
  $texte = str_replace(" ".$avant."u", " ".$apres."u", $texte);
  $texte = str_replace(" ".$avant."ù", " ".$apres."ù", $texte);
  $texte = str_replace(" ".$avant."ü", " ".$apres."ü", $texte);
  $texte = str_replace(" ".$avant."û", " ".$apres."û", $texte);
  $texte = str_replace(" ".$avant."y", " ".$apres."y", $texte);

  return $texte;
 }

 private function creerGroupeNominal($nom, $article, $pluriel)
 {
  if ($pluriel) $gn = $this->creerPluriel($nom);
  else $gn = $nom[0];

  if (($article === 0) || (strlen($article) == 0)) return $gn;

 if ($nom[1] == 1) // féminin
 {
  switch ($article)
  {
   case "un": $article = "une"; break;
   case "le": $article = "la"; break;
  }
 }

  $gn = $article." ".$gn;
 
  return $gn;
 }

 private function creerComplement($index)
 {
  $compArr = $this->randArray($this->complements);
  $comp = str_replace('*', $compArr[$index + 1], $compArr[0]);

  if (mb_strpos($comp, '+') !== FALSE)
  {
   if (($index == 1) || ($index == 3)) // pluriel
    $comp = str_replace('+', $compArr[6], $comp);
   else
    $comp = str_replace('+', $compArr[5], $comp);
  }

  return $comp;
 }

 private function creerAdjectif()
 {
  $adj = $this->randArray($this->adjectifs);

  if (mt_rand(0, 1) == 0)
   $adj = $this->randArray($this->adverbes)." ".$adj;

  return $adj;
 }

 public function generer()
 {
  $jour = ceil(time() / (24 * 3600));
  // mt_srand($jour);
  //$jour -= 17366;
  $jour -= 17368;

  $texte = "Jour ".strval($jour)."\n\n";

  $struct = $this->randArray($this->structures);
  $texte .= $this->randArray($struct[0]);
  $texte .= " ".$this->randArray($struct[1]);

  switch ($struct[2])
  {
   case "lieu":
    $sujet = $this->randArray($this->lieux);
    break;
   default:
    $sujet = $this->randArray($this->noms);
    break;
  }

  $texte = str_replace("%adj%", $this->creerAdjectif(), $texte);

  if ($sujet[1] == 1) // sujet féminin
   $texte = str_replace("€", "e", $texte);
  else
   $texte = str_replace("€", "", $texte);

  $texte = str_replace("%comp0%", $this->creerComplement(0), $texte);
  $texte = str_replace("%comp1%", $this->creerComplement(1), $texte);
  $texte = str_replace("%comp2%", $this->creerComplement(2), $texte);
  $texte = str_replace("%comp3%", $this->creerComplement(3), $texte);

  $texte = str_replace("%un_sujet%", $this->creerGroupeNominal($sujet, "un", false), $texte);

  $texte = str_replace("%nom%", $this->creerGroupeNominal($this->randArray($this->noms), "", false), $texte);
  $texte = str_replace("%un_nom%", $this->creerGroupeNominal($this->randArray($this->noms), "un", false), $texte);
  $texte = str_replace("%le_nom%", $this->creerGroupeNominal($this->randArray($this->noms), "le", false), $texte);
  $texte = str_replace("%noms%", $this->creerGroupeNominal($this->randArray($this->noms), "", true), $texte);
  $texte = str_replace("%des_noms%", $this->creerGroupeNominal($this->randArray($this->noms), "des", true), $texte);
  $texte = str_replace("%les_noms%", $this->creerGroupeNominal($this->randArray($this->noms), "les", true), $texte);

  $texte = str_replace("%nom2%", $this->creerGroupeNominal($this->randArray($this->noms), "", false), $texte);
  $texte = str_replace("%un_nom2%", $this->creerGroupeNominal($this->randArray($this->noms), "un", false), $texte);
  $texte = str_replace("%le_nom2%", $this->creerGroupeNominal($this->randArray($this->noms), "le", false), $texte);
  $texte = str_replace("%noms2%", $this->creerGroupeNominal($this->randArray($this->noms), "", true), $texte);
  $texte = str_replace("%des_noms2%", $this->creerGroupeNominal($this->randArray($this->noms), "des", true), $texte);
  $texte = str_replace("%les_noms2%", $this->creerGroupeNominal($this->randArray($this->noms), "les", true), $texte);
 
  $texte = $this->faireElision("le ", "l'", $texte);
  $texte = $this->faireElision("la ", "l'", $texte);
  $texte = $this->faireElision("de ", "d'", $texte);

  $texte = trim($texte);
  $texte .= ".";

  return $texte;
 }
}


?>