<?php

class AutoEluard
{
private $adjectifs = array
(
array("abandonné","abandonnée","abandonnés","abandonnées"),
array("abîmé","abîmée","abîmés","abîmées"),
array("absent","absente","absents","absentes"),
array("adroit","adroite","adroits","adroites"),
array("aîné","aînée","aînés","aînées"),
array("amusant","amusante","amusants","amusantes"),
array("ancien","anciene","anciens","ancienes"),
array("assis","assise","assis","assises"),
array("barbouillé","barbouillée","barbouillés","barbouillées"),
array("bas","basse","bas","basses"),
array("beau","belle","beaux","belles"),
array("bizarre","bizarre","bizarres","bizarres"),
array("blanc","blance","blancs","blances"),
array("bleu","bleue","bleus","bleues"),
array("blond","blonde","blonds","blondes"),
array("bon","bonne","bons","bonnes"),
array("brun","brune","bruns","brunes"),
array("caché","cachée","cachés","cachées"),
array("calme","calme","calmes","calmes"),
array("cassé","cassée","cassés","cassées"),
array("changeant","changeante","changeants","changeantes"),
array("chaud","chaude","chauds","chaudes"),
array("cher","chère","chers","chères"),
array("clair","claire","clairs","claires"),
array("confortable","confortable","confortables","confortables"),
array("content","contente","contents","contentes"),
array("coquet","coquete","coquets","coquetes"),
array("couché","couchée","couchés","couchées"),
array("court","courte","courts","courtes"),
array("creux","creuse","creux","creuses"),
array("cru","crue","crus","crues"),
array("cruel","cruelle","cruels","cruelles"),
array("cuit","cuite","cuits","cuites"),
array("curieux","curieuse","curieux","curieuses"),
array("dangereux","dangereuse","dangereux","dangereuses"),
array("déçu","déçue","déçus","déçues"),
array("délicieux","délicieuse","délicieux","délicieuses"),
array("dernier","dernière","derniers","dernières"),
array("différent","différente","différents","différentes"),
array("difficile","difficile","difficiles","difficiles"),
array("douillet","douillette","douillets","douillettes"),
array("doux","douce","doux","douces"),
array("drôle","drôle","drôles","drôles"),
array("dur","dure","durs","dures"),
array("effrayé","effrayée","effrayés","effrayées"),
array("égal","égale","égaux","égales"),
array("électrique","électrique","électriques","électriques"),
array("énervé","énervée","énervés","énervées"),
array("énorme","énorme","énormes","énormes"),
array("entier","entière","entiers","entières"),
array("épais","épaise","épais","épaises"),
array("étroit","étroite","étroits","étroites"),
array("facile","facile","faciles","faciles"),
array("foncé","foncée","foncés","foncées"),
array("fort","forte","forts","fortes"),
array("fou","folle","fous","folles"),
array("fragile","fragile","fragiles","fragiles"),
array("froid","froide","froids","froides"),
array("gauche","gauche","gauches","gauches"),
array("gelé","gelée","gelés","gelées"),
array("gentil","gentille","gentils","gentilles"),
array("gourmand","gourmande","gourmands","gourmandes"),
array("grand","grande","grands","grandes"),
array("gris","grise","gris","grises"),
array("gros","grosse","gros","grosses"),
array("groupé","groupée","groupés","groupées"),
array("guéri","guérie","guéris","guéries"),
array("handicapé","handicapée","handicapés","handicapées"),
array("haut","haute","hauts","hautes"),
array("heureux","heureuse","heureux","heureuses"),
array("humide","humide","humides","humides"),
array("immense","immense","immenses","immenses"),
array("immobile","immobile","immobiles","immobiles"),
array("important","importante","importants","importantes"),
array("impossible","impossible","impossibles","impossibles"),
array("inséparable","inséparable","inséparables","inséparables"),
array("instable","instable","instables","instables"),
array("intéressant","intéressante","intéressants","intéressantes"),
array("jaloux","jalouse","jaloux","jalouses"),
array("jaune","jaune","jaunes","jaunes"),
array("jeune","jeune","jeunes","jeunes"),
array("joli","jolie","jolis","jolies"),
array("joyeux","joyeuse","joyeux","joyeuses"),
array("large","large","larges","larges"),
array("léger","légère","légers","légères"),
array("lent","lente","lents","lentes"),
array("lisse","lisse","lisses","lisses"),
array("long","longue","longs","longues"),
array("lourd","lourde","lourds","lourdes"),
array("maigre","maigre","maigres","maigres"),
array("malade","malade","malades","malades"),
array("maladroit","maladroite","maladroits","maladroites"),
array("mauvais","mauvaise","mauvais","mauvaises"),
array("méchant","méchante","méchants","méchantes"),
array("meilleur","meilleure","meilleurs","meilleures"),
array("même","même","mêmes","mêmes"),
array("mince","mince","minces","minces"),
array("moite","moite","moites","moites"),
array("mort","morte","morts","mortes"),
array("mouillé","mouillée","mouillés","mouillées"),
array("moyen","moyenne","moyens","moyennes"),
array("muet","muette","muets","muettes"),
array("multicolore","multicolore","multicolores","multicolores"),
array("mûr","mûre","mûrs","mûres"),
array("nain","naine","nains","naines"),
array("né","née","nés","nées"),
array("neuf","neuve","neufs","neuves"),
array("noir","noire","noirs","noires"),
array("nouveau","nouvelle","nouveaux","nouvelles"),
array("nu","nue","nus","nues"),
array("nuageux","nuageuse","nuageux","nuageuses"),
array("obèse","obèse","obèses","obèses"),
array("pâle","pâle","pâles","pâles"),
array("pareil","pareille","pareils","pareilles"),
array("patient","patiente","patients","patientes"),
array("petit","petite","petits","petites"),
array("plein","pleine","pleins","pleines"),
array("pluvieux","pluvieuse","pluvieux","pluvieuses"),
array("pointu","pointue","pointus","pointues"),
array("poli","polie","polis","polies"),
array("premier","première","premiers","premières"),
array("présent","présente","présents","présentes"),
array("prêt","prête","prêts","prêtes"),
array("profond","profonde","profonds","profondes"),
array("propre","propre","propres","propres"),
array("prudent","prudente","prudents","prudentes"),
array("rapide","rapide","rapides","rapides"),
array("riche","riche","riches","riches"),
array("rond","ronde","ronds","rondes"),
array("rouge","rouge","rouges","rouges"),
array("roux","rousse","roux","rousses"),
array("rugueux","rugueuse","rugueux","rugueuses"),
array("sage","sage","sages","sages"),
array("sale","sale","sales","sales"),
array("sec","sèche","secs","sèches"),
array("sérieux","sérieuse","sérieux","sérieuses"),
array("serré","serrée","serrés","serrées"),
array("solide","solide","solides","solides"),
array("solitaire","solitaire","solitaires","solitaires"),
array("sombre","sombre","sombres","sombres"),
array("souple","souple","souples","souples"),
array("sourd","sourde","sourds","sourdes"),
array("terrible","terrible","terribles","terribles"),
array("tordu","tordue","tordus","tordues"),
array("tranquille","tranquille","tranquilles","tranquilles"),
array("transparent","transparente","transparents","transparentes"),
array("triste","triste","tristes","tristes"),
array("usé","usée","usés","usées"),
array("utile","utile","utiles","utiles"),
array("vert","verte","verts","vertes"),
array("vide","vide","vides","vides"),
array("vieux","vieille","vieux","vieilles"),
array("vivant","vivante","vivants","vivantes")
);

private $noms = array
(
array("Abeille", "l'abeille", "les abeilles", "mon abeille", "mes abeilles", "f"),
array("Abricot", "l'abricot", "les abricots", "mon abricot", "mes abricots", "m"),
array("Accident", "l'accident", "les accidents", "mon accident", "mes accidents", "m"),
array("Acrobate", "l'acrobate", "les acrobates", "mon acrobate", "mes acrobates", "m"),
array("Adresse", "l'adresse", "les adresses", "mon adresse", "mes adresses", "f"),
array("Adulte", "l'adulte", "les adultes", "mon adulte", "mes adultes", "m"),
array("Aéroport", "l'aéroport", "les aéroports", "mon aéroport", "mes aéroports", "m"),
array("Affaire", "l'affaire", "les affaires", "mon affaire", "mes affaires", "f"),
array("Affiche", "l'affiche", "les affiches", "mon affiche", "mes affiches", "f"),
array("Âge", "l'âge", "les âges", "mon âge", "mes âges", "m"),
array("Agneau", "l'agneau", "les agneaux", "mon agneau", "mes agneaux", "m"),
array("Aigle", "l'aigle", "les aigles", "mon aigle", "mes aigles", "m"),
array("Aiguille", "l'aiguille", "les aiguilles", "mon aiguille", "mes aiguilles", "f"),
array("Aile", "l'aile", "les ailes", "mon aile", "mes ailes", "f"),
array("Air", "l'air", "les airs", "mon air", "mes airs", "m"),
array("Album", "l'album", "les albums", "mon album", "mes albums", "m"),
array("Aliment", "l'aliment", "les aliments", "mon aliment", "mes aliments", "m"),
array("Allumette", "l'allumette", "les allumettes", "mon allumette", "mes allumettes", "f"),
array("Alphabet", "l'alphabet", "les alphabets", "mon alphabet", "mes alphabets", "m"),
array("Ambulance", "l'ambulance", "les ambulances", "mon ambulance", "mes ambulances", "f"),
array("Ami", "l'ami", "les amis", "mon ami", "mes amis", "m"),
array("Amour", "l'amour", "les amours", "mon amour", "mes amours", "m"),
array("Ampoule", "l'ampoule", "les ampoules", "mon ampoule", "mes ampoules", "f"),
array("Année", "l'année", "les années", "mon année", "mes années", "f"),
array("Ananas", "l'ananas", "les ananas", "mon ananas", "mes ananas", "m"),
array("Âne", "l'âne", "les ânes", "mon âne", "mes ânes", "m"),
array("Angle", "l'angle", "les angles", "mon angle", "mes angles", "m"),
array("Animal", "l'animal", "les animaux", "mon animal", "mes animaux", "m"),
array("Année", "l'année", "les années", "mon année", "mes années", "f"),
array("Anniversaire", "l'anniversaire", "les anniversaires", "mon anniversaire", "mes anniversaires", "m"),
array("Anorak", "l'anorak", "les anoraks", "mon anorak", "mes anoraks", "m"),
array("Appareil", "l'appareil", "les appareils", "mon appareil", "mes appareils", "m"),
array("Appartement", "l'appartement", "les appartements", "mon appartement", "mes appartements", "m"),
array("Appétit", "l'appétit", "les appétits", "mon appétit", "mes appétits", "m"),
array("Après-midi", "l'après-midi", "les après-midis", "mon après-midi", "mes après-midis", "m"),
array("Aquarium", "l'aquarium", "les aquariums", "mon aquarium", "mes aquariums", "m"),
array("Araignée", "l'araignée", "les araignées", "mon araignée", "mes araignées", "f"),
array("Arbre", "l'arbre", "les arbres", "mon arbre", "mes arbres", "m"),
array("Arc", "l'arc", "les arcs", "mon arc", "mes arcs", "m"),
array("Arc-en-ciel", "l'arc-en-ciel", "les arcs-en-ciel", "mon arc-en-ciel", "mes arcs-en-ciel", "m"),
array("Arête", "l'arête", "les arêtes", "mon arête", "mes arêtes", "f"),
array("Argent", "l'argent", "les argents", "mon argent", "mes argents", "m"),
array("Armoire", "l'armoire", "les armoires", "mon armoire", "mes armoires", "f"),
array("Arrêt", "l'arrêt", "les arrêts", "mon arrêt", "mes arrêts", "m"),
array("Arrière", "l'arrière", "les arrières", "mon arrière", "mes arrières", "m"),
array("Arrosoir", "l'arrosoir", "les arrosoirs", "mon arrosoir", "mes arrosoirs", "m"),
array("Ascenseur", "l'ascenseur", "les ascenseurs", "mon ascenseur", "mes ascenseurs", "m"),
array("Aspirateur", "l'aspirateur", "les aspirateurs", "mon aspirateur", "mes aspirateurs", "m"),
array("Assiette", "l'assiette", "les assiettes", "mon assiette", "mes assiettes", "f"),
array("Attention", "l'attention", "les attentions", "mon attention", "mes attentions", "f"),
array("Auto", "l'auto", "les autos", "mon auto", "mes autos", "f"),
array("Avion", "l'avion", "les avions", "mon avion", "mes avions", "m"),
array("Bagage", "le bagage", "les bagages", "mon bagage", "mes bagages", "m"),
array("Bagarre", "la bagarre", "les bagarres", "ma bagarre", "mes bagarres", "f"),
array("Bague", "la bague", "les bagues", "ma bague", "mes bagues", "f"),
array("Baguette", "la baguette", "les baguettes", "ma baguette", "mes baguettes", "f"),
array("Bain", "le bain", "les bains", "mon bain", "mes bains", "m"),
array("Baiser", "le baiser", "les baisers", "mon baiser", "mes baisers", "m"),
array("Balai", "le balai", "les balais", "mon balai", "mes balais", "m"),
array("Balançoire", "la balançoire", "les balançoires", "ma balançoire", "mes balançoires", "f"),
array("Balcon", "le balcon", "les balcons", "mon balcon", "mes balcons", "m"),
array("Baleine", "la baleine", "les baleines", "ma baleine", "mes baleines", "f"),
array("Balle", "la balle", "les balles", "ma balle", "mes balles", "f"),
array("Ballon", "le ballon", "les ballons", "mon ballon", "mes ballons", "m"),
array("Banane", "la banane", "les bananes", "ma banane", "mes bananes", "f"),
array("Banc", "le banc", "les bancs", "mon banc", "mes bancs", "m"),
array("Bande", "la bande", "les bandes", "ma bande", "mes bandes", "f"),
array("Bande dessinée", "la bande dessinée", "les bandes dessinées", "ma bande dessinée", "mes bandes dessinées", "f"),
array("Barbe", "la barbe", "les barbes", "ma barbe", "mes barbes", "f"),
array("Barque", "la barque", "les barques", "ma barque", "mes barques", "f"),
array("Barre", "la barre", "les barres", "ma barre", "mes barres", "f"),
array("Barreau", "le barreau", "les barreaux", "mon barreau", "mes barreaux", "m"),
array("Barrette", "la barrette", "les barrettes", "ma barrette", "mes barrettes", "f"),
array("Bassin", "le bassin", "les bassins", "mon bassin", "mes bassins", "m"),
array("Bassine", "la bassine", "les bassines", "ma bassine", "mes bassines", "f"),
array("Bateau", "le bateau", "les bateaux", "mon bateau", "mes bateaux", "m"),
array("Bâton", "le bâton", "les bâtons", "mon bâton", "mes bâtons", "m"),
array("Bavoir", "le bavoir", "les bavoirs", "mon bavoir", "mes bavoirs", "m"),
array("Bébé", "le bébé", "les bébés", "mon bébé", "mes bébés", "m"),
array("Bec", "le bec", "les becs", "mon bec", "mes becs", "m"),
array("Bête", "la bête", "les bêtes", "ma bête", "mes bêtes", "f"),
array("Bêtise", "la bêtise", "les bêtises", "ma bêtise", "mes bêtises", "f"),
array("Biberon", "le biberon", "les biberons", "mon biberon", "mes biberons", "m"),
array("Bibliothèque", "la bibliothèque", "les bibliothèques", "ma bibliothèque", "mes bibliothèques", "f"),
array("Bicyclette", "la bicyclette", "les bicyclettes", "ma bicyclette", "mes bicyclettes", "f"),
array("Bifteck", "le bifteck", "les biftecks", "mon bifteck", "mes biftecks", "m"),
array("Bijou", "le bijou", "les bijoux", "mon bijou", "mes bijoux", "m"),
array("Bille", "la bille", "les billes", "ma bille", "mes billes", "f"),
array("Billet", "le billet", "les billets", "mon billet", "mes billets", "m"),
array("Biscuit", "le biscuit", "les biscuits", "mon biscuit", "mes biscuits", "m"),
array("Bisou", "le bisou", "les bisous", "mon bisou", "mes bisous", "m"),
array("Boeuf", "le boeuf", "les boeufs", "mon boeuf", "mes boeufs", "m"),
array("Bois", "le bois", "les bois", "mon bois", "mes bois", "m"),
array("Boisson", "la boisson", "les boissons", "ma boisson", "mes boissons", "f"),
array("Boîte", "la boîte", "les boîtes", "ma boîte", "mes boîtes", "f"),
array("Bol", "le bol", "les bols", "mon bol", "mes bols", "m"),
array("Bonbon", "le bonbon", "les bonbons", "mon bonbon", "mes bonbons", "m"),
array("Bonhomme", "le bonhomme", "les bonshommes", "mon bonhomme", "mes bonshommes", "m"),
array("Bonnet", "le bonnet", "les bonnets", "mon bonnet", "mes bonnets", "m"),
array("Bord", "le bord", "les bords", "mon bord", "mes bords", "m"),
array("Bosse", "la bosse", "les bosses", "ma bosse", "mes bosses", "f"),
array("Botte", "la botte", "les bottes", "ma botte", "mes bottes", "f"),
array("Botte de foin", "la botte de foin", "les bottes de foin", "ma botte de foin", "mes bottes de foin", "f"),
array("Bouche", "la bouche", "les bouches", "ma bouche", "mes bouches", "f"),
array("Boucherie", "la boucherie", "les boucheries", "ma boucherie", "mes boucheries", "f"),
array("Bouchon", "le bouchon", "les bouchons", "mon bouchon", "mes bouchons", "m"),
array("Boue", "la boue", "les boues", "ma boue", "mes boues", "f"),
array("Bouée", "la bouée", "les bouées", "ma bouée", "mes bouées", "f"),
array("Boulanger", "le boulanger", "les boulangers", "mon boulanger", "mes boulangers", "m"),
array("Boulangerie", "la boulangerie", "les boulangeries", "ma boulangerie", "mes boulangeries", "f"),
array("Boule", "la boule", "les boules", "ma boule", "mes boules", "f"),
array("Bouquet", "le bouquet", "les bouquets", "mon bouquet", "mes bouquets", "m"),
array("Bourgeon", "le bourgeon", "les bourgeons", "mon bourgeon", "mes bourgeons", "m"),
array("Bout", "le bout", "les bouts", "mon bout", "mes bouts", "m"),
array("Bouteille", "la bouteille", "les bouteilles", "ma bouteille", "mes bouteilles", "f"),
array("Boutique", "la boutique", "les boutiques", "ma boutique", "mes boutiques", "f"),
array("Bouton", "le bouton", "les boutons", "mon bouton", "mes boutons", "m"),
array("Bracelet", "le bracelet", "les bracelets", "mon bracelet", "mes bracelets", "m"),
array("Branche", "la branche", "les branches", "ma branche", "mes branches", "f"),
array("Bras", "le bras", "les bras", "mon bras", "mes bras", "m"),
array("Bretelle", "la bretelle", "les bretelles", "ma bretelle", "mes bretelles", "f"),
array("Bricolage", "le bricolage", "les bricolages", "mon bricolage", "mes bricolages", "m"),
array("Brosse", "la brosse", "les brosses", "ma brosse", "mes brosses", "f"),
array("Brouette", "la brouette", "les brouettes", "ma brouette", "mes brouettes", "f"),
array("Brouillard", "le brouillard", "les brouillards", "mon brouillard", "mes brouillards", "m"),
array("Bruit", "le bruit", "les bruits", "mon bruit", "mes bruits", "m"),
array("Bûche", "la bûche", "les bûches", "ma bûche", "mes bûches", "f"),
array("Buisson", "le buisson", "les buissons", "mon buisson", "mes buissons", "m"),
array("Bulle", "la bulle", "les bulles", "ma bulle", "mes bulles", "f"),
array("Bureau", "le bureau", "les bureaux", "mon bureau", "mes bureaux", "m"),
array("Bus", "le bus", "les bus", "mon bus", "mes bus", "m"),
array("Cabane", "la cabane", "les cabanes", "ma cabane", "mes cabanes", "f"),
array("Cabinet", "le cabinet", "les cabinets", "mon cabinet", "mes cabinets", "m"),
array("Cadeau", "le cadeau", "les cadeaux", "mon cadeau", "mes cadeaux", "m"),
array("Cadenas", "le cadenas", "les cadenas", "mon cadenas", "mes cadenas", "m"),
array("Cadre", "le cadre", "les cadres", "mon cadre", "mes cadres", "m"),
array("Café", "le café", "les cafés", "mon café", "mes cafés", "m"),
array("Cage", "la cage", "les cages", "ma cage", "mes cages", "f"),
array("Cage à écureuil", "la cage à écureuil", "les cages à écureuils", "ma cage à écureuil", "mes cages à écureuils", "f"),
array("Cagoule", "la cagoule", "les cagoules", "ma cagoule", "mes cagoules", "f"),
array("Cahier", "le cahier", "les cahiers", "mon cahier", "mes cahiers", "m"),
array("Caillou", "le caillou", "les cailloux", "mon caillou", "mes cailloux", "m"),
array("Caisse", "la caisse", "les caisses", "ma caisse", "mes caisses", "f"),
array("Calendrier", "le calendrier", "les calendriers", "mon calendrier", "mes calendriers", "m"),
array("Câlin", "le câlin", "les câlins", "mon câlin", "mes câlins", "m"),
array("Camarade", "le camarade", "les camarades", "mon camarade", "mes camarades", "m"),
array("Caméscope", "le caméscope", "les caméscopes", "mon caméscope", "mes caméscopes", "m"),
array("Camion", "le camion", "les camions", "mon camion", "mes camions", "m"),
array("Camp", "le camp", "les camps", "mon camp", "mes camps", "m"),
array("Campagne", "la campagne", "les campagnes", "ma campagne", "mes campagnes", "f"),
array("Canapé", "le canapé", "les canapés", "mon canapé", "mes canapés", "m"),
array("Canard", "le canard", "les canards", "mon canard", "mes canards", "m"),
array("Caniveau", "le caniveau", "les caniveaux", "mon caniveau", "mes caniveaux", "m"),
array("Canne", "la canne", "les cannes", "ma canne", "mes cannes", "f"),
array("Canne à pêche", "la canne à pêche", "les cannes à pêche", "ma canne à pêche", "mes cannes à pêche", "f"),
array("Caprice", "le caprice", "les caprices", "mon caprice", "mes caprices", "m"),
array("Car", "le car", "les cars", "mon car", "mes cars", "m"),
array("Caravane", "la caravane", "les caravanes", "ma caravane", "mes caravanes", "f"),
array("Caresse", "la caresse", "les caresses", "ma caresse", "mes caresses", "f"),
array("Carnet", "le carnet", "les carnets", "mon carnet", "mes carnets", "m"),
array("Carotte", "la carotte", "les carottes", "ma carotte", "mes carottes", "f"),
array("Carré", "le carré", "les carrés", "mon carré", "mes carrés", "m"),
array("Carreau", "le carreau", "les carreaux", "mon carreau", "mes carreaux", "m"),
array("Carrefour", "le carrefour", "les carrefours", "mon carrefour", "mes carrefours", "m"),
array("Cartable", "le cartable", "les cartables", "mon cartable", "mes cartables", "m"),
array("Carton", "le carton", "les cartons", "mon carton", "mes cartons", "m"),
array("Casier", "le casier", "les casiers", "mon casier", "mes casiers", "m"),
array("Casque", "le casque", "les casques", "mon casque", "mes casques", "m"),
array("Casquette", "la casquette", "les casquettes", "ma casquette", "mes casquettes", "f"),
array("Casserole", "la casserole", "les casseroles", "ma casserole", "mes casseroles", "f"),
array("Cassette", "la cassette", "les cassettes", "ma cassette", "mes cassettes", "f"),
array("Catalogue", "le catalogue", "les catalogues", "mon catalogue", "mes catalogues", "m"),
array("Cauchemar", "le cauchemar", "les cauchemars", "mon cauchemar", "mes cauchemars", "m"),
array("Cave", "la cave", "les caves", "ma cave", "mes caves", "f"),
array("CD-ROM", "le CD-ROM", "les CD-ROMs", "mon CD-ROM", "mes CD-ROMs", "m"),
array("Ceinture", "la ceinture", "les ceintures", "ma ceinture", "mes ceintures", "f"),
array("Cerceau", "le cerceau", "les cerceaux", "mon cerceau", "mes cerceaux", "m"),
array("Céréale", "la céréale", "les céréales", "ma céréale", "mes céréales", "f"),
array("Cerf", "le cerf", "les cerfs", "mon cerf", "mes cerfs", "m"),
array("Cerf-volant", "le cerf-volant", "les cerf-volants", "mon cerf-volant", "mes cerf-volants", "m"),
array("Cerise", "la cerise", "les cerises", "ma cerise", "mes cerises", "f"),
array("Chaîne", "la chaîne", "les chaînes", "ma chaîne", "mes chaînes", "f"),
array("Chaise", "la chaise", "les chaises", "ma chaise", "mes chaises", "f"),
array("Chambre", "la chambre", "les chambres", "ma chambre", "mes chambres", "f"),
array("Champ", "le champ", "les champs", "mon champ", "mes champs", "m"),
array("Champignon", "le champignon", "les champignons", "mon champignon", "mes champignons", "m"),
array("Chance", "la chance", "les chances", "ma chance", "mes chances", "f"),
array("Chanson", "la chanson", "les chansons", "ma chanson", "mes chansons", "f"),
array("Chapeau", "le chapeau", "les chapeaux", "mon chapeau", "mes chapeaux", "m"),
array("Charcuterie", "la charcuterie", "les charcuteries", "ma charcuterie", "mes charcuteries", "f"),
array("Chariot", "le chariot", "les chariots", "mon chariot", "mes chariots", "m"),
array("Chasseur", "le chasseur", "les chasseurs", "mon chasseur", "mes chasseurs", "m"),
array("Chat", "le chat", "les chats", "mon chat", "mes chats", "m"),
array("Châtaigne", "la châtaigne", "les châtaignes", "ma châtaigne", "mes châtaignes", "f"),
array("Château", "le château", "les châteaux", "mon château", "mes châteaux", "m"),
array("Chaussette", "la chaussette", "les chaussettes", "ma chaussette", "mes chaussettes", "f"),
array("Chausson", "le chausson", "les chaussons", "mon chausson", "mes chaussons", "m"),
array("Chaussure", "la chaussure", "les chaussures", "ma chaussure", "mes chaussures", "m"),
array("Chemin", "le chemin", "les chemins", "mon chemin", "mes chemins", "m"),
array("Cheminée", "la cheminée", "les cheminées", "ma cheminée", "mes cheminées", "f"),
array("Chemise", "la chemise", "les chemises", "ma chemise", "mes chemises", "f"),
array("Chêne", "le chêne", "les chênes", "mon chêne", "mes chênes", "m"),
array("Chenille", "la chenille", "les chenilles", "ma chenille", "mes chenilles", "f"),
array("Cheval", "le cheval", "les chevaux", "mon cheval", "mes chevaux", "m"),
array("Cheveu", "le cheveu", "les cheveux", "mon cheveu", "mes cheveux", "m"),
array("Cheville", "la cheville", "les chevilles", "ma cheville", "mes chevilles", "f"),
array("Chèvre", "la chèvre", "les chèvres", "ma chèvre", "mes chèvres", "f"),
array("Chien", "le chien", "les chiens", "mon chien", "mes chiens", "m"),
array("Chiffon", "le chiffon", "les chiffons", "mon chiffon", "mes chiffons", "m"),
array("Chiffre", "le chiffre", "les chiffres", "mon chiffre", "mes chiffres", "m"),
array("Chocolat", "le chocolat", "les chocolats", "mon chocolat", "mes chocolats", "m"),
array("Chose", "la chose", "les choses", "ma chose", "mes choses", "f"),
array("Chou", "le chou", "les choux", "mon chou", "mes choux", "m"),
array("Chouette", "la chouette", "les chouettes", "ma chouette", "mes chouettes", "f"),
array("Chute", "la chute", "les chutes", "ma chute", "mes chutes", "f"),
array("Ciel", "le ciel", "les ciels", "mon ciel", "mes ciels", "m"),
array("Cigarette", "la cigarette", "les cigarettes", "ma cigarette", "mes cigarettes", "f"),
array("Cigogne", "la cigogne", "les cigognes", "ma cigogne", "mes cigognes", "f"),
array("Cil", "le cil", "les cils", "mon cil", "mes cils", "m"),
array("Cimetière", "le cimetière", "les cimetières", "mon cimetière", "mes cimetières", "m"),
array("Cinéma", "le cinéma", "les cinémas", "mon cinéma", "mes cinémas", "m"),
array("Cirque", "le cirque", "les cirques", "mon cirque", "mes cirques", "m"),
array("Ciseau", "le ciseau", "les ciseaux", "mon ciseau", "mes ciseaux", "m"),
array("Citron", "le citron", "les citrons", "mon citron", "mes citrons", "m"),
array("Citrouille", "la citrouille", "les citrouilles", "ma citrouille", "mes citrouilles", "f"),
array("Classe", "la classe", "les classes", "ma classe", "mes classes", "f"),
array("Clé", "la clé", "les clés", "ma clé", "mes clés", "f"),
array("Clémentine", "la clémentine", "les clémentines", "ma clémentine", "mes clémentines", "f"),
array("Clin d’oeil", "le clin d’oeil", "les clins d’oeil", "mon clin d’oeil", "mes clins d’oeil", "m"),
array("Cloche", "la cloche", "les cloches", "ma cloche", "mes cloches", "f"),
array("Clocher", "le clocher", "les clochers", "mon clocher", "mes clochers", "m"),
array("Clou", "le clou", "les clous", "mon clou", "mes clous", "m"),
array("Clown", "le clown", "les clowns", "mon clown", "mes clowns", "m"),
array("Coccinelle", "la coccinelle", "les coccinelles", "ma coccinelle", "mes coccinelles", "f"),
array("Cochon", "le cochon", "les cochons", "mon cochon", "mes cochons", "m"),
array("Cochon d’Inde", "le cochon d’Inde", "les cochons d’Inde", "mon cochon d’Inde", "mes cochons d’Inde", "m"),
array("Cocotte", "la cocotte", "les cocottes", "ma cocotte", "mes cocottes", "f"),
array("Coeur", "le coeur", "les coeurs", "mon coeur", "mes coeurs", "m"),
array("Coffre", "le coffre", "les coffres", "mon coffre", "mes coffres", "m"),
array("Coffret", "le coffret", "les coffrets", "mon coffret", "mes coffrets", "m"),
array("Coiffeur", "le coiffeur", "les coiffeurs", "mon coiffeur", "mes coiffeurs", "m"),
array("Coin", "le coin", "les coins", "mon coin", "mes coins", "m"),
array("Col", "le col", "les cols", "mon col", "mes cols", "m"),
array("Colère", "la colère", "les colères", "ma colère", "mes colères", "f"),
array("Collant", "le collant", "les collants", "mon collant", "mes collants", "m"),
array("Colle", "la colle", "les colles", "ma colle", "mes colles", "f"),
array("Collier", "le collier", "les colliers", "mon collier", "mes colliers", "m"),
array("Colline", "la colline", "les collines", "ma colline", "mes collines", "f"),
array("Coloriage", "le coloriage", "les coloriages", "mon coloriage", "mes coloriages", "m"),
array("Concombre", "le concombre", "les concombres", "mon concombre", "mes concombres", "m"),
array("Confiture", "la confiture", "les confitures", "ma confiture", "mes confitures", "f"),
array("Conte", "le conte", "les contes", "mon conte", "mes contes", "m"),
array("Contraire", "le contraire", "les contraires", "mon contraire", "mes contraires", "m"),
array("Copain", "le copain", "les copains", "mon copain", "mes copains", "m"),
array("Coq", "le coq", "les coqs", "mon coq", "mes coqs", "m"),
array("Coquelicot", "le coquelicot", "les coquelicots", "mon coquelicot", "mes coquelicots", "m"),
array("Coquetier", "le coquetier", "les coquetiers", "mon coquetier", "mes coquetiers", "m"),
array("Coquillage", "le coquillage", "les coquillages", "mon coquillage", "mes coquillages", "m"),
array("Coquille", "la coquille", "les coquilles", "ma coquille", "mes coquilles", "f"),
array("Coquin", "le coquin", "les coquins", "mon coquin", "mes coquins", "m"),
array("Corbeau", "le corbeau", "les corbeaux", "mon corbeau", "mes corbeaux", "m"),
array("Corbeille", "la corbeille", "les corbeilles", "ma corbeille", "mes corbeilles", "f"),
array("Corde", "la corde", "les cordes", "ma corde", "mes cordes", "f"),
array("Corps", "le corps", "les corps", "mon corps", "mes corps", "m"),
array("Côté", "le côté", "les côtés", "mon côté", "mes côtés", "m"),
array("Cou", "le cou", "les cous", "mon cou", "mes cous", "m"),
array("Coude", "le coude", "les coudes", "mon coude", "mes coudes", "m"),
array("Couette", "la couette", "les couettes", "ma couette", "mes couettes", "f"),
array("Couleur", "la couleur", "les couleurs", "ma couleur", "mes couleurs", "f"),
array("Couloir", "le couloir", "les couloirs", "mon couloir", "mes couloirs", "m"),
array("Coup", "le coup", "les coups", "mon coup", "mes coups", "m"),
array("Cour", "la cour", "les cours", "ma cour", "mes cours", "f"),
array("Couronne", "la couronne", "les couronnes", "ma couronne", "mes couronnes", "f"),
array("Courrier", "le courrier", "les courriers", "mon courrier", "mes courriers", "m"),
array("Course", "la course", "les courses", "ma course", "mes courses", "f"),
array("Cousin", "le cousin", "les cousins", "mon cousin", "mes cousins", "m"),
array("Cousine", "la cousine", "les cousines", "ma cousine", "mes cousines", "f"),
array("Coussin", "le coussin", "les coussins", "mon coussin", "mes coussins", "m"),
array("Couteau", "le couteau", "les couteaux", "mon couteau", "mes couteaux", "m"),
array("Couvercle", "le couvercle", "les couvercles", "mon couvercle", "mes couvercles", "m"),
array("Couvert", "le couvert", "les couverts", "mon couvert", "mes couverts", "m"),
array("Couverture", "la couverture", "les couvertures", "ma couverture", "mes couvertures", "f"),
array("Crabe", "le crabe", "les crabes", "mon crabe", "mes crabes", "m"),
array("Craie", "la craie", "les craies", "ma craie", "mes craies", "f"),
array("Crapaud", "le crapaud", "les crapauds", "mon crapaud", "mes crapauds", "m"),
array("Cravate", "la cravate", "les cravates", "ma cravate", "mes cravates", "f"),
array("Crayon", "le crayon", "les crayons", "mon crayon", "mes crayons", "m"),
array("Crèche", "la crèche", "les crèches", "ma crèche", "mes crèches", "f"),
array("Crêpe", "la crêpe", "les crêpes", "ma crêpe", "mes crêpes", "f"),
array("Crevette", "la crevette", "les crevettes", "ma crevette", "mes crevettes", "f"),
array("Cri", "le cri", "les cris", "mon cri", "mes cris", "m"),
array("Crochet", "le crochet", "les crochets", "mon crochet", "mes crochets", "m"),
array("Crocodile", "le crocodile", "les crocodiles", "mon crocodile", "mes crocodiles", "m"),
array("Croix", "la croix", "les croix", "ma croix", "mes croix", "f"),
array("Croûte", "la croûte", "les croûtes", "ma croûte", "mes croûtes", "f"),
array("Cube", "le cube", "les cubes", "mon cube", "mes cubes", "m"),
array("Cuillère", "la cuillère", "les cuillères", "ma cuillère", "mes cuillères", "f"),
array("Cuisine", "la cuisine", "les cuisines", "ma cuisine", "mes cuisines", "f"),
array("Cuisinière", "la cuisinière", "les cuisinières", "ma cuisinière", "mes cuisinières", "f"),
array("Cuisse", "la cuisse", "les cuisses", "ma cuisse", "mes cuisses", "f"),
array("Culotte", "la culotte", "les culottes", "ma culotte", "mes culottes", "f"),
array("Cuvette", "la cuvette", "les cuvettes", "ma cuvette", "mes cuvettes", "f"),
array("Cygne", "le cygne", "les cygnes", "mon cygne", "mes cygnes", "m"),
array("Dame", "la dame", "les dames", "ma dame", "mes dames", "f"),
array("Danger", "le danger", "les dangers", "mon danger", "mes dangers", "m"),
array("Danse", "la danse", "les danses", "ma danse", "mes danses", "f"),
array("Dauphin", "le dauphin", "les dauphins", "mon dauphin", "mes dauphins", "m"),
array("Dé", "le dé", "les dés", "mon dé", "mes dés", "m"),
array("Début", "le début", "les débuts", "mon début", "mes débuts", "m"),
array("Découpage", "le découpage", "les découpages", "mon découpage", "mes découpages", "m"),
array("Déguisement", "le déguisement", "les déguisements", "mon déguisement", "mes déguisements", "m"),
array("Dent", "la dent", "les dents", "ma dent", "mes dents", "f"),
array("Dentifrice", "le dentifrice", "les dentifrices", "mon dentifrice", "mes dentifrices", "m"),
array("Dentiste", "le dentiste", "les dentistes", "mon dentiste", "mes dentistes", "m"),
array("Départ", "le départ", "les départs", "mon départ", "mes départs", "m"),
array("Désordre", "le désordre", "les désordres", "mon désordre", "mes désordres", "m"),
array("Dessert", "le dessert", "les desserts", "mon dessert", "mes desserts", "m"),
array("Dessin", "le dessin", "les dessins", "mon dessin", "mes dessins", "m"),
array("Dictionnaire", "le dictionnaire", "les dictionnaires", "mon dictionnaire", "mes dictionnaires", "m"),
array("Différence", "la différence", "les différences", "ma différence", "mes différences", "f"),
array("Dimanche", "le dimanche", "les dimanches", "mon dimanche", "mes dimanches", "m"),
array("Dindon", "le dindon", "les dindons", "mon dindon", "mes dindons", "m"),
array("Dînette", "la dînette", "les dînettes", "ma dînette", "mes dînettes", "f"),
array("Dinosaure", "le dinosaure", "les dinosaures", "mon dinosaure", "mes dinosaures", "m"),
array("Directeur", "le directeur", "les directeurs", "mon directeur", "mes directeurs", "m"),
array("Directrice", "la directrice", "les directrices", "ma directrice", "mes directrices", "f"),
array("Docteur", "le docteur", "les docteurs", "mon docteur", "mes docteurs", "m"),
array("Doigt", "le doigt", "les doigts", "mon doigt", "mes doigts", "m"),
array("Domino", "le domino", "les dominos", "mon domino", "mes dominos", "m"),
array("Dos", "le dos", "les dos", "mon dos", "mes dos", "m"),
array("Dossier", "le dossier", "les dossiers", "mon dossier", "mes dossiers", "m"),
array("Douche", "la douche", "les douches", "ma douche", "mes douches", "f"),
array("Drap", "le drap", "les draps", "mon drap", "mes draps", "m"),
array("Drapeau", "le drapeau", "les drapeaux", "mon drapeau", "mes drapeaux", "m"),
array("Droit", "le droit", "les droits", "mon droit", "mes droits", "m"),
array("Eau", "l'eau", "les eaux", "mon eau", "mes eaux", "f"),
array("Écharpe", "l'écharpe", "les écharpes", "mon écharpe", "mes écharpes", "f"),
array("Échasse", "l'échasse", "les échasses", "mon échasse", "mes échasses", "f"),
array("Échelle", "l'échelle", "les échelles", "mon échelle", "mes échelles", "f"),
array("Éclair", "l'éclair", "les éclairs", "mon éclair", "mes éclairs", "m"),
array("École", "l'école", "les écoles", "mon école", "mes écoles", "f"),
array("Écorce", "l'écorce", "les écorces", "mon écorce", "mes écorces", "f"),
array("Écran", "l'écran", "les écrans", "mon écran", "mes écrans", "m"),
array("Écriture", "l'écriture", "les écritures", "mon écriture", "mes écritures", "f"),
array("Écureuil", "l'écureuil", "les écureuils", "mon écureuil", "mes écureuils", "m"),
array("Effort", "l'effort", "les efforts", "mon effort", "mes efforts", "m"),
array("Église", "l'église", "les églises", "mon église", "mes églises", "f"),
array("Élastique", "l'élastique", "les élastiques", "mon élastique", "mes élastiques", "m"),
array("Éléphant", "l'éléphant", "les éléphants", "mon éléphant", "mes éléphants", "m"),
array("Élève", "l'élève", "les élèves", "mon élève", "mes élèves", "m"),
array("Embouteillage", "l'embouteillage", "les embouteillages", "mon embouteillage", "mes embouteillages", "m"),
array("Endive", "l'endive", "les endives", "mon endive", "mes endives", "f"),
array("Endroit", "l'endroit", "les endroits", "mon endroit", "mes endroits", "m"),
array("Enfant", "l'enfant", "les enfants", "mon enfant", "mes enfants", "m"),
array("Engin", "l'engin", "les engins", "mon engin", "mes engins", "m"),
array("Entonnoir", "l'entonnoir", "les entonnoirs", "mon entonnoir", "mes entonnoirs", "m"),
array("Entrée", "l'entrée", "les entrées", "mon entrée", "mes entrées", "f"),
array("Enveloppe", "l'enveloppe", "les enveloppes", "mon enveloppe", "mes enveloppes", "f"),
array("Envie", "l'envie", "les envies", "mon envie", "mes envies", "f"),
array("Épaule", "l'épaule", "les épaules", "mon épaule", "mes épaules", "f"),
array("Épée", "l'épée", "les épées", "mon épée", "mes épées", "f"),
array("Épingle", "l'épingle", "les épingles", "mon épingle", "mes épingles", "f"),
array("Épluchure", "l'épluchure", "les épluchures", "mon épluchure", "mes épluchures", "f"),
array("Éponge", "l'éponge", "les éponges", "mon éponge", "mes éponges", "f"),
array("Équipe", "l'équipe", "les équipes", "mon équipe", "mes équipes", "f"),
array("Escabeau", "l'escabeau", "les escabeaux", "mon escabeau", "mes escabeaux", "m"),
array("Escalier", "l'escalier", "les escaliers", "mon escalier", "mes escaliers", "m"),
array("Escargot", "l'escargot", "les escargots", "mon escargot", "mes escargots", "m"),
array("Essence", "l'essence", "les essences", "mon essence", "mes essences", "f"),
array("Étagère", "l'étagère", "les étagères", "mon étagère", "mes étagères", "f"),
array("Étang", "l'étang", "les étangs", "mon étang", "mes étangs", "m"),
array("Été", "l'été", "les étés", "mon été", "mes étés", "m"),
array("Étiquette", "l'étiquette", "les étiquettes", "mon étiquette", "mes étiquettes", "f"),
array("Étoile", "l'étoile", "les étoiles", "mon étoile", "mes étoiles", "f"),
array("Étude", "l'étude", "les études", "mon étude", "mes études", "f"),
array("Évier", "l'évier", "les éviers", "mon évier", "mes éviers", "m"),
array("Extérieur", "l'extérieur", "les extérieurs", "mon extérieur", "mes extérieurs", "m"),
array("Facteur", "le facteur", "les facteurs", "mon facteur", "mes facteurs", "m"),
array("Faim", "la faim", "les faims", "ma faim", "mes faims", "f"),
array("Farce", "la farce", "les farces", "ma farce", "mes farces", "f"),
array("Farine", "la farine", "les farines", "ma farine", "mes farines", "f"),
array("Fatigue", "la fatigue", "les fatigues", "ma fatigue", "mes fatigues", "f"),
array("Faute", "la faute", "les fautes", "ma faute", "mes fautes", "f"),
array("Fauteuil", "le fauteuil", "les fauteuils", "mon fauteuil", "mes fauteuils", "m"),
array("Fée", "la fée", "les fées", "ma fée", "mes fées", "f"),
array("Femme", "la femme", "les femmes", "ma femme", "mes femmes", "f"),
array("Fenêtre", "la fenêtre", "les fenêtres", "ma fenêtre", "mes fenêtres", "f"),
array("Fer à repasser", "le fer à repasser", "les fers à repasser", "mon fer à repasser", "mes fers à repasser", "m"),
array("Ferme", "la ferme", "les fermes", "ma ferme", "mes fermes", "f"),
array("Fermier", "le fermier", "les fermiers", "mon fermier", "mes fermiers", "m"),
array("Fesse", "la fesse", "les fesses", "ma fesse", "mes fesses", "f"),
array("Fête", "la fête", "les fêtes", "ma fête", "mes fêtes", "f"),
array("Feu", "le feu", "les feux", "mon feu", "mes feux", "m"),
array("Feuille", "la feuille", "les feuilles", "ma feuille", "mes feuilles", "f"),
array("Feutre", "le feutre", "les feutres", "mon feutre", "mes feutres", "m"),
array("Fève", "la fève", "les fèves", "ma fève", "mes fèves", "f"),
array("Ficelle", "la ficelle", "les ficelles", "ma ficelle", "mes ficelles", "f"),
array("Fièvre", "la fièvre", "les fièvres", "ma fièvre", "mes fièvres", "f"),
array("Figure", "la figure", "les figures", "ma figure", "mes figures", "f"),
array("Fil", "le fil", "les fils", "mon fil", "mes fils", "m"),
array("Filet", "le filet", "les filets", "mon filet", "mes filets", "m"),
array("Fille", "la fille", "les filles", "ma fille", "mes filles", "f"),
array("Film", "le film", "les films", "mon film", "mes films", "m"),
array("Fils", "le fils", "les fils", "mon fils", "mes fils", "m"),
array("Fin", "la fin", "les fins", "ma fin", "mes fins", "f"),
array("Flamme", "la flamme", "les flammes", "ma flamme", "mes flammes", "f"),
array("Flaque", "la flaque", "les flaques", "ma flaque", "mes flaques", "f"),
array("Flèche", "la flèche", "les flèches", "ma flèche", "mes flèches", "f"),
array("Fleur", "la fleur", "les fleurs", "ma fleur", "mes fleurs", "f"),
array("Fleuriste", "le fleuriste", "les fleuristes", "mon fleuriste", "mes fleuristes", "m"),
array("Flocon", "le flocon", "les flocons", "mon flocon", "mes flocons", "m"),
array("Foin", "le foin", "les foins", "mon foin", "mes foins", "m"),
array("Foire", "la foire", "les foires", "ma foire", "mes foires", "f"),
array("Fois", "la foi", "les fois", "ma foi", "mes fois", "f"),
array("Fond", "le fond", "les fonds", "mon fond", "mes fonds", "m"),
array("Fontaine", "la fontaine", "les fontaines", "ma fontaine", "mes fontaines", "f"),
array("Forêt", "la forêt", "les forêts", "ma forêt", "mes forêts", "f"),
array("Forme", "la forme", "les formes", "ma forme", "mes formes", "f"),
array("Four", "le four", "les fours", "mon four", "mes fours", "m"),
array("Fourchette", "la fourchette", "les fourchettes", "ma fourchette", "mes fourchettes", "f"),
array("Fourmi", "la fourmi", "les fourmis", "ma fourmi", "mes fourmis", "f"),
array("Fraise", "la fraise", "les fraises", "ma fraise", "mes fraises", "f"),
array("Framboise", "la framboise", "les framboises", "ma framboise", "mes framboises", "f"),
array("Frange", "la frange", "les franges", "ma frange", "mes franges", "f"),
array("Frein", "le frein", "les freins", "mon frein", "mes freins", "m"),
array("Frère", "le frère", "les frères", "mon frère", "mes frères", "m"),
array("Frite", "la frite", "les frites", "ma frite", "mes frites", "f"),
array("Fromage", "le fromage", "les fromages", "mon fromage", "mes fromages", "m"),
array("Front", "le front", "les fronts", "mon front", "mes fronts", "m"),
array("Fruit", "le fruit", "les fruits", "mon fruit", "mes fruits", "m"),
array("Fumée", "la fumée", "les fumées", "ma fumée", "mes fumées", "f"),
array("Fusée", "la fusée", "les fusées", "ma fusée", "mes fusées", "f"),
array("Fusil", "le fusil", "les fusils", "mon fusil", "mes fusils", "m"),
array("Galette", "la galette", "les galettes", "ma galette", "mes galettes", "f"),
array("Gant", "le gant", "les gants", "mon gant", "mes gants", "m"),
array("Garage", "le garage", "les garages", "mon garage", "mes garages", "m"),
array("Garçon", "le garçon", "les garçons", "mon garçon", "mes garçons", "m"),
array("Gardien", "le gardien", "les gardiens", "mon gardien", "mes gardiens", "m"),
array("Gare", "la gare", "les gares", "ma gare", "mes gares", "f"),
array("Gâteau", "le gâteau", "les gâteaux", "mon gâteau", "mes gâteaux", "m"),
array("Géant", "le géant", "les géants", "mon géant", "mes géants", "m"),
array("Genou", "le genou", "les genoux", "mon genou", "mes genoux", "m"),
array("Girafe", "la girafe", "les girafes", "ma girafe", "mes girafes", "f"),
array("Glace", "la glace", "les glaces", "ma glace", "mes glaces", "f"),
array("Glaçon", "le glaçon", "les glaçons", "mon glaçon", "mes glaçons", "m"),
array("Gobelet", "le gobelet", "les gobelets", "mon gobelet", "mes gobelets", "m"),
array("Gomme", "la gomme", "les gommes", "ma gomme", "mes gommes", "f"),
array("Gorge", "la gorge", "les gorges", "ma gorge", "mes gorges", "f"),
array("Gourde", "la gourde", "les gourdes", "ma gourde", "mes gourdes", "f"),
array("Goût", "le goût", "les goûts", "mon goût", "mes goûts", "m"),
array("Goutte", "la goutte", "les gouttes", "ma goutte", "mes gouttes", "f"),
array("Grain", "le grain", "les grains", "mon grain", "mes grains", "m"),
array("Graine", "la graine", "les graines", "ma graine", "mes graines", "f"),
array("Grand-mère", "la grand-mère", "les grand-mères", "ma grand-mère", "mes grand-mères", "f"),
array("Grand-parent", "le grand-parent", "les grand-parents", "mon grand-parent", "mes grand-parents", "m"),
array("Grand-père", "le grand-père", "les grand-pères", "mon grand-père", "mes grand-pères", "m"),
array("Grenouille", "la grenouille", "les grenouilles", "ma grenouille", "mes grenouilles", "f"),
array("Griffe", "la griffe", "les griffes", "ma griffe", "mes griffes", "f"),
array("Grimace", "la grimace", "les grimaces", "ma grimace", "mes grimaces", "f"),
array("Grotte", "la grotte", "les grottes", "ma grotte", "mes grottes", "f"),
array("Grue", "la grue", "les grues", "ma grue", "mes grues", "f"),
array("Guêpe", "la guêpe", "les guêpes", "ma guêpe", "mes guêpes", "f"),
array("Guirlande", "la guirlande", "les guirlandes", "ma guirlande", "mes guirlandes", "f"),
array("Gymnastique", "la gymnastique", "les gymnastiques", "ma gymnastique", "mes gymnastiques", "f"),
array("Habit", "l'habit", "les habits", "mon habit", "mes habits", "m"),
array("Hamster", "le hamster", "les hamsters", "mon hamster", "mes hamsters", "m"),
array("Hanche", "la hanche", "les hanches", "ma hanche", "mes hanches", "f"),
array("Haricot", "le haricot", "les haricots", "mon haricot", "mes haricots", "m"),
array("Hélicoptère", "l'hélicoptère", "les hélicoptères", "mon hélicoptère", "mes hélicoptères", "m"),
array("Herbe", "l'herbe", "les herbes", "mon herbe", "mes herbes", "f"),
array("Hérisson", "le hérisson", "les hérissons", "mon hérisson", "mes hérissons", "m"),
array("Heure", "l'heure", "les heures", "mon heure", "mes heures", "f"),
array("Hibou", "le hibou", "les hiboux", "mon hibou", "mes hiboux", "m"),
array("Hippopotame", "l'hippopotame", "les hippopotames", "mon hippopotame", "mes hippopotames", "m"),
array("Hirondelle", "l'hirondelle", "les hirondelles", "mon hirondelle", "mes hirondelles", "f"),
array("Histoire", "l'histoire", "les histoires", "mon histoire", "mes histoires", "f"),
array("Hiver", "l'hiver", "les hivers", "mon hiver", "mes hivers", "m"),
array("Homme", "l'homme", "les hommes", "mon homme", "mes hommes", "m"),
array("Hôpital", "l'hôpital", "les hôpitaux", "mon hôpital", "mes hôpitaux", "m"),
array("Horloge", "l'horloge", "les horloges", "mon horloge", "mes horloges", "f"),
array("Hôtel", "l'hôtel", "les hôtels", "mon hôtel", "mes hôtels", "m"),
array("Huile", "l'huile", "les huiles", "mon huile", "mes huiles", "f"),
array("Humeur", "l'humeur", "les humeurs", "mon humeur", "mes humeurs", "f"),
array("Idée", "l'idée", "les idées", "mon idée", "mes idées", "f"),
array("Île", "l'île", "les îles", "mon île", "mes îles", "f"),
array("Image", "l'image", "les images", "mon image", "mes images", "f"),
array("Immeuble", "l'immeuble", "les immeubles", "mon immeuble", "mes immeubles", "m"),
array("Incendie", "l'incendie", "les incendies", "mon incendie", "mes incendies", "m"),
array("Infirmier", "l'infirmier", "les infirmiers", "mon infirmier", "mes infirmiers", "m"),
array("Infirmière", "l'infirmière", "les infirmières", "mon infirmière", "mes infirmières", "f"),
array("Insecte", "l'insecte", "les insectes", "mon insecte", "mes insectes", "m"),
array("Instrument", "l'instrument", "les instruments", "mon instrument", "mes instruments", "m"),
array("Intérieur", "l'intérieur", "les intérieurs", "mon intérieur", "mes intérieurs", "m"),
array("Intrus", "l'intrus", "les intrus", "mon intrus", "mes intrus", "m"),
array("Invitation", "l'invitation", "les invitations", "mon invitation", "mes invitations", "f"),
array("Jambe", "la jambe", "les jambes", "ma jambe", "mes jambes", "f"),
array("Jambon", "le jambon", "les jambons", "mon jambon", "mes jambons", "m"),
array("Jardin", "le jardin", "les jardins", "mon jardin", "mes jardins", "m"),
array("Jean", "le jean", "les jeans", "mon jean", "mes jeans", "m"),
array("Jeu", "le jeu", "les jeux", "mon jeu", "mes jeux", "m"),
array("Jeudi", "le jeudi", "les jeudis", "mon jeudi", "mes jeudis", "m"),
array("Joie", "la joie", "les joies", "ma joie", "mes joies", "f"),
array("Jonquille", "la jonquille", "les jonquilles", "ma jonquille", "mes jonquilles", "f"),
array("Joue", "la joue", "les joues", "ma joue", "mes joues", "f"),
array("Jouet", "le jouet", "les jouets", "mon jouet", "mes jouets", "m"),
array("Jour", "le jour", "les jours", "mon jour", "mes jours", "m"),
array("Journal", "le journal", "les journaux", "mon journal", "mes journaux", "m"),
array("Journée", "la journée", "les journées", "ma journée", "mes journées", "f"),
array("Jumeau", "le jumeau", "les jumeaux", "mon jumeau", "mes jumeaux", "m"),
array("Jumelle", "la jumelle", "les jumelles", "ma jumelle", "mes jumelles", "f"),
array("Jupe", "la jupe", "les jupes", "ma jupe", "mes jupes", "f"),
array("Jus", "le jus", "les jus", "mon jus", "mes jus", "m"),
array("Kangourou", "le kangourou", "les kangourous", "mon kangourou", "mes kangourous", "m"),
array("Kiwi", "le kiwi", "les kiwis", "mon kiwi", "mes kiwis", "m"),
array("Lac", "le lac", "les lacs", "mon lac", "mes lacs", "m"),
array("Lacet", "le lacet", "les lacets", "mon lacet", "mes lacets", "m"),
array("Laine", "la laine", "les laines", "ma laine", "mes laines", "f"),
array("Laisse", "la laisse", "les laisses", "ma laisse", "mes laisses", "f"),
array("Lait", "le lait", "les laits", "mon lait", "mes laits", "m"),
array("Lame", "la lame", "les lames", "ma lame", "mes lames", "f"),
array("Lampe", "la lampe", "les lampes", "ma lampe", "mes lampes", "f"),
array("Langue", "la langue", "les langues", "ma langue", "mes langues", "f"),
array("Lapin", "le lapin", "les lapins", "mon lapin", "mes lapins", "m"),
array("Larme", "la larme", "les larmes", "ma larme", "mes larmes", "f"),
array("Lavabo", "le lavabo", "les lavabos", "mon lavabo", "mes lavabos", "m"),
array("Lave-linge", "le lave-linge", "les lave-linges", "mon lave-linge", "mes lave-linges", "m"),
array("Lecture", "la lecture", "les lectures", "ma lecture", "mes lectures", "f"),
array("Légume", "le légume", "les légumes", "mon légume", "mes légumes", "m"),
array("Lessive", "la lessive", "les lessives", "ma lessive", "mes lessives", "f"),
array("Lettre", "la lettre", "les lettres", "ma lettre", "mes lettres", "f"),
array("Lèvre", "la lèvre", "les lèvres", "ma lèvre", "mes lèvres", "f"),
array("Lézard", "le lézard", "les lézards", "mon lézard", "mes lézards", "m"),
array("Ligne", "la ligne", "les lignes", "ma ligne", "mes lignes", "f"),
array("Linge", "le linge", "les linges", "mon linge", "mes linges", "m"),
array("Lion", "le lion", "les lions", "mon lion", "mes lions", "m"),
array("Liquide", "le liquide", "les liquides", "mon liquide", "mes liquides", "m"),
array("Liste", "la liste", "les listes", "ma liste", "mes listes", "f"),
array("Lit", "le lit", "les lits", "mon lit", "mes lits", "m"),
array("Litre", "le litre", "les litres", "mon litre", "mes litres", "m"),
array("Livre", "le livre", "les livres", "mon livre", "mes livres", "m"),
array("Louche", "la louche", "les louches", "ma louche", "mes louches", "f"),
array("Loup", "le loup", "les loups", "mon loup", "mes loups", "m"),
array("Loupe", "la loupe", "les loupes", "ma loupe", "mes loupes", "f"),
array("Luge", "la luge", "les luges", "ma luge", "mes luges", "f"),
array("Lumière", "la lumière", "les lumières", "ma lumière", "mes lumières", "f"),
array("Lundi", "le lundi", "les lundis", "mon lundi", "mes lundis", "m"),
array("Lune", "la lune", "les lunes", "ma lune", "mes lunes", "f"),
array("Lunettes", "la lunettes", "les lunettes", "ma lunettes", "mes lunettes", "f"),
array("Lutin", "le lutin", "les lutins", "mon lutin", "mes lutins", "m"),
array("Machine", "la machine", "les machines", "ma machine", "mes machines", "f"),
array("Madame", "la madame", "les madames", "ma madame", "mes madames", "f"),
array("Magasin", "le magasin", "les magasins", "mon magasin", "mes magasins", "m"),
array("Magazine", "le magazine", "les magazines", "mon magazine", "mes magazines", "m"),
array("Magicien", "le magicien", "les magiciens", "mon magicien", "mes magiciens", "m"),
array("Magie", "la magie", "les magies", "ma magie", "mes magies", "f"),
array("Magnétoscope", "le magnétoscope", "les magnétoscopes", "mon magnétoscope", "mes magnétoscopes", "m"),
array("Maillot", "le maillot", "les maillots", "mon maillot", "mes maillots", "m"),
array("Main", "la main", "les mains", "ma main", "mes mains", "f"),
array("Maison", "la maison", "les maisons", "ma maison", "mes maisons", "f"),
array("Maître", "le maître", "les maîtres", "mon maître", "mes maîtres", "m"),
array("Maîtresse", "la maîtresse", "les maîtresses", "ma maîtresse", "mes maîtresses", "f"),
array("Maman", "la maman", "les mamans", "ma maman", "mes mamans", "f"),
array("Manche", "le manche", "les manches", "mon manche", "mes manches", "m"),
array("Manège", "le manège", "les manèges", "mon manège", "mes manèges", "m"),
array("Manteau", "le manteau", "les manteaux", "mon manteau", "mes manteaux", "m"),
array("Maquillage", "le maquillage", "les maquillages", "mon maquillage", "mes maquillages", "m"),
array("Marchand", "le marchand", "les marchands", "mon marchand", "mes marchands", "m"),
array("Marche", "la marche", "les marches", "ma marche", "mes marches", "f"),
array("Mardi", "le mardi", "les mardis", "mon mardi", "mes mardis", "m"),
array("Mare", "la mare", "les mares", "ma mare", "mes mares", "f"),
array("Marguerite", "la marguerite", "les marguerites", "ma marguerite", "mes marguerites", "f"),
array("Mari", "le mari", "les maris", "mon mari", "mes maris", "m"),
array("Mariage", "le mariage", "les mariages", "mon mariage", "mes mariages", "m"),
array("Marin", "le marin", "les marins", "mon marin", "mes marins", "m"),
array("Marionnette", "la marionnette", "les marionnettes", "ma marionnette", "mes marionnettes", "f"),
array("Marron", "le marron", "les marrons", "mon marron", "mes marrons", "m"),
array("Marteau", "le marteau", "les marteaux", "mon marteau", "mes marteaux", "m"),
array("Masque", "le masque", "les masques", "mon masque", "mes masques", "m"),
array("Matelas", "le matelas", "les matelas", "mon matelas", "mes matelas", "m"),
array("Maternelle", "la maternelle", "les maternelles", "ma maternelle", "mes maternelles", "f"),
array("Matin", "le matin", "les matins", "mon matin", "mes matins", "m"),
array("Médecin", "le médecin", "les médecins", "mon médecin", "mes médecins", "m"),
array("Médicament", "le médicament", "les médicaments", "mon médicament", "mes médicaments", "m"),
array("Melon", "le melon", "les melons", "mon melon", "mes melons", "m"),
array("Ménage", "le ménage", "les ménages", "mon ménage", "mes ménages", "m"),
array("Mensonge", "le mensonge", "les mensonges", "mon mensonge", "mes mensonges", "m"),
array("Menton", "le menton", "les mentons", "mon menton", "mes mentons", "m"),
array("Mer", "la mer", "les mers", "ma mer", "mes mers", "f"),
array("Mercredi", "le mercredi", "les mercredis", "mon mercredi", "mes mercredis", "m"),
array("Mère", "la mère", "les mères", "ma mère", "mes mères", "f"),
array("Métal", "le métal", "les métaux", "mon métal", "mes métaux", "m"),
array("Mètre", "le mètre", "les mètres", "mon mètre", "mes mètres", "m"),
array("Meuble", "le meuble", "les meubles", "mon meuble", "mes meubles", "m"),
array("Micro", "le micro", "les micros", "mon micro", "mes micros", "m"),
array("Midi", "le midi", "les midis", "mon midi", "mes midis", "m"),
array("Mie", "la mie", "les mies", "ma mie", "mes mies", "f"),
array("Miel", "le miel", "les miels", "mon miel", "mes miels", "m"),
array("Milieu", "le milieu", "les milieux", "mon milieu", "mes milieux", "m"),
array("Mine", "la mine", "les mines", "ma mine", "mes mines", "f"),
array("Minuit", "le minuit", "les minuits", "mon minuit", "mes minuits", "m"),
array("Minute", "la minute", "les minutes", "ma minute", "mes minutes", "f"),
array("Modèle", "le modèle", "les modèles", "mon modèle", "mes modèles", "m"),
array("Moineau", "le moineau", "les moineaux", "mon moineau", "mes moineaux", "m"),
array("Mois", "le mois", "les mois", "mon mois", "mes mois", "m"),
array("Moitié", "la moitié", "les moitiés", "ma moitié", "mes moitiés", "f"),
array("Moment", "le moment", "les moments", "mon moment", "mes moments", "m"),
array("Monde", "le monde", "les mondes", "mon monde", "mes mondes", "m"),
array("Monnaie", "la monnaie", "les monnaies", "ma monnaie", "mes monnaies", "f"),
array("Monsieur", "le monsieur", "les monsieurs", "mon monsieur", "mes monsieurs", "m"),
array("Montagne", "la montagne", "les montagnes", "ma montagne", "mes montagnes", "f"),
array("Montre", "la montre", "les montres", "ma montre", "mes montres", "f"),
array("Monument", "le monument", "les monuments", "mon monument", "mes monuments", "m"),
array("Morceau", "le morceau", "les morceaux", "mon morceau", "mes morceaux", "m"),
array("Morceau de pain", "le morceau de pain", "les morceaux de pain", "mon morceau de pain", "mes morceaux de pain", "m"),
array("Mot", "le mot", "les mots", "mon mot", "mes mots", "m"),
array("Moteur", "le moteur", "les moteurs", "mon moteur", "mes moteurs", "m"),
array("Moto", "la moto", "les motos", "ma moto", "mes motos", "f"),
array("Mouche", "la mouche", "les mouches", "ma mouche", "mes mouches", "f"),
array("Mouchoir", "le mouchoir", "les mouchoirs", "mon mouchoir", "mes mouchoirs", "m"),
array("Mouette", "la mouette", "les mouettes", "ma mouette", "mes mouettes", "f"),
array("Moufle", "le moufle", "les moufles", "mon moufle", "mes moufles", "m"),
array("Moule", "la moule", "les moules", "ma moule", "mes moules", "f"),
array("Moulin", "le moulin", "les moulins", "mon moulin", "mes moulins", "m"),
array("Mousse", "la mousse", "les mousses", "ma mousse", "mes mousses", "f"),
array("Moustache", "la moustache", "les moustaches", "ma moustache", "mes moustaches", "f"),
array("Moustique", "le moustique", "les moustiques", "mon moustique", "mes moustiques", "m"),
array("Mouton", "le mouton", "les moutons", "mon mouton", "mes moutons", "m"),
array("Muguet", "le muguet", "les muguets", "mon muguet", "mes muguets", "m"),
array("Mur", "le mur", "les murs", "mon mur", "mes murs", "m"),
array("Mur d’escalade", "le mur d’escalade", "les murs d’escalade", "mon mur d’escalade", "mes murs d’escalade", "m"),
array("Mûre", "la mûre", "les mûres", "ma mûre", "mes mûres", "f"),
array("Muscle", "le muscle", "les muscles", "mon muscle", "mes muscles", "m"),
array("Musique", "la musique", "les musiques", "ma musique", "mes musiques", "f"),
array("Nappe", "la nappe", "les nappes", "ma nappe", "mes nappes", "f"),
array("Navet", "le navet", "les navets", "mon navet", "mes navets", "m"),
array("Navire", "le navire", "les navires", "mon navire", "mes navires", "m"),
array("Neige", "la neige", "les neiges", "ma neige", "mes neiges", "f"),
array("Nez", "le nez", "les nez", "mon nez", "mes nez", "m"),
array("Nid", "le nid", "les nids", "mon nid", "mes nids", "m"),
array("Noël", "Noël", "les Noëls", "Noël", "mes Noëls", "m"),
array("Noeud", "le noeud", "les noeuds", "mon noeud", "mes noeuds", "m"),
array("Noisette", "la noisette", "les noisettes", "ma noisette", "mes noisettes", "f"),
array("Noix", "la noix", "les noix", "ma noix", "mes noix", "f"),
array("Nom", "le nom", "les noms", "mon nom", "mes noms", "m"),
array("Nombre", "le nombre", "les nombres", "mon nombre", "mes nombres", "m"),
array("Nourriture", "la nourriture", "les nourritures", "ma nourriture", "mes nourritures", "f"),
array("Noyau", "le noyau", "les noyaux", "mon noyau", "mes noyaux", "m"),
array("Nuage", "le nuage", "les nuages", "mon nuage", "mes nuages", "m"),
array("Nuit", "la nuit", "les nuits", "ma nuit", "mes nuits", "f"),
array("Numéro", "le numéro", "les numéros", "mon numéro", "mes numéros", "m"),
array("Objet", "l'objet", "les objets", "mon objet", "mes objets", "m"),
array("Odeur", "l'odeur", "les odeurs", "mon odeur", "mes odeurs", "f"),
array("Oeil", "l'oeil", "les yeux", "mon oeil", "mes yeux", "m"),
array("Oeuf", "l'oeuf", "les oeufs", "mon oeuf", "mes oeufs", "m"),
array("Ogre", "l'ogre", "les ogres", "mon ogre", "mes ogres", "m"),
array("Oie", "l'oie", "les oies", "mon oie", "mes oies", "f"),
array("Oignon", "l'oignon", "les oignons", "mon oignon", "mes oignons", "m"),
array("Oiseau", "l'oiseau", "les oiseaux", "mon oiseau", "mes oiseaux", "m"),
array("Ombre", "l'ombre", "les ombres", "mon ombre", "mes ombres", "f"),
array("Ongle", "l'ongle", "les ongles", "mon ongle", "mes ongles", "m"),
array("Or", "l'or", "les ors", "mon or", "mes ors", "m"),
array("Orage", "l'orage", "les orages", "mon orage", "mes orages", "m"),
array("Orange", "l'orange", "les oranges", "mon orange", "mes oranges", "f"),
array("Orchestre", "l'orchestre", "les orchestres", "mon orchestre", "mes orchestres", "m"),
array("Ordinateur", "l'ordinateur", "les ordinateurs", "mon ordinateur", "mes ordinateurs", "m"),
array("Ordonnance", "l'ordonnance", "les ordonnances", "mon ordonnance", "mes ordonnances", "f"),
array("Ordre", "l'ordre", "les ordres", "mon ordre", "mes ordres", "m"),
array("Oreille", "l'oreille", "les oreilles", "mon oreille", "mes oreilles", "f"),
array("Oreiller", "l'oreiller", "les oreillers", "mon oreiller", "mes oreillers", "m"),
array("Os", "l'os", "les os", "mon os", "mes os", "m"),
array("Ouragan", "l'ouragan", "les ouragans", "mon ouragan", "mes ouragans", "m"),
array("Ours", "l'ours", "les ours", "mon ours", "mes ours", "m"),
array("Outil", "l'outil", "les outils", "mon outil", "mes outils", "m"),
array("Ouvrier", "l'ouvrier", "les ouvriers", "mon ouvrier", "mes ouvriers", "m"),
array("Page", "la page", "les pages", "ma page", "mes pages", "f"),
array("Paille", "la paille", "les pailles", "ma paille", "mes pailles", "f"),
array("Pain", "le pain", "les pains", "mon pain", "mes pains", "m"),
array("Paire", "la paire", "les paires", "ma paire", "mes paires", "f"),
array("Paix", "la paix", "les guerres", "ma paix", "mes guerres", "f"),
array("Palais", "le palais", "les palais", "mon palais", "mes palais", "m"),
array("Pamplemousse", "le pamplemousse", "les pamplemousses", "mon pamplemousse", "mes pamplemousses", "m"),
array("Panda", "le panda", "les pandas", "mon panda", "mes pandas", "m"),
array("Panier", "le panier", "les paniers", "mon panier", "mes paniers", "m"),
array("Panne", "la panne", "les pannes", "ma panne", "mes pannes", "f"),
array("Panneau", "le panneau", "les panneaux", "mon panneau", "mes panneaux", "m"),
array("Pansement", "le pansement", "les pansements", "mon pansement", "mes pansements", "m"),
array("Pantalon", "le pantalon", "les pantalons", "mon pantalon", "mes pantalons", "m"),
array("Panthère", "la panthère", "les panthères", "ma panthère", "mes panthères", "f"),
array("Papa", "le papa", "les papas", "mon papa", "mes papas", "m"),
array("Papier", "le papier", "les papiers", "mon papier", "mes papiers", "m"),
array("Papillon", "le papillon", "les papillons", "mon papillon", "mes papillons", "m"),
array("Pâquerette", "la pâquerette", "les pâquerettes", "ma pâquerette", "mes pâquerettes", "f"),
array("Paquet", "le paquet", "les paquets", "mon paquet", "mes paquets", "m"),
array("Parapluie", "le parapluie", "les parapluies", "mon parapluie", "mes parapluies", "m"),
array("Parasol", "le parasol", "les parasols", "mon parasol", "mes parasols", "m"),
array("Parc", "le parc", "les parcs", "mon parc", "mes parcs", "m"),
array("Parcours", "le parcours", "les parcours", "mon parcours", "mes parcours", "m"),
array("Pardon", "le pardon", "les pardons", "mon pardon", "mes pardons", "m"),
array("Parent", "le parent", "les parents", "mon parent", "mes parents", "m"),
array("Parfum", "le parfum", "les parfums", "mon parfum", "mes parfums", "m"),
array("Parking", "le parking", "les parkings", "mon parking", "mes parkings", "m"),
array("Part", "la part", "les parts", "ma part", "mes parts", "f"),
array("Partie", "la partie", "les parties", "ma partie", "mes parties", "f"),
array("Pas", "le pas", "les pas", "mon pas", "mes pas", "m"),
array("Passage", "le passage", "les passages", "mon passage", "mes passages", "m"),
array("Passerelle", "la passerelle", "les passerelles", "ma passerelle", "mes passerelles", "f"),
array("Pâte", "la pâte", "les pâtes", "ma pâte", "mes pâtes", "f"),
array("Pâte à modeler", "la pâte à modeler", "les pâtes à modeler", "ma pâte à modeler", "mes pâtes à modeler", "f"),
array("Pâtisserie", "la pâtisserie", "les pâtisseries", "ma pâtisserie", "mes pâtisseries", "f"),
array("Patte", "la patte", "les pattes", "ma patte", "mes pattes", "f"),
array("Pays", "le pays", "les pays", "mon pays", "mes pays", "m"),
array("Paysage", "le paysage", "les paysages", "mon paysage", "mes paysages", "m"),
array("Peau", "la peau", "les peaux", "ma peau", "mes peaux", "f"),
array("Pêche", "la pêche", "les pêches", "ma pêche", "mes pêches", "f"),
array("Pêcheur", "le pêcheur", "les pêcheurs", "mon pêcheur", "mes pêcheurs", "m"),
array("Pédale", "la pédale", "les pédales", "ma pédale", "mes pédales", "f"),
array("Peigne", "le peigne", "les peignes", "mon peigne", "mes peignes", "m"),
array("Peinture", "la peinture", "les peintures", "ma peinture", "mes peintures", "f"),
array("Pelle", "la pelle", "les pelles", "ma pelle", "mes pelles", "f"),
array("Peluche", "la peluche", "les peluches", "ma peluche", "mes peluches", "f"),
array("Pendule", "la pendule", "les pendules", "ma pendule", "mes pendules", "f"),
array("Pente", "la pente", "les pentes", "ma pente", "mes pentes", "f"),
array("Père", "le père", "les pères", "mon père", "mes pères", "m"),
array("Perle", "la perle", "les perles", "ma perle", "mes perles", "f"),
array("Perroquet", "le perroquet", "les perroquets", "mon perroquet", "mes perroquets", "m"),
array("Persil", "le persil", "les persils", "mon persil", "mes persils", "m"),
array("Personne", "la personne", "les personnes", "ma personne", "mes personnes", "f"),
array("Petit pois", "le petit pois", "les petits pois", "mon petit pois", "mes petits pois", "m"),
array("Petite-fille", "la petite-fille", "les petites-filles", "ma petite-fille", "mes petites-filles", "f"),
array("Petit-enfant", "le petit-enfant", "les petits-enfants", "mon petit-enfant", "mes petits-enfants", "m"),
array("Petit-fils", "le petit-fils", "les petits-fils", "mon petit-fils", "mes petits-fils", "m"),
array("Peur", "la peur", "les peurs", "ma peur", "mes peurs", "f"),
array("Pharmacie", "la pharmacie", "les pharmacies", "ma pharmacie", "mes pharmacies", "f"),
array("Pharmacien", "le pharmacien", "les pharmaciens", "mon pharmacien", "mes pharmaciens", "m"),
array("Phoque", "le phoque", "les phoques", "mon phoque", "mes phoques", "m"),
array("Photo", "la photo", "les photos", "ma photo", "mes photos", "f"),
array("Pied", "le pied", "les pieds", "mon pied", "mes pieds", "m"),
array("Pierre", "la pierre", "les pierres", "ma pierre", "mes pierres", "f"),
array("Pigeon", "le pigeon", "les pigeons", "mon pigeon", "mes pigeons", "m"),
array("Pile", "la pile", "les piles", "ma pile", "mes piles", "f"),
array("Pilote", "le pilote", "les pilotes", "mon pilote", "mes pilotes", "m"),
array("Pin", "le pin", "les pins", "mon pin", "mes pins", "m"),
array("Pinceau", "le pinceau", "les pinceaux", "mon pinceau", "mes pinceaux", "m"),
array("Pion", "le pion", "les pions", "mon pion", "mes pions", "m"),
array("Piqûre", "la piqûre", "les piqûres", "ma piqûre", "mes piqûres", "f"),
array("Piscine", "la piscine", "les piscines", "ma piscine", "mes piscines", "f"),
array("Placard", "le placard", "les placards", "mon placard", "mes placards", "m"),
array("Place", "la place", "les places", "ma place", "mes places", "f"),
array("Plafond", "le plafond", "les plafonds", "mon plafond", "mes plafonds", "m"),
array("Plage", "la plage", "les plages", "ma plage", "mes plages", "f"),
array("Planche", "la planche", "les planches", "ma planche", "mes planches", "f"),
array("Plante", "la plante", "les plantes", "ma plante", "mes plantes", "f"),
array("Plat", "le plat", "les plats", "mon plat", "mes plats", "m"),
array("Plateau", "le plateau", "les plateaux", "mon plateau", "mes plateaux", "m"),
array("Plâtre", "le plâtre", "les plâtres", "mon plâtre", "mes plâtres", "m"),
array("Pli", "le pli", "les plis", "mon pli", "mes plis", "m"),
array("Pliage", "le pliage", "les pliages", "mon pliage", "mes pliages", "m"),
array("Plongeoir", "le plongeoir", "les plongeoirs", "mon plongeoir", "mes plongeoirs", "m"),
array("Pluie", "la pluie", "les pluies", "ma pluie", "mes pluies", "f"),
array("Plume", "la plume", "les plumes", "ma plume", "mes plumes", "f"),
array("Pneu", "le pneu", "les pneus", "mon pneu", "mes pneus", "m"),
array("Poche", "la poche", "les poches", "ma poche", "mes poches", "f"),
array("Poêle", "la poêle", "les poêles", "ma poêle", "mes poêles", "f"),
array("Poignet", "le poignet", "les poignets", "mon poignet", "mes poignets", "m"),
array("Poing", "le poing", "les poings", "mon poing", "mes poings", "m"),
array("Point", "le point", "les points", "mon point", "mes points", "m"),
array("Pointe", "la pointe", "les pointes", "ma pointe", "mes pointes", "f"),
array("Poire", "la poire", "les poires", "ma poire", "mes poires", "f"),
array("Poireau", "le poireau", "les poireaux", "mon poireau", "mes poireaux", "m"),
array("Poison", "le poison", "les poisons", "mon poison", "mes poisons", "m"),
array("Poisson", "le poisson", "les poissons", "mon poisson", "mes poissons", "m"),
array("Police", "la police", "les polices", "ma police", "mes polices", "f"),
array("Policier", "le policier", "les policiers", "mon policier", "mes policiers", "m"),
array("Pomme", "la pomme", "les pommes", "ma pomme", "mes pommes", "f"),
array("Pomme de terre", "la pomme de terre", "les pommes de terre", "ma pomme de terre", "mes pommes de terre", "f"),
array("Pompe", "la pompe", "les pompes", "ma pompe", "mes pompes", "f"),
array("Pompier", "le pompier", "les pompiers", "mon pompier", "mes pompiers", "m"),
array("Poney", "le poney", "les poneys", "mon poney", "mes poneys", "m"),
array("Pont", "le pont", "les ponts", "mon pont", "mes ponts", "m"),
array("Port", "le port", "les ports", "mon port", "mes ports", "m"),
array("Porte", "la porte", "les portes", "ma porte", "mes portes", "f"),
array("Portemanteau", "le portemanteau", "les portemanteaux", "mon portemanteau", "mes portemanteaux", "m"),
array("Portière", "la portière", "les portières", "ma portière", "mes portières", "f"),
array("Poste", "la poste", "les postes", "ma poste", "mes postes", "f"),
array("Poster", "le poster", "les posters", "mon poster", "mes posters", "m"),
array("Pot", "le pot", "les pots", "mon pot", "mes pots", "m"),
array("Potage", "le potage", "les potages", "mon potage", "mes potages", "m"),
array("Poubelle", "la poubelle", "les poubelles", "ma poubelle", "mes poubelles", "f"),
array("Pouce", "le pouce", "les pouces", "mon pouce", "mes pouces", "m"),
array("Pouf", "le pouf", "les poufs", "mon pouf", "mes poufs", "m"),
array("Poule", "la poule", "les poules", "ma poule", "mes poules", "f"),
array("Poulet", "le poulet", "les poulets", "mon poulet", "mes poulets", "m"),
array("Poupée", "la poupée", "les poupées", "ma poupée", "mes poupées", "f"),
array("Poussette", "la poussette", "les poussettes", "ma poussette", "mes poussettes", "f"),
array("Poussière", "la poussière", "les poussières", "ma poussière", "mes poussières", "f"),
array("Poussin", "le poussin", "les poussins", "mon poussin", "mes poussins", "m"),
array("Poutre d’équilibre", "la poutre d’équilibre", "les poutres d’équilibre", "ma poutre d’équilibre", "mes poutres d’équilibre", "f"),
array("Prairie", "la prairie", "les prairies", "ma prairie", "mes prairies", "f"),
array("Préau", "le préau", "les préaux", "mon préau", "mes préaux", "m"),
array("Prénom", "le prénom", "les prénoms", "mon prénom", "mes prénoms", "m"),
array("Prince", "le prince", "les princes", "mon prince", "mes princes", "m"),
array("Princesse", "la princesse", "les princesses", "ma princesse", "mes princesses", "f"),
array("Prise", "la prise", "les prises", "ma prise", "mes prises", "f"),
array("Prix", "le prix", "les prix", "mon prix", "mes prix", "m"),
array("Promenade", "la promenade", "les promenades", "ma promenade", "mes promenades", "f"),
array("Prune", "la prune", "les prunes", "ma prune", "mes prunes", "f"),
array("Pull-over", "le pull-over", "les pull-overs", "mon pull-over", "mes pull-overs", "m"),
array("Purée", "la purée", "les purées", "ma purée", "mes purées", "f"),
array("Puzzle", "le puzzle", "les puzzles", "mon puzzle", "mes puzzles", "m"),
array("Pyjama", "le pyjama", "les pyjamas", "mon pyjama", "mes pyjamas", "m"),
array("Quai", "le quai", "les quais", "mon quai", "mes quais", "m"),
array("Quartier", "le quartier", "les quartiers", "mon quartier", "mes quartiers", "m"),
array("Question", "la question", "les questions", "ma question", "mes questions", "f"),
array("Queue", "la queue", "les queues", "ma queue", "mes queues", "f"),
array("Radiateur", "le radiateur", "les radiateurs", "mon radiateur", "mes radiateurs", "m"),
array("Radio", "la radio", "les radios", "ma radio", "mes radios", "f"),
array("Radis", "le radis", "les radis", "mon radis", "mes radis", "m"),
array("Raisin", "le raisin", "les raisins", "mon raisin", "mes raisins", "m"),
array("Rampe", "la rampe", "les rampes", "ma rampe", "mes rampes", "f"),
array("Rangée", "la rangée", "les rangées", "ma rangée", "mes rangées", "f"),
array("Râpe", "la râpe", "les râpes", "ma râpe", "mes râpes", "f"),
array("Raquette", "la raquette", "les raquettes", "ma raquette", "mes raquettes", "f"),
array("Rasoir", "le rasoir", "les rasoirs", "mon rasoir", "mes rasoirs", "m"),
array("Rat", "le rat", "les rats", "mon rat", "mes rats", "m"),
array("Râteau", "le râteau", "les râteaux", "mon râteau", "mes râteaux", "m"),
array("Rayon", "le rayon", "les rayons", "mon rayon", "mes rayons", "m"),
array("Rayure", "la rayure", "les rayures", "ma rayure", "mes rayures", "f"),
array("Recette", "la recette", "les recettes", "ma recette", "mes recettes", "f"),
array("Récréation", "la récréation", "les récréations", "ma récréation", "mes récréations", "f"),
array("Réfrigérateur", "le réfrigérateur", "les réfrigérateurs", "mon réfrigérateur", "mes réfrigérateurs", "m"),
array("Regard", "le regard", "les regards", "mon regard", "mes regards", "m"),
array("Reine", "la reine", "les reines", "ma reine", "mes reines", "f"),
array("Renard", "le renard", "les renards", "mon renard", "mes renards", "m"),
array("Rentrée", "la rentrée", "les rentrées", "ma rentrée", "mes rentrées", "f"),
array("Repas", "le repas", "les repas", "mon repas", "mes repas", "m"),
array("Requin", "le requin", "les requins", "mon requin", "mes requins", "m"),
array("Restaurant", "le restaurant", "les restaurants", "mon restaurant", "mes restaurants", "m"),
array("Retard", "le retard", "les retards", "mon retard", "mes retards", "m"),
array("Retour", "le retour", "les retours", "mon retour", "mes retours", "m"),
array("Réveil", "le réveil", "les réveils", "mon réveil", "mes réveils", "m"),
array("Rhinocéros", "le rhinocéros", "les rhinocéros", "mon rhinocéros", "mes rhinocéros", "m"),
array("Rideau", "le rideau", "les rideaux", "mon rideau", "mes rideaux", "m"),
array("Rivière", "la rivière", "les rivières", "ma rivière", "mes rivières", "f"),
array("Riz", "le riz", "les riz", "mon riz", "mes riz", "m"),
array("Robe", "la robe", "les robes", "ma robe", "mes robes", "f"),
array("Robinet", "le robinet", "les robinets", "mon robinet", "mes robinets", "m"),
array("Rocher", "le rocher", "les rochers", "mon rocher", "mes rochers", "m"),
array("Roi", "le roi", "les rois", "mon roi", "mes rois", "m"),
array("Rond", "le rond", "les ronds", "mon rond", "mes ronds", "m"),
array("Rondelle", "la rondelle", "les rondelles", "ma rondelle", "mes rondelles", "f"),
array("Rosé", "le rosé", "les rosés", "mon rosé", "mes rosés", "m"),
array("Roue", "la roue", "les roues", "ma roue", "mes roues", "f"),
array("Roulade", "la roulade", "les roulades", "ma roulade", "mes roulades", "f"),
array("Rouleau", "le rouleau", "les rouleaux", "mon rouleau", "mes rouleaux", "m"),
array("Route", "la route", "les routes", "ma route", "mes routes", "f"),
array("Ruban", "le ruban", "les rubans", "mon ruban", "mes rubans", "m"),
array("Rue", "la rue", "les rues", "ma rue", "mes rues", "f"),
array("Sable", "le sable", "les sables", "mon sable", "mes sables", "m"),
array("Sac", "le sac", "les sacs", "mon sac", "mes sacs", "m"),
array("Sac en plastique", "le sac en plastique", "les sacs en plastique", "mon sac en plastique", "mes sacs en plastique", "m"),
array("Saison", "la saison", "les saisons", "ma saison", "mes saisons", "f"),
array("Salade", "la salade", "les salades", "ma salade", "mes salades", "f"),
array("Saladier", "le saladier", "les saladiers", "mon saladier", "mes saladiers", "m"),
array("Salle", "la salle", "les salles", "ma salle", "mes salles", "f"),
array("Samedi", "le samedi", "les samedis", "mon samedi", "mes samedis", "m"),
array("Sang", "le sang", "les sangs", "mon sang", "mes sangs", "m"),
array("Santé", "la santé", "les santés", "ma santé", "mes santés", "f"),
array("Sapin", "le sapin", "les sapins", "mon sapin", "mes sapins", "m"),
array("Sardine", "la sardine", "les sardines", "ma sardine", "mes sardines", "f"),
array("Saut", "le saut", "les sauts", "mon saut", "mes sauts", "m"),
array("Savon", "le savon", "les savons", "mon savon", "mes savons", "m"),
array("Scie", "la scie", "les scies", "ma scie", "mes scies", "f"),
array("Seau", "le seau", "les seaux", "mon seau", "mes seaux", "m"),
array("Sel", "le sel", "les sels", "mon sel", "mes sels", "m"),
array("Semaine", "la semaine", "les semaines", "ma semaine", "mes semaines", "f"),
array("Semelle", "la semelle", "les semelles", "ma semelle", "mes semelles", "f"),
array("Sens", "le sens", "les sens", "mon sens", "mes sens", "m"),
array("Serpent", "le serpent", "les serpents", "mon serpent", "mes serpents", "m"),
array("Serrure", "la serrure", "les serrures", "ma serrure", "mes serrures", "f"),
array("Serviette", "la serviette", "les serviettes", "ma serviette", "mes serviettes", "f"),
array("Shampoing", "le shampoing", "les shampoings", "mon shampoing", "mes shampoings", "m"),
array("Siège", "le siège", "les sièges", "mon siège", "mes sièges", "m"),
array("Sieste", "la sieste", "les siestes", "ma sieste", "mes siestes", "f"),
array("Sifflet", "le sifflet", "les sifflets", "mon sifflet", "mes sifflets", "m"),
array("Signe", "le signe", "les signes", "mon signe", "mes signes", "m"),
array("Silence", "le silence", "les silences", "mon silence", "mes silences", "m"),
array("Singe", "le singe", "les singes", "mon singe", "mes singes", "m"),
array("Ski", "le ski", "les skis", "mon ski", "mes skis", "m"),
array("Soeur", "la soeur", "les soeurs", "ma soeur", "mes soeurs", "f"),
array("Soif", "la soif", "les soifs", "ma soif", "mes soifs", "f"),
array("Soir", "le soir", "les soirs", "mon soir", "mes soirs", "m"),
array("Sol", "le sol", "les sols", "mon sol", "mes sols", "m"),
array("Soldat", "le soldat", "les soldats", "mon soldat", "mes soldats", "m"),
array("Sole", "la sole", "les soles", "ma sole", "mes soles", "f"),
array("Soleil", "le soleil", "les soleils", "mon soleil", "mes soleils", "m"),
array("Sommeil", "le sommeil", "les sommeils", "mon sommeil", "mes sommeils", "m"),
array("Sommet", "le sommet", "les sommets", "mon sommet", "mes sommets", "m"),
array("Sonnette", "la sonnette", "les sonnettes", "ma sonnette", "mes sonnettes", "f"),
array("Sorcière", "la sorcière", "les sorcières", "ma sorcière", "mes sorcières", "f"),
array("Sortie", "la sortie", "les sorties", "ma sortie", "mes sorties", "f"),
array("Soupe", "la soupe", "les soupes", "ma soupe", "mes soupes", "f"),
array("Sourcil", "le sourcil", "les sourcils", "mon sourcil", "mes sourcils", "m"),
array("Sourire", "le sourire", "les sourires", "mon sourire", "mes sourires", "m"),
array("Souris", "la souris", "les souris", "ma souris", "mes souris", "f"),
array("Spectacle", "le spectacle", "les spectacles", "mon spectacle", "mes spectacles", "m"),
array("Sport", "le sport", "les sports", "mon sport", "mes sports", "m"),
array("Square", "le square", "les squares", "mon square", "mes squares", "m"),
array("Squelette", "le squelette", "les squelettes", "mon squelette", "mes squelettes", "m"),
array("Stylo", "le stylo", "les stylos", "mon stylo", "mes stylos", "m"),
array("Sucre", "le sucre", "les sucres", "mon sucre", "mes sucres", "m"),
array("Suivant", "le suivant", "les suivants", "mon suivant", "mes suivants", "m"),
array("Surprise", "la surprise", "les surprises", "ma surprise", "mes surprises", "f"),
array("Table", "la table", "les tables", "ma table", "mes tables", "f"),
array("Tableau", "le tableau", "les tableaux", "mon tableau", "mes tableaux", "m"),
array("Tablier", "le tablier", "les tabliers", "mon tablier", "mes tabliers", "m"),
array("Tabouret", "le tabouret", "les tabourets", "mon tabouret", "mes tabourets", "m"),
array("Tache", "la tache", "les taches", "ma tache", "mes taches", "f"),
array("Taille", "la taille", "les tailles", "ma taille", "mes tailles", "f"),
array("Taille-crayon", "le taille-crayon", "les taille-crayons", "mon taille-crayon", "mes taille-crayons", "m"),
array("Talon", "le talon", "les talons", "mon talon", "mes talons", "m"),
array("Tambour", "le tambour", "les tambours", "mon tambour", "mes tambours", "m"),
array("Tampon", "le tampon", "les tampons", "mon tampon", "mes tampons", "m"),
array("Tapis", "le tapis", "les tapis", "mon tapis", "mes tapis", "m"),
array("Tarte", "la tarte", "les tartes", "ma tarte", "mes tartes", "f"),
array("Tartine", "la tartine", "les tartines", "ma tartine", "mes tartines", "f"),
array("Tas", "le tas", "les tas", "mon tas", "mes tas", "m"),
array("Tasse", "la tasse", "les tasses", "ma tasse", "mes tasses", "f"),
array("Taupe", "la taupe", "les taupes", "ma taupe", "mes taupes", "f"),
array("Télécommande", "la télécommande", "les télécommandes", "ma télécommande", "mes télécommandes", "f"),
array("Téléphone", "le téléphone", "les téléphones", "mon téléphone", "mes téléphones", "m"),
array("Télévision", "la télévision", "les télévisions", "ma télévision", "mes télévisions", "f"),
array("Tempête", "la tempête", "les tempêtes", "ma tempête", "mes tempêtes", "f"),
array("Temps", "le temps", "les temps", "mon temps", "mes temps", "m"),
array("Tente", "la tente", "les tentes", "ma tente", "mes tentes", "f"),
array("Terrain", "le terrain", "les terrains", "mon terrain", "mes terrains", "m"),
array("Terre", "la terre", "les terres", "ma terre", "mes terres", "f"),
array("Terrier", "le terrier", "les terriers", "mon terrier", "mes terriers", "m"),
array("Tête", "la tête", "les têtes", "ma tête", "mes têtes", "f"),
array("Thé", "le thé", "les thés", "mon thé", "mes thés", "m"),
array("Thermomètre", "le thermomètre", "les thermomètres", "mon thermomètre", "mes thermomètres", "m"),
array("Ticket", "le ticket", "les tickets", "mon ticket", "mes tickets", "m"),
array("Tige", "la tige", "les tiges", "ma tige", "mes tiges", "f"),
array("Tigre", "le tigre", "les tigres", "mon tigre", "mes tigres", "m"),
array("Timbre", "le timbre", "les timbres", "mon timbre", "mes timbres", "m"),
array("Tiroir", "le tiroir", "les tiroirs", "mon tiroir", "mes tiroirs", "m"),
array("Tissu", "le tissu", "les tissus", "mon tissu", "mes tissus", "m"),
array("Titre", "le titre", "les titres", "mon titre", "mes titres", "m"),
array("Toboggan", "le toboggan", "les toboggans", "mon toboggan", "mes toboggans", "m"),
array("Toilette", "la toilette", "les toilettes", "ma toilette", "mes toilettes", "f"),
array("Toit", "le toit", "les toits", "mon toit", "mes toits", "m"),
array("Tomate", "la tomate", "les tomates", "ma tomate", "mes tomates", "f"),
array("Tonnerre", "le tonnerre", "les tonnerres", "mon tonnerre", "mes tonnerres", "m"),
array("Torchon", "le torchon", "les torchons", "mon torchon", "mes torchons", "m"),
array("Tortue", "la tortue", "les tortues", "ma tortue", "mes tortues", "f"),
array("Tour", "la tour", "les tours", "ma tour", "mes tours", "f"),
array("Tournevis", "le tournevis", "les tournevis", "mon tournevis", "mes tournevis", "m"),
array("Tracteur", "le tracteur", "les tracteurs", "mon tracteur", "mes tracteurs", "m"),
array("Train", "le train", "les trains", "mon train", "mes trains", "m"),
array("Traîneau", "le traîneau", "les traîneaux", "mon traîneau", "mes traîneaux", "m"),
array("Trait", "le trait", "les traits", "mon trait", "mes traits", "m"),
array("Trampoline", "le trampoline", "les trampolines", "mon trampoline", "mes trampolines", "m"),
array("Tranche", "la tranche", "les tranches", "ma tranche", "mes tranches", "f"),
array("Travail", "le travail", "les travaux", "mon travail", "mes travaux", "m"),
array("Trésor", "le trésor", "les trésors", "mon trésor", "mes trésors", "m"),
array("Tricot", "le tricot", "les tricots", "mon tricot", "mes tricots", "m"),
array("Tricycle", "le tricycle", "les tricycles", "mon tricycle", "mes tricycles", "m"),
array("Trompette", "la trompette", "les trompettes", "ma trompette", "mes trompettes", "f"),
array("Trottoir", "le trottoir", "les trottoirs", "mon trottoir", "mes trottoirs", "m"),
array("Trou", "le trou", "les trous", "mon trou", "mes trous", "m"),
array("Trousse", "la trousse", "les trousses", "ma trousse", "mes trousses", "f"),
array("Tube", "le tube", "les tubes", "mon tube", "mes tubes", "m"),
array("Tulipe", "la tulipe", "les tulipes", "ma tulipe", "mes tulipes", "f"),
array("Tunnel", "le tunnel", "les tunnels", "mon tunnel", "mes tunnels", "m"),
array("Tuyau", "le tuyau", "les tuyaux", "mon tuyau", "mes tuyaux", "m"),
array("Uniforme", "l'uniforme", "les uniformes", "mon uniforme", "mes uniformes", "m"),
array("Univers", "l'univers", "les univers", "mon univers", "mes univers", "m"),
array("Usine", "l'usine", "les usines", "mon usine", "mes usines", "f"),
array("Vache", "la vache", "les vaches", "ma vache", "mes vaches", "f"),
array("Vague", "la vague", "les vagues", "ma vague", "mes vagues", "f"),
array("Vaisselle", "la vaisselle", "les vaisselles", "ma vaisselle", "mes vaisselles", "f"),
array("Valise", "la valise", "les valises", "ma valise", "mes valises", "f"),
array("Vase", "le vase", "les vases", "mon vase", "mes vases", "m"),
array("Véhicule", "le véhicule", "les véhicules", "mon véhicule", "mes véhicules", "m"),
array("Vélo", "le vélo", "les vélos", "mon vélo", "mes vélos", "m"),
array("Vendredi", "le vendredi", "les vendredis", "mon vendredi", "mes vendredis", "m"),
array("Vent", "le vent", "les vents", "mon vent", "mes vents", "m"),
array("Ventre", "le ventre", "les ventres", "mon ventre", "mes ventres", "m"),
array("Ver", "le ver", "les vers", "mon ver", "mes vers", "m"),
array("Verre", "le verre", "les verres", "mon verre", "mes verres", "m"),
array("Veste", "la veste", "les vestes", "ma veste", "mes vestes", "f"),
array("Vêtement", "le vêtement", "les vêtements", "mon vêtement", "mes vêtements", "m"),
array("Vétérinaire", "le vétérinaire", "les vétérinaires", "mon vétérinaire", "mes vétérinaires", "m"),
array("Viande", "la viande", "les viandes", "ma viande", "mes viandes", "f"),
array("Village", "le village", "les villages", "mon village", "mes villages", "m"),
array("Ville", "la ville", "les villes", "ma ville", "mes villes", "f"),
array("Vin", "le vin", "les vins", "mon vin", "mes vins", "m"),
array("Virage", "le virage", "les virages", "mon virage", "mes virages", "m"),
array("Vis", "la vis", "les vis", "ma vis", "mes vis", "f"),
array("Visage", "le visage", "les visages", "mon visage", "mes visages", "m"),
array("Vitesse", "la vitesse", "les vitesses", "ma vitesse", "mes vitesses", "f"),
array("Vitre", "la vitre", "les vitres", "ma vitre", "mes vitres", "f"),
array("Voile", "le voile", "les voiles", "mon voile", "mes voiles", "m"),
array("Voisin", "le voisin", "les voisins", "mon voisin", "mes voisins", "m"),
array("Voiture", "la voiture", "les voitures", "ma voiture", "mes voitures", "f"),
array("Voix", "la voix", "les voix", "ma voix", "mes voix", "f"),
array("Volet", "le volet", "les volets", "mon volet", "mes volets", "m"),
array("Voyage", "le voyage", "les voyages", "mon voyage", "mes voyages", "m"),
array("Wagon", "le wagon", "les wagons", "mon wagon", "mes wagons", "m"),
array("WC", "le WC", "les WCs", "mon WC", "mes WCs", "m"),
array("Xylophone", "le xylophone", "les xylophones", "mon xylophone", "mes xylophones", "m"),
array("Yaourt", "le yaourt", "les yaourts", "mon yaourt", "mes yaourts", "m"),
array("Zèbre", "le zèbre", "les zèbres", "mon zèbre", "mes zèbres", "m"),
array("Zéro", "le zéro", "les zéros", "mon zéro", "mes zéros", "m"),
array("Zigzag", "le zigzag", "les zigzags", "mon zigzag", "mes zigzags", "m"),
array("Zoo", "le zoo", "les zoos", "mon zoo", "mes zoos", "m"),  
);

public function genererEluard($strophes = 1, $retourChariot = "\n", $retourFinal = false)
{

$text = "";

for ($s = 0; $s < $strophes; $s++)
{
for ($i = 0; $i < 3; $i++)
{
  $phraseType = rand(0, 2);
	  
  switch ($phraseType)
  {
    case 0:
		$text = $text."Sur " . $this->genererMorceauEluard(false, "lm", $this->noms, $this->adjectifs) . ", sur " . $this->genererMorceauEluard(false, "lm", $this->noms, $this->adjectifs);
		break;
	case 1:
		$text = $text."Sur " . $this->genererMorceauEluard(false, "l", $this->noms, $this->adjectifs) . " de " . $this->genererMorceauEluard(false, "m", $this->noms, $this->adjectifs);
		break;
	case 2:
		$text = $text."Sur " . $this->genererMorceauEluard(true, "lm", $this->noms, $this->adjectifs);
		break;
  }

  $text .= $retourChariot;
}
  $text .= $retourChariot;
}

$text .= "J'écris ton nom".$retourChariot;
$text .= $this->noms[$this->getRandomArrayIndex($this->noms)][0];

 return $text;
}

private function genererMorceauEluard($avecAdjectif, $detType, $noms, $adjectifs)
{
	$pluriel = (mt_rand(0, 1) == 0);
	$nomID = $this->getRandomArrayIndex($noms);
	$nomGN = 1;
	if ($pluriel) $nomGN = 2;

	$possessif = (mt_rand(0, 1) == 0);
	if ($detType == "m") $possessif = true;
	else if ($detType == "l") $possessif = false;
	
	if ($possessif) $nomGN += 2;
	
	$morceau = $noms[$nomID][$nomGN];

	if ($avecAdjectif)
	{
		$adjID = $this->getRandomArrayIndex($adjectifs);
		$adjGN = 0;
		if ($noms[$nomID][5] == "f") $adjGN = 1;
		if ($pluriel) $adjGN += 2;
		
		$morceau = $morceau . " " . $adjectifs[$adjID][$adjGN];
	}

	return $morceau;
}

private function getRandomArrayIndex($arr) { return mt_rand(0, count($arr) - 1); }

}
