<?php

class AutoNiemoller
{

private $noms = array
(
array( "Abeille", "l'abeille", "les abeilles", "une abeille", "mes abeilles", "f" ),
array( "Abricot", "l'abricot", "les abricots", "un abricot", "mes abricots", "m" ),
array( "Accident", "l'accident", "les accidents", "un accident", "mes accidents", "m" ),
array( "Acrobate", "l'acrobate", "les acrobates", "un acrobate", "mes acrobates", "m" ),
array( "Adresse", "l'adresse", "les adresses", "une adresse", "mes adresses", "f" ),
array( "Adulte", "l'adulte", "les adultes", "un adulte", "mes adultes", "m" ),
array( "Aéroport", "l'aéroport", "les aéroports", "un aéroport", "mes aéroports", "m" ),
array( "Affaire", "l'affaire", "les affaires", "une affaire", "mes affaires", "f" ),
array( "Affiche", "l'affiche", "les affiches", "une affiche", "mes affiches", "f" ),
array( "Âge", "l'âge", "les âges", "un âge", "mes âges", "m" ),
array( "Agneau", "l'agneau", "les agneaux", "un agneau", "mes agneaux", "m" ),
array( "Aigle", "l'aigle", "les aigles", "un aigle", "mes aigles", "m" ),
array( "Aiguille", "l'aiguille", "les aiguilles", "une aiguille", "mes aiguilles", "f" ),
array( "Aile", "l'aile", "les ailes", "une aile", "mes ailes", "f" ),
array( "Air", "l'air", "les airs", "un air", "mes airs", "m" ),
array( "Album", "l'album", "les albums", "un album", "mes albums", "m" ),
array( "Aliment", "l'aliment", "les aliments", "un aliment", "mes aliments", "m" ),
array( "Allumette", "l'allumette", "les allumettes", "une allumette", "mes allumettes", "f" ),
array( "Alphabet", "l'alphabet", "les alphabets", "un alphabet", "mes alphabets", "m" ),
array( "Ambulance", "l'ambulance", "les ambulances", "une ambulance", "mes ambulances", "f" ),
array( "Ami", "l'ami", "les amis", "un ami", "mes amis", "m" ),
array( "Amour", "l'amour", "les amours", "un amour", "mes amours", "m" ),
array( "Ampoule", "l'ampoule", "les ampoules", "une ampoule", "mes ampoules", "f" ),
array( "Année", "l'année", "les années", "une année", "mes années", "f" ),
array( "Ananas", "l'ananas", "les ananas", "un ananas", "mes ananas", "m" ),
array( "Âne", "l'âne", "les ânes", "un âne", "mes ânes", "m" ),
array( "Angle", "l'angle", "les angles", "un angle", "mes angles", "m" ),
array( "Animal", "l'animal", "les animaux", "un animal", "mes animaux", "m" ),
array( "Année", "l'année", "les années", "une année", "mes années", "f" ),
array( "Anniversaire", "l'anniversaire", "les anniversaires", "un anniversaire", "mes anniversaires", "m" ),
array( "Anorak", "l'anorak", "les anoraks", "un anorak", "mes anoraks", "m" ),
array( "Appareil", "l'appareil", "les appareils", "un appareil", "mes appareils", "m" ),
array( "Appartement", "l'appartement", "les appartements", "un appartement", "mes appartements", "m" ),
array( "Appétit", "l'appétit", "les appétits", "un appétit", "mes appétits", "m" ),
array( "Après-midi", "l'après-midi", "les après-midis", "un après-midi", "mes après-midis", "m" ),
array( "Aquarium", "l'aquarium", "les aquariums", "un aquarium", "mes aquariums", "m" ),
array( "Araignée", "l'araignée", "les araignées", "une araignée", "mes araignées", "f" ),
array( "Arbre", "l'arbre", "les arbres", "un arbre", "mes arbres", "m" ),
array( "Arc", "l'arc", "les arcs", "un arc", "mes arcs", "m" ),
array( "Arc-en-ciel", "l'arc-en-ciel", "les arcs-en-ciel", "un arc-en-ciel", "mes arcs-en-ciel", "m" ),
array( "Arête", "l'arête", "les arêtes", "une arête", "mes arêtes", "f" ),
array( "Argent", "l'argent", "les argents", "un argent", "mes argents", "m" ),
array( "Armoire", "l'armoire", "les armoires", "une armoire", "mes armoires", "f" ),
array( "Arrêt", "l'arrêt", "les arrêts", "un arrêt", "mes arrêts", "m" ),
array( "Arrière", "l'arrière", "les arrières", "un arrière", "mes arrières", "m" ),
array( "Arrosoir", "l'arrosoir", "les arrosoirs", "un arrosoir", "mes arrosoirs", "m" ),
array( "Ascenseur", "l'ascenseur", "les ascenseurs", "un ascenseur", "mes ascenseurs", "m" ),
array( "Aspirateur", "l'aspirateur", "les aspirateurs", "un aspirateur", "mes aspirateurs", "m" ),
array( "Assiette", "l'assiette", "les assiettes", "une assiette", "mes assiettes", "f" ),
array( "Auto", "l'auto", "les autos", "une auto", "mes autos", "f" ),
array( "Avion", "l'avion", "les avions", "un avion", "mes avions", "m" ),
array( "Bagage", "le bagage", "les bagages", "un bagage", "mes bagages", "m" ),
array( "Bagarre", "la bagarre", "les bagarres", "une bagarre", "mes bagarres", "f" ),
array( "Bague", "la bague", "les bagues", "une bague", "mes bagues", "f" ),
array( "Baguette", "la baguette", "les baguettes", "une baguette", "mes baguettes", "f" ),
array( "Bain", "le bain", "les bains", "un bain", "mes bains", "m" ),
array( "Baiser", "le baiser", "les baisers", "un baiser", "mes baisers", "m" ),
array( "Balai", "le balai", "les balais", "un balai", "mes balais", "m" ),
array( "Balançoire", "la balançoire", "les balançoires", "une balançoire", "mes balançoires", "f" ),
array( "Balcon", "le balcon", "les balcons", "un balcon", "mes balcons", "m" ),
array( "Baleine", "la baleine", "les baleines", "une baleine", "mes baleines", "f" ),
array( "Balle", "la balle", "les balles", "une balle", "mes balles", "f" ),
array( "Ballon", "le ballon", "les ballons", "un ballon", "mes ballons", "m" ),
array( "Banane", "la banane", "les bananes", "une banane", "mes bananes", "f" ),
array( "Banc", "le banc", "les bancs", "un banc", "mes bancs", "m" ),
array( "Bande", "la bande", "les bandes", "une bande", "mes bandes", "f" ),
array( "Bande dessinée", "la bande dessinée", "les bandes dessinées", "une bande dessinée", "mes bandes dessinées", "f" ),
array( "Barbe", "la barbe", "les barbes", "une barbe", "mes barbes", "f" ),
array( "Barque", "la barque", "les barques", "une barque", "mes barques", "f" ),
array( "Barre", "la barre", "les barres", "une barre", "mes barres", "f" ),
array( "Barreau", "le barreau", "les barreaux", "un barreau", "mes barreaux", "m" ),
array( "Barrette", "la barrette", "les barrettes", "une barrette", "mes barrettes", "f" ),
array( "Bassin", "le bassin", "les bassins", "un bassin", "mes bassins", "m" ),
array( "Bassine", "la bassine", "les bassines", "une bassine", "mes bassines", "f" ),
array( "Bateau", "le bateau", "les bateaux", "un bateau", "mes bateaux", "m" ),
array( "Bâton", "le bâton", "les bâtons", "un bâton", "mes bâtons", "m" ),
array( "Bavoir", "le bavoir", "les bavoirs", "un bavoir", "mes bavoirs", "m" ),
array( "Bébé", "le bébé", "les bébés", "un bébé", "mes bébés", "m" ),
array( "Bec", "le bec", "les becs", "un bec", "mes becs", "m" ),
array( "Bête", "la bête", "les bêtes", "une bête", "mes bêtes", "f" ),
array( "Bêtise", "la bêtise", "les bêtises", "une bêtise", "mes bêtises", "f" ),
array( "Biberon", "le biberon", "les biberons", "un biberon", "mes biberons", "m" ),
array( "Bibliothèque", "la bibliothèque", "les bibliothèques", "une bibliothèque", "mes bibliothèques", "f" ),
array( "Bicyclette", "la bicyclette", "les bicyclettes", "une bicyclette", "mes bicyclettes", "f" ),
array( "Bifteck", "le bifteck", "les biftecks", "un bifteck", "mes biftecks", "m" ),
array( "Bijou", "le bijou", "les bijoux", "un bijou", "mes bijoux", "m" ),
array( "Bille", "la bille", "les billes", "une bille", "mes billes", "f" ),
array( "Billet", "le billet", "les billets", "un billet", "mes billets", "m" ),
array( "Biscuit", "le biscuit", "les biscuits", "un biscuit", "mes biscuits", "m" ),
array( "Bisou", "le bisou", "les bisous", "un bisou", "mes bisous", "m" ),
array( "Boeuf", "le boeuf", "les boeufs", "un boeuf", "mes boeufs", "m" ),
array( "Bois", "le bois", "les bois", "un bois", "mes bois", "m" ),
array( "Boisson", "la boisson", "les boissons", "une boisson", "mes boissons", "f" ),
array( "Boîte", "la boîte", "les boîtes", "une boîte", "mes boîtes", "f" ),
array( "Bol", "le bol", "les bols", "un bol", "mes bols", "m" ),
array( "Bonbon", "le bonbon", "les bonbons", "un bonbon", "mes bonbons", "m" ),
array( "Bonhomme", "le bonhomme", "les bonhommes", "un bonhomme", "mes bonhommes", "m" ),
array( "Bonnet", "le bonnet", "les bonnets", "un bonnet", "mes bonnets", "m" ),
array( "Bord", "le bord", "les bords", "un bord", "mes bords", "m" ),
array( "Bosse", "la bosse", "les bosses", "une bosse", "mes bosses", "f" ),
array( "Botte", "la botte", "les bottes", "une botte", "mes bottes", "f" ),
array( "Botte de foin", "la botte de foin", "les bottes de foin", "une botte de foin", "mes bottes de foin", "f" ),
array( "Bouche", "la bouche", "les bouches", "une bouche", "mes bouches", "f" ),
array( "Boucherie", "la boucherie", "les boucheries", "une boucherie", "mes boucheries", "f" ),
array( "Bouchon", "le bouchon", "les bouchons", "un bouchon", "mes bouchons", "m" ),
array( "Boue", "la boue", "les boues", "une boue", "mes boues", "f" ),
array( "Bouée", "la bouée", "les bouées", "une bouée", "mes bouées", "f" ),
array( "Boulanger", "le boulanger", "les boulangers", "un boulanger", "mes boulangers", "m" ),
array( "Boulangerie", "la boulangerie", "les boulangeries", "une boulangerie", "mes boulangeries", "f" ),
array( "Boule", "la boule", "les boules", "une boule", "mes boules", "f" ),
array( "Bouquet", "le bouquet", "les bouquets", "un bouquet", "mes bouquets", "m" ),
array( "Bourgeon", "le bourgeon", "les bourgeons", "un bourgeon", "mes bourgeons", "m" ),
array( "Bout", "le bout", "les bouts", "un bout", "mes bouts", "m" ),
array( "Bouteille", "la bouteille", "les bouteilles", "une bouteille", "mes bouteilles", "f" ),
array( "Boutique", "la boutique", "les boutiques", "une boutique", "mes boutiques", "f" ),
array( "Bouton", "le bouton", "les boutons", "un bouton", "mes boutons", "m" ),
array( "Bracelet", "le bracelet", "les bracelets", "un bracelet", "mes bracelets", "m" ),
array( "Branche", "la branche", "les branches", "une branche", "mes branches", "f" ),
array( "Bras", "le bras", "les bras", "un bras", "mes bras", "m" ),
array( "Bretelle", "la bretelle", "les bretelles", "une bretelle", "mes bretelles", "f" ),
array( "Bricolage", "le bricolage", "les bricolages", "un bricolage", "mes bricolages", "m" ),
array( "Brosse", "la brosse", "les brosses", "une brosse", "mes brosses", "f" ),
array( "Brouette", "la brouette", "les brouettes", "une brouette", "mes brouettes", "f" ),
array( "Brouillard", "le brouillard", "les brouillards", "un brouillard", "mes brouillards", "m" ),
array( "Bruit", "le bruit", "les bruits", "un bruit", "mes bruits", "m" ),
array( "Bûche", "la bûche", "les bûches", "une bûche", "mes bûches", "f" ),
array( "Buisson", "le buisson", "les buissons", "un buisson", "mes buissons", "m" ),
array( "Bulle", "la bulle", "les bulles", "une bulle", "mes bulles", "f" ),
array( "Bureau", "le bureau", "les bureaux", "un bureau", "mes bureaux", "m" ),
array( "Bus", "le bus", "les bus", "un bus", "mes bus", "m" ),
array( "Cabane", "la cabane", "les cabanes", "une cabane", "mes cabanes", "f" ),
array( "Cabinet", "le cabinet", "les cabinets", "un cabinet", "mes cabinets", "m" ),
array( "Cadeau", "le cadeau", "les cadeaux", "un cadeau", "mes cadeaux", "m" ),
array( "Cadenas", "le cadenas", "les cadenas", "un cadenas", "mes cadenas", "m" ),
array( "Cadre", "le cadre", "les cadres", "un cadre", "mes cadres", "m" ),
array( "Café", "le café", "les cafés", "un café", "mes cafés", "m" ),
array( "Cage", "la cage", "les cages", "une cage", "mes cages", "f" ),
array( "Cage à écureuil", "la cage à écureuil", "les cages à écureuils", "une cage à écureuil", "mes cages à écureuils", "f" ),
array( "Cagoule", "la cagoule", "les cagoules", "une cagoule", "mes cagoules", "f" ),
array( "Cahier", "le cahier", "les cahiers", "un cahier", "mes cahiers", "m" ),
array( "Caillou", "le caillou", "les cailloux", "un caillou", "mes cailloux", "m" ),
array( "Caisse", "la caisse", "les caisses", "une caisse", "mes caisses", "f" ),
array( "Calendrier", "le calendrier", "les calendriers", "un calendrier", "mes calendriers", "m" ),
array( "Câlin", "le câlin", "les câlins", "un câlin", "mes câlins", "m" ),
array( "Camarade", "le camarade", "les camarades", "un camarade", "mes camarades", "m" ),
array( "Caméscope", "le caméscope", "les caméscopes", "un caméscope", "mes caméscopes", "m" ),
array( "Camion", "le camion", "les camions", "un camion", "mes camions", "m" ),
array( "Camp", "le camp", "les camps", "un camp", "mes camps", "m" ),
array( "Campagne", "la campagne", "les campagnes", "une campagne", "mes campagnes", "f" ),
array( "Canapé", "le canapé", "les canapés", "un canapé", "mes canapés", "m" ),
array( "Canard", "le canard", "les canards", "un canard", "mes canards", "m" ),
array( "Caniveau", "le caniveau", "les caniveaux", "un caniveau", "mes caniveaux", "m" ),
array( "Canne", "la canne", "les cannes", "une canne", "mes cannes", "f" ),
array( "Canne à pêche", "la canne à pêche", "les cannes à pêche", "une canne à pêche", "mes cannes à pêche", "f" ),
array( "Caprice", "le caprice", "les caprices", "un caprice", "mes caprices", "m" ),
array( "Car", "le car", "les cars", "un car", "mes cars", "m" ),
array( "Caravane", "la caravane", "les caravanes", "une caravane", "mes caravanes", "f" ),
array( "Caresse", "la caresse", "les caresses", "une caresse", "mes caresses", "f" ),
array( "Carnet", "le carnet", "les carnets", "un carnet", "mes carnets", "m" ),
array( "Carotte", "la carotte", "les carottes", "une carotte", "mes carottes", "f" ),
array( "Carré", "le carré", "les carrés", "un carré", "mes carrés", "m" ),
array( "Carreau", "le carreau", "les carreaux", "un carreau", "mes carreaux", "m" ),
array( "Carrefour", "le carrefour", "les carrefours", "un carrefour", "mes carrefours", "m" ),
array( "Cartable", "le cartable", "les cartables", "un cartable", "mes cartables", "m" ),
array( "Carton", "le carton", "les cartons", "un carton", "mes cartons", "m" ),
array( "Casier", "le casier", "les casiers", "un casier", "mes casiers", "m" ),
array( "Casque", "le casque", "les casques", "un casque", "mes casques", "m" ),
array( "Casquette", "la casquette", "les casquettes", "une casquette", "mes casquettes", "f" ),
array( "Casserole", "la casserole", "les casseroles", "une casserole", "mes casseroles", "f" ),
array( "Cassette", "la cassette", "les cassettes", "une cassette", "mes cassettes", "f" ),
array( "Catalogue", "le catalogue", "les catalogues", "un catalogue", "mes catalogues", "m" ),
array( "Cauchemar", "le cauchemar", "les cauchemars", "un cauchemar", "mes cauchemars", "m" ),
array( "Cave", "la cave", "les caves", "une cave", "mes caves", "f" ),
array( "CD-ROM", "le CD-ROM", "les CD-ROMs", "un CD-ROM", "mes CD-ROMs", "m" ),
array( "Ceinture", "la ceinture", "les ceintures", "une ceinture", "mes ceintures", "f" ),
array( "Cerceau", "le cerceau", "les cerceaux", "un cerceau", "mes cerceaux", "m" ),
array( "Céréale", "la céréale", "les céréales", "une céréale", "mes céréales", "f" ),
array( "Cerf", "le cerf", "les cerfs", "un cerf", "mes cerfs", "m" ),
array( "Cerf-volant", "le cerf-volant", "les cerf-volants", "un cerf-volant", "mes cerf-volants", "m" ),
array( "Cerise", "la cerise", "les cerises", "une cerise", "mes cerises", "f" ),
array( "Chaîne", "la chaîne", "les chaînes", "une chaîne", "mes chaînes", "f" ),
array( "Chaise", "la chaise", "les chaises", "une chaise", "mes chaises", "f" ),
array( "Chambre", "la chambre", "les chambres", "une chambre", "mes chambres", "f" ),
array( "Champ", "le champ", "les champs", "un champ", "mes champs", "m" ),
array( "Champignon", "le champignon", "les champignons", "un champignon", "mes champignons", "m" ),
array( "Chance", "la chance", "les chances", "une chance", "mes chances", "f" ),
array( "Chanson", "la chanson", "les chansons", "une chanson", "mes chansons", "f" ),
array( "Chapeau", "le chapeau", "les chapeaux", "un chapeau", "mes chapeaux", "m" ),
array( "Charcuterie", "la charcuterie", "les charcuteries", "une charcuterie", "mes charcuteries", "f" ),
array( "Chariot", "le chariot", "les chariots", "un chariot", "mes chariots", "m" ),
array( "Chasseur", "le chasseur", "les chasseurs", "un chasseur", "mes chasseurs", "m" ),
array( "Chat", "le chat", "les chats", "un chat", "mes chats", "m" ),
array( "Châtaigne", "la châtaigne", "les châtaignes", "une châtaigne", "mes châtaignes", "f" ),
array( "Château", "le château", "les châteaux", "un château", "mes châteaux", "m" ),
array( "Chaussette", "la chaussette", "les chaussettes", "une chaussette", "mes chaussettes", "f" ),
array( "Chausson", "le chausson", "les chaussons", "un chausson", "mes chaussons", "m" ),
array( "Chaussure", "la chaussure", "les chaussures", "une chaussure", "mes chaussures", "m" ),
array( "Chemin", "le chemin", "les chemins", "un chemin", "mes chemins", "m" ),
array( "Cheminée", "la cheminée", "les cheminées", "une cheminée", "mes cheminées", "f" ),
array( "Chemise", "la chemise", "les chemises", "une chemise", "mes chemises", "f" ),
array( "Chêne", "le chêne", "les chênes", "un chêne", "mes chênes", "m" ),
array( "Chenille", "la chenille", "les chenilles", "une chenille", "mes chenilles", "f" ),
array( "Cheval", "le cheval", "les chevaux", "un cheval", "mes chevaux", "m" ),
array( "Cheveu", "le cheveu", "les cheveux", "un cheveu", "mes cheveux", "m" ),
array( "Cheville", "la cheville", "les chevilles", "une cheville", "mes chevilles", "f" ),
array( "Chèvre", "la chèvre", "les chèvres", "une chèvre", "mes chèvres", "f" ),
array( "Chien", "le chien", "les chiens", "un chien", "mes chiens", "m" ),
array( "Chiffon", "le chiffon", "les chiffons", "un chiffon", "mes chiffons", "m" ),
array( "Chiffre", "le chiffre", "les chiffres", "un chiffre", "mes chiffres", "m" ),
array( "Chocolat", "le chocolat", "les chocolats", "un chocolat", "mes chocolats", "m" ),
array( "Chose", "la chose", "les choses", "une chose", "mes choses", "f" ),
array( "Chou", "le chou", "les choux", "un chou", "mes choux", "m" ),
array( "Chouette", "la chouette", "les chouettes", "une chouette", "mes chouettes", "f" ),
array( "Chute", "la chute", "les chutes", "une chute", "mes chutes", "f" ),
array( "Ciel", "le ciel", "les ciels", "un ciel", "mes ciels", "m" ),
array( "Cigarette", "la cigarette", "les cigarettes", "une cigarette", "mes cigarettes", "f" ),
array( "Cigogne", "la cigogne", "les cigognes", "une cigogne", "mes cigognes", "f" ),
array( "Cil", "le cil", "les cils", "un cil", "mes cils", "m" ),
array( "Cimetière", "le cimetière", "les cimetières", "un cimetière", "mes cimetières", "m" ),
array( "Cinéma", "le cinéma", "les cinémas", "un cinéma", "mes cinémas", "m" ),
array( "Cirque", "le cirque", "les cirques", "un cirque", "mes cirques", "m" ),
array( "Ciseau", "le ciseau", "les ciseaux", "un ciseau", "mes ciseaux", "m" ),
array( "Citron", "le citron", "les citrons", "un citron", "mes citrons", "m" ),
array( "Citrouille", "la citrouille", "les citrouilles", "une citrouille", "mes citrouilles", "f" ),
array( "Classe", "la classe", "les classes", "une classe", "mes classes", "f" ),
array( "Clé", "la clé", "les clés", "une clé", "mes clés", "f" ),
array( "Clémentine", "la clémentine", "les clémentines", "une clémentine", "mes clémentines", "f" ),
array( "Clin d’oeil", "le clin d’oeil", "les clins d’oeil", "un clin d’oeil", "mes clins d’oeil", "m" ),
array( "Cloche", "la cloche", "les cloches", "une cloche", "mes cloches", "m" ),
array( "Clocher", "le clocher", "les clochers", "un clocher", "mes clochers", "m" ),
array( "Clou", "le clou", "les clous", "un clou", "mes clous", "m" ),
array( "Clown", "le clown", "les clowns", "un clown", "mes clowns", "m" ),
array( "Coccinelle", "la coccinelle", "les coccinelles", "une coccinelle", "mes coccinelles", "f" ),
array( "Cochon", "le cochon", "les cochons", "un cochon", "mes cochons", "m" ),
array( "Cochon d’Inde", "le cochon d’Inde", "les cochons d’Inde", "un cochon d’Inde", "mes cochons d’Inde", "m" ),
array( "Cocotte", "la cocotte", "les cocottes", "une cocotte", "mes cocottes", "f" ),
array( "Coeur", "le coeur", "les coeurs", "un coeur", "mes coeurs", "m" ),
array( "Coffre", "le coffre", "les coffres", "un coffre", "mes coffres", "m" ),
array( "Coffret", "le coffret", "les coffrets", "un coffret", "mes coffrets", "m" ),
array( "Coiffeur", "le coiffeur", "les coiffeurs", "un coiffeur", "mes coiffeurs", "m" ),
array( "Coin", "le coin", "les coins", "un coin", "mes coins", "m" ),
array( "Col", "le col", "les cols", "un col", "mes cols", "m" ),
array( "Colère", "la colère", "les colères", "une colère", "mes colères", "f" ),
array( "Collant", "le collant", "les collants", "un collant", "mes collants", "m" ),
array( "Colle", "la colle", "les colles", "une colle", "mes colles", "f" ),
array( "Collier", "le collier", "les colliers", "un collier", "mes colliers", "m" ),
array( "Colline", "la colline", "les collines", "une colline", "mes collines", "f" ),
array( "Coloriage", "le coloriage", "les coloriages", "un coloriage", "mes coloriages", "m" ),
array( "Concombre", "le concombre", "les concombres", "un concombre", "mes concombres", "m" ),
array( "Confiture", "la confiture", "les confitures", "une confiture", "mes confitures", "f" ),
array( "Conte", "le conte", "les contes", "un conte", "mes contes", "m" ),
array( "Contraire", "le contraire", "les contraires", "un contraire", "mes contraires", "m" ),
array( "Copain", "le copain", "les copains", "un copain", "mes copains", "m" ),
array( "Coq", "le coq", "les coqs", "un coq", "mes coqs", "m" ),
array( "Coquelicot", "le coquelicot", "les coquelicots", "un coquelicot", "mes coquelicots", "m" ),
array( "Coquetier", "le coquetier", "les coquetiers", "un coquetier", "mes coquetiers", "m" ),
array( "Coquillage", "le coquillage", "les coquillages", "un coquillage", "mes coquillages", "m" ),
array( "Coquille", "la coquille", "les coquilles", "une coquille", "mes coquilles", "f" ),
array( "Coquin", "le coquin", "les coquins", "un coquin", "mes coquins", "m" ),
array( "Corbeau", "le corbeau", "les corbeaux", "un corbeau", "mes corbeaux", "m" ),
array( "Corbeille", "la corbeille", "les corbeilles", "une corbeille", "mes corbeilles", "f" ),
array( "Corde", "la corde", "les cordes", "une corde", "mes cordes", "f" ),
array( "Corps", "le corps", "les corps", "un corps", "mes corps", "m" ),
array( "Côté", "le côté", "les côtés", "un côté", "mes côtés", "m" ),
array( "Cou", "le cou", "les cous", "un cou", "mes cous", "m" ),
array( "Coude", "le coude", "les coudes", "un coude", "mes coudes", "m" ),
array( "Couette", "la couette", "les couettes", "une couette", "mes couettes", "f" ),
array( "Couleur", "la couleur", "les couleurs", "une couleur", "mes couleurs", "f" ),
array( "Couloir", "le couloir", "les couloirs", "un couloir", "mes couloirs", "m" ),
array( "Coup", "le coup", "les coups", "un coup", "mes coups", "m" ),
array( "Cour", "la cour", "les cours", "une cour", "mes cours", "f" ),
array( "Couronne", "la couronne", "les couronnes", "une couronne", "mes couronnes", "f" ),
array( "Courrier", "le courrier", "les courriers", "un courrier", "mes courriers", "m" ),
array( "Course", "la course", "les courses", "une course", "mes courses", "f" ),
array( "Cousin", "le cousin", "les cousins", "un cousin", "mes cousins", "m" ),
array( "Cousine", "la cousine", "les cousines", "une cousine", "mes cousines", "f" ),
array( "Coussin", "le coussin", "les coussins", "un coussin", "mes coussins", "m" ),
array( "Couteau", "le couteau", "les couteaux", "un couteau", "mes couteaux", "m" ),
array( "Couvercle", "le couvercle", "les couvercles", "un couvercle", "mes couvercles", "m" ),
array( "Couvert", "le couvert", "les couverts", "un couvert", "mes couverts", "m" ),
array( "Couverture", "la couverture", "les couvertures", "une couverture", "mes couvertures", "f" ),
array( "Crabe", "le crabe", "les crabes", "un crabe", "mes crabes", "m" ),
array( "Craie", "la craie", "les craies", "une craie", "mes craies", "f" ),
array( "Crapaud", "le crapaud", "les crapauds", "un crapaud", "mes crapauds", "m" ),
array( "Cravate", "la cravate", "les cravates", "une cravate", "mes cravates", "f" ),
array( "Crayon", "le crayon", "les crayons", "un crayon", "mes crayons", "m" ),
array( "Crèche", "la crèche", "les crèches", "une crèche", "mes crèches", "f" ),
array( "Crêpe", "la crêpe", "les crêpes", "une crêpe", "mes crêpes", "f" ),
array( "Crevette", "la crevette", "les crevettes", "une crevette", "mes crevettes", "f" ),
array( "Cri", "le cri", "les cris", "un cri", "mes cris", "m" ),
array( "Crochet", "le crochet", "les crochets", "un crochet", "mes crochets", "m" ),
array( "Crocodile", "le crocodile", "les crocodiles", "un crocodile", "mes crocodiles", "m" ),
array( "Croix", "la croix", "les croix", "une croix", "mes croix", "f" ),
array( "Croûte", "la croûte", "les croûtes", "une croûte", "mes croûtes", "f" ),
array( "Cube", "le cube", "les cubes", "un cube", "mes cubes", "m" ),
array( "Cuillère", "la cuillère", "les cuillères", "une cuillère", "mes cuillères", "f" ),
array( "Cuisine", "la cuisine", "les cuisines", "une cuisine", "mes cuisines", "f" ),
array( "Cuisinière", "la cuisinière", "les cuisinières", "une cuisinière", "mes cuisinières", "f" ),
array( "Cuisse", "la cuisse", "les cuisses", "une cuisse", "mes cuisses", "f" ),
array( "Culotte", "la culotte", "les culottes", "une culotte", "mes culottes", "f" ),
array( "Cuvette", "la cuvette", "les cuvettes", "une cuvette", "mes cuvettes", "f" ),
array( "Cygne", "le cygne", "les cygnes", "un cygne", "mes cygnes", "m" ),
array( "Dame", "la dame", "les dames", "une dame", "mes dames", "f" ),
array( "Danger", "le danger", "les dangers", "un danger", "mes dangers", "m" ),
array( "Danse", "la danse", "les danses", "une danse", "mes danses", "f" ),
array( "Dauphin", "le dauphin", "les dauphins", "un dauphin", "mes dauphins", "m" ),
array( "Dé", "le dé", "les dés", "un dé", "mes dés", "m" ),
array( "Début", "le début", "les débuts", "un début", "mes débuts", "m" ),
array( "Découpage", "le découpage", "les découpages", "un découpage", "mes découpages", "m" ),
array( "Déguisement", "le déguisement", "les déguisements", "un déguisement", "mes déguisements", "m" ),
array( "Dent", "la dent", "les dents", "une dent", "mes dents", "f" ),
array( "Dentifrice", "le dentifrice", "les dentifrices", "un dentifrice", "mes dentifrices", "m" ),
array( "Dentiste", "le dentiste", "les dentistes", "un dentiste", "mes dentistes", "m" ),
array( "Départ", "le départ", "les départs", "un départ", "mes départs", "m" ),
array( "Désordre", "le désordre", "les désordres", "un désordre", "mes désordres", "m" ),
array( "Dessert", "le dessert", "les desserts", "un dessert", "mes desserts", "m" ),
array( "Dessin", "le dessin", "les dessins", "un dessin", "mes dessins", "m" ),
array( "Dictionnaire", "le dictionnaire", "les dictionnaires", "un dictionnaire", "mes dictionnaires", "m" ),
array( "Différence", "la différence", "les différences", "une différence", "mes différences", "f" ),
array( "Dimanche", "le dimanche", "les dimanches", "un dimanche", "mes dimanches", "m" ),
array( "Dindon", "le dindon", "les dindons", "un dindon", "mes dindons", "m" ),
array( "Dînette", "la dînette", "les dînettes", "une dînette", "mes dînettes", "f" ),
array( "Dinosaure", "le dinosaure", "les dinosaures", "un dinosaure", "mes dinosaures", "m" ),
array( "Directeur", "le directeur", "les directeurs", "un directeur", "mes directeurs", "m" ),
array( "Directrice", "la directrice", "les directrices", "une directrice", "mes directrices", "f" ),
array( "Docteur", "le docteur", "les docteurs", "un docteur", "mes docteurs", "m" ),
array( "Doigt", "le doigt", "les doigts", "un doigt", "mes doigts", "m" ),
array( "Domino", "le domino", "les dominos", "un domino", "mes dominos", "m" ),
array( "Dos", "le dos", "les dos", "un dos", "mes dos", "m" ),
array( "Dossier", "le dossier", "les dossiers", "un dossier", "mes dossiers", "m" ),
array( "Douche", "la douche", "les douches", "une douche", "mes douches", "f" ),
array( "Drap", "le drap", "les draps", "un drap", "mes draps", "m" ),
array( "Drapeau", "le drapeau", "les drapeaux", "un drapeau", "mes drapeaux", "m" ),
array( "Droit", "le droit", "les droits", "un droit", "mes droits", "m" ),
array( "Eau", "l'eau", "les eaux", "une eau", "mes eaux", "f" ),
array( "Écharpe", "l'écharpe", "les écharpes", "une écharpe", "mes écharpes", "f" ),
array( "Échasse", "l'échasse", "les échasses", "une échasse", "mes échasses", "f" ),
array( "Échelle", "l'échelle", "les échelles", "une échelle", "mes échelles", "f" ),
array( "Éclair", "l'éclair", "les éclairs", "un éclair", "mes éclairs", "m" ),
array( "École", "l'école", "les écoles", "une école", "mes écoles", "f" ),
array( "Écorce", "l'écorce", "les écorces", "une écorce", "mes écorces", "f" ),
array( "Écran", "l'écran", "les écrans", "un écran", "mes écrans", "m" ),
array( "Écriture", "l'écriture", "les écritures", "une écriture", "mes écritures", "f" ),
array( "Écureuil", "l'écureuil", "les écureuils", "un écureuil", "mes écureuils", "m" ),
array( "Effort", "l'effort", "les efforts", "un effort", "mes efforts", "m" ),
array( "Église", "l'église", "les églises", "une église", "mes églises", "f" ),
array( "Élastique", "l'élastique", "les élastiques", "un élastique", "mes élastiques", "m" ),
array( "Éléphant", "l'éléphant", "les éléphants", "un éléphant", "mes éléphants", "m" ),
array( "Élève", "l'élève", "les élèves", "un élève", "mes élèves", "m" ),
array( "Embouteillage", "l'embouteillage", "les embouteillages", "un embouteillage", "mes embouteillages", "m" ),
array( "Endive", "l'endive", "les endives", "une endive", "mes endives", "f" ),
array( "Endroit", "l'endroit", "les endroits", "un endroit", "mes endroits", "m" ),
array( "Enfant", "l'enfant", "les enfants", "un enfant", "mes enfants", "m" ),
array( "Engin", "l'engin", "les engins", "un engin", "mes engins", "m" ),
array( "Entonnoir", "l'entonnoir", "les entonnoirs", "un entonnoir", "mes entonnoirs", "m" ),
array( "Entrée", "l'entrée", "les entrées", "une entrée", "mes entrées", "f" ),
array( "Enveloppe", "l'enveloppe", "les enveloppes", "une enveloppe", "mes enveloppes", "f" ),
array( "Envie", "l'envie", "les envies", "une envie", "mes envies", "f" ),
array( "Épaule", "l'épaule", "les épaules", "une épaule", "mes épaules", "f" ),
array( "Épée", "l'épée", "les épées", "une épée", "mes épées", "f" ),
array( "Épingle", "l'épingle", "les épingles", "une épingle", "mes épingles", "f" ),
array( "Épluchure", "l'épluchure", "les épluchures", "une épluchure", "mes épluchures", "f" ),
array( "Éponge", "l'éponge", "les éponges", "une éponge", "mes éponges", "f" ),
array( "Équipe", "l'équipe", "les équipes", "une équipe", "mes équipes", "f" ),
array( "Escabeau", "l'escabeau", "les escabeaux", "un escabeau", "mes escabeaux", "m" ),
array( "Escalier", "l'escalier", "les escaliers", "un escalier", "mes escaliers", "m" ),
array( "Escargot", "l'escargot", "les escargots", "un escargot", "mes escargots", "m" ),
array( "Essence", "l'essence", "les essences", "une essence", "mes essences", "f" ),
array( "Étagère", "l'étagère", "les étagères", "une étagère", "mes étagères", "f" ),
array( "Étang", "l'étang", "les étangs", "un étang", "mes étangs", "m" ),
array( "Été", "l'été", "les étés", "un été", "mes étés", "m" ),
array( "Étiquette", "l'étiquette", "les étiquettes", "une étiquette", "mes étiquettes", "f" ),
array( "Étoile", "l'étoile", "les étoiles", "une étoile", "mes étoiles", "f" ),
array( "Étude", "l'étude", "les études", "une étude", "mes études", "f" ),
array( "Évier", "l'évier", "les éviers", "un évier", "mes éviers", "m" ),
array( "Extérieur", "l'extérieur", "les extérieurs", "un extérieur", "mes extérieurs", "m" ),
array( "Facteur", "le facteur", "les facteurs", "un facteur", "mes facteurs", "m" ),
array( "Faim", "la faim", "les faims", "une faim", "mes faims", "f" ),
array( "Farce", "la farce", "les farces", "une farce", "mes farces", "f" ),
array( "Farine", "la farine", "les farines", "une farine", "mes farines", "f" ),
array( "Fatigue", "la fatigue", "les fatigues", "une fatigue", "mes fatigues", "f" ),
array( "Faute", "la faute", "les fautes", "une faute", "mes fautes", "f" ),
array( "Fauteuil", "le fauteuil", "les fauteuils", "un fauteuil", "mes fauteuils", "m" ),
array( "Fée", "la fée", "les fées", "une fée", "mes fées", "f" ),
array( "Femme", "la femme", "les femmes", "une femme", "mes femmes", "f" ),
array( "Fenêtre", "la fenêtre", "les fenêtres", "une fenêtre", "mes fenêtres", "f" ),
array( "Fer à repasser", "le fer à repasser", "les fers à repasser", "un fer à repasser", "mes fers à repasser", "m" ),
array( "Ferme", "la ferme", "les fermes", "une ferme", "mes fermes", "f" ),
array( "Fermier", "le fermier", "les fermiers", "un fermier", "mes fermiers", "m" ),
array( "Fesse", "la fesse", "les fesses", "une fesse", "mes fesses", "f" ),
array( "Fête", "la fête", "les fêtes", "une fête", "mes fêtes", "f" ),
array( "Feu", "le feu", "les feux", "un feu", "mes feux", "m" ),
array( "Feuille", "la feuille", "les feuilles", "une feuille", "mes feuilles", "f" ),
array( "Feutre", "le feutre", "les feutres", "un feutre", "mes feutres", "m" ),
array( "Fève", "la fève", "les fèves", "une fève", "mes fèves", "f" ),
array( "Ficelle", "la ficelle", "les ficelles", "une ficelle", "mes ficelles", "f" ),
array( "Fièvre", "la fièvre", "les fièvres", "une fièvre", "mes fièvres", "f" ),
array( "Figure", "la figure", "les figures", "une figure", "mes figures", "f" ),
array( "Fil", "le fil", "les fils", "un fil", "mes fils", "m" ),
array( "Filet", "le filet", "les filets", "un filet", "mes filets", "m" ),
array( "Fille", "la fille", "les filles", "une fille", "mes filles", "f" ),
array( "Film", "le film", "les films", "un film", "mes films", "m" ),
array( "Fils", "le fils", "les fils", "un fils", "mes fils", "m" ),
array( "Fin", "la fin", "les fins", "une fin", "mes fins", "f" ),
array( "Flamme", "la flamme", "les flammes", "une flamme", "mes flammes", "f" ),
array( "Flaque", "la flaque", "les flaques", "une flaque", "mes flaques", "f" ),
array( "Flèche", "la flèche", "les flèches", "une flèche", "mes flèches", "f" ),
array( "Fleur", "la fleur", "les fleurs", "une fleur", "mes fleurs", "f" ),
array( "Fleuriste", "le fleuriste", "les fleuristes", "un fleuriste", "mes fleuristes", "m" ),
array( "Flocon", "le flocon", "les flocons", "un flocon", "mes flocons", "m" ),
array( "Foin", "le foin", "les foins", "un foin", "mes foins", "m" ),
array( "Foire", "la foire", "les foires", "une foire", "mes foires", "f" ),
array( "Fois", "la foi", "les fois", "une foi", "mes fois", "f" ),
array( "Fond", "le fond", "les fonds", "un fond", "mes fonds", "m" ),
array( "Fontaine", "la fontaine", "les fontaines", "une fontaine", "mes fontaines", "f" ),
array( "Forêt", "la forêt", "les forêts", "une forêt", "mes forêts", "f" ),
array( "Forme", "la forme", "les formes", "une forme", "mes formes", "f" ),
array( "Four", "le four", "les fours", "un four", "mes fours", "m" ),
array( "Fourchette", "la fourchette", "les fourchettes", "une fourchette", "mes fourchettes", "f" ),
array( "Fourmi", "la fourmi", "les fourmis", "une fourmi", "mes fourmis", "f" ),
array( "Fraise", "la fraise", "les fraises", "une fraise", "mes fraises", "f" ),
array( "Framboise", "la framboise", "les framboises", "une framboise", "mes framboises", "f" ),
array( "Frange", "la frange", "les franges", "une frange", "mes franges", "f" ),
array( "Frein", "le frein", "les freins", "un frein", "mes freins", "m" ),
array( "Frère", "le frère", "les frères", "un frère", "mes frères", "m" ),
array( "Frite", "la frite", "les frites", "une frite", "mes frites", "f" ),
array( "Fromage", "le fromage", "les fromages", "un fromage", "mes fromages", "m" ),
array( "Front", "le front", "les fronts", "un front", "mes fronts", "m" ),
array( "Fruit", "le fruit", "les fruits", "un fruit", "mes fruits", "m" ),
array( "Fumée", "la fumée", "les fumées", "une fumée", "mes fumées", "f" ),
array( "Fusée", "la fusée", "les fusées", "une fusée", "mes fusées", "f" ),
array( "Fusil", "le fusil", "les fusils", "un fusil", "mes fusils", "m" ),
array( "Galette", "la galette", "les galettes", "une galette", "mes galettes", "f" ),
array( "Gant", "le gant", "les gants", "un gant", "mes gants", "m" ),
array( "Garage", "le garage", "les garages", "un garage", "mes garages", "m" ),
array( "Garçon", "le garçon", "les garçons", "un garçon", "mes garçons", "m" ),
array( "Gardien", "le gardien", "les gardiens", "un gardien", "mes gardiens", "m" ),
array( "Gare", "la gare", "les gares", "une gare", "mes gares", "f" ),
array( "Gâteau", "le gâteau", "les gâteaux", "un gâteau", "mes gâteaux", "m" ),
array( "Géant", "le géant", "les géants", "un géant", "mes géants", "m" ),
array( "Genou", "le genou", "les genoux", "un genou", "mes genoux", "m" ),
array( "Girafe", "la girafe", "les girafes", "une girafe", "mes girafes", "f" ),
array( "Glace", "la glace", "les glaces", "une glace", "mes glaces", "f" ),
array( "Glaçon", "le glaçon", "les glaçons", "un glaçon", "mes glaçons", "m" ),
array( "Gobelet", "le gobelet", "les gobelets", "un gobelet", "mes gobelets", "m" ),
array( "Gomme", "la gomme", "les gommes", "une gomme", "mes gommes", "f" ),
array( "Gorge", "la gorge", "les gorges", "une gorge", "mes gorges", "f" ),
array( "Gourde", "la gourde", "les gourdes", "une gourde", "mes gourdes", "f" ),
array( "Goût", "le goût", "les goûts", "un goût", "mes goûts", "m" ),
array( "Goutte", "la goutte", "les gouttes", "une goutte", "mes gouttes", "f" ),
array( "Grain", "le grain", "les grains", "un grain", "mes grains", "m" ),
array( "Graine", "la graine", "les graines", "une graine", "mes graines", "f" ),
array( "Grand-mère", "la grand-mère", "les grand-mères", "une grand-mère", "mes grand-mères", "f" ),
array( "Grand-parent", "le grand-parent", "les grand-parents", "un grand-parent", "mes grand-parents", "m" ),
array( "Grand-père", "le grand-père", "les grand-pères", "un grand-père", "mes grand-pères", "m" ),
array( "Grenouille", "la grenouille", "les grenouilles", "une grenouille", "mes grenouilles", "f" ),
array( "Griffe", "la griffe", "les griffes", "une griffe", "mes griffes", "f" ),
array( "Grimace", "la grimace", "les grimaces", "une grimace", "mes grimaces", "f" ),
array( "Grotte", "la grotte", "les grottes", "une grotte", "mes grottes", "f" ),
array( "Grue", "la grue", "les grues", "une grue", "mes grues", "f" ),
array( "Guêpe", "la guêpe", "les guêpes", "une guêpe", "mes guêpes", "f" ),
array( "Guirlande", "la guirlande", "les guirlandes", "une guirlande", "mes guirlandes", "f" ),
array( "Gymnastique", "la gymnastique", "les gymnastiques", "une gymnastique", "mes gymnastiques", "f" ),
array( "Habit", "l'habit", "les habits", "un habit", "mes habits", "m" ),
array( "Hamster", "le hamster", "les hamsters", "un hamster", "mes hamsters", "m" ),
array( "Hanche", "la hanche", "les hanches", "une hanche", "mes hanches", "f" ),
array( "Haricot", "le haricot", "les haricots", "un haricot", "mes haricots", "m" ),
array( "Hélicoptère", "l'hélicoptère", "les hélicoptères", "un hélicoptère", "mes hélicoptères", "m" ),
array( "Herbe", "l'herbe", "les herbes", "une herbe", "mes herbes", "f" ),
array( "Hérisson", "le hérisson", "les hérissons", "un hérisson", "mes hérissons", "m" ),
array( "Heure", "l'heure", "les heures", "une heure", "mes heures", "f" ),
array( "Hibou", "le hibou", "les hiboux", "un hibou", "mes hiboux", "m" ),
array( "Hippopotame", "l'hippopotame", "les hippopotames", "un hippopotame", "mes hippopotames", "m" ),
array( "Hirondelle", "l'hirondelle", "les hirondelles", "une hirondelle", "mes hirondelles", "f" ),
array( "Histoire", "l'histoire", "les histoires", "une histoire", "mes histoires", "f" ),
array( "Hiver", "l'hiver", "les hivers", "un hiver", "mes hivers", "m" ),
array( "Homme", "l'homme", "les hommes", "un homme", "mes hommes", "m" ),
array( "Hôpital", "l'hôpital", "les hôpitaux", "un hôpital", "mes hôpitaux", "m" ),
array( "Horloge", "l'horloge", "les horloges", "une horloge", "mes horloges", "f" ),
array( "Hôtel", "l'hôtel", "les hôtels", "un hôtel", "mes hôtels", "m" ),
array( "Huile", "l'huile", "les huiles", "une huile", "mes huiles", "f" ),
array( "Humeur", "l'humeur", "les humeurs", "une humeur", "mes humeurs", "f" ),
array( "Idée", "l'idée", "les idées", "une idée", "mes idées", "f" ),
array( "Île", "l'île", "les îles", "une île", "mes îles", "f" ),
array( "Image", "l'image", "les images", "une image", "mes images", "f" ),
array( "Immeuble", "l'immeuble", "les immeubles", "un immeuble", "mes immeubles", "m" ),
array( "Incendie", "l'incendie", "les incendies", "un incendie", "mes incendies", "m" ),
array( "Infirmier", "l'infirmier", "les infirmiers", "un infirmier", "mes infirmiers", "m" ),
array( "Infirmière", "l'infirmière", "les infirmières", "une infirmière", "mes infirmières", "f" ),
array( "Insecte", "l'insecte", "les insectes", "un insecte", "mes insectes", "m" ),
array( "Instrument", "l'instrument", "les instruments", "un instrument", "mes instruments", "m" ),
array( "Intérieur", "l'intérieur", "les intérieurs", "un intérieur", "mes intérieurs", "m" ),
array( "Intrus", "l'intrus", "les intrus", "un intrus", "mes intrus", "m" ),
array( "Invitation", "l'invitation", "les invitations", "une invitation", "mes invitations", "f" ),
array( "Jambe", "la jambe", "les jambes", "une jambe", "mes jambes", "f" ),
array( "Jambon", "le jambon", "les jambons", "un jambon", "mes jambons", "m" ),
array( "Jardin", "le jardin", "les jardins", "un jardin", "mes jardins", "m" ),
array( "Jean", "le jean", "les jeans", "un jean", "mes jeans", "m" ),
array( "Jeu", "le jeu", "les jeux", "un jeu", "mes jeux", "m" ),
array( "Jeudi", "le jeudi", "les jeudis", "un jeudi", "mes jeudis", "m" ),
array( "Joie", "la joie", "les joies", "une joie", "mes joies", "f" ),
array( "Jonquille", "la jonquille", "les jonquilles", "une jonquille", "mes jonquilles", "f" ),
array( "Joue", "la joue", "les joues", "une joue", "mes joues", "f" ),
array( "Jouet", "le jouet", "les jouets", "un jouet", "mes jouets", "m" ),
array( "Jour", "le jour", "les jours", "un jour", "mes jours", "m" ),
array( "Journal", "le journal", "les journaux", "un journal", "mes journaux", "m" ),
array( "Journée", "la journée", "les journées", "une journée", "mes journées", "f" ),
array( "Jumeau", "le jumeau", "les jumeaux", "un jumeau", "mes jumeaux", "m" ),
array( "Jumelle", "la jumelle", "les jumelles", "une jumelle", "mes jumelles", "f" ),
array( "Jupe", "la jupe", "les jupes", "une jupe", "mes jupes", "f" ),
array( "Jus", "le jus", "les jus", "un jus", "mes jus", "m" ),
array( "Kangourou", "le kangourou", "les kangourous", "un kangourou", "mes kangourous", "m" ),
array( "Kiwi", "le kiwi", "les kiwis", "un kiwi", "mes kiwis", "m" ),
array( "Lac", "le lac", "les lacs", "un lac", "mes lacs", "m" ),
array( "Lacet", "le lacet", "les lacets", "un lacet", "mes lacets", "m" ),
array( "Laine", "la laine", "les laines", "une laine", "mes laines", "f" ),
array( "Laisse", "la laisse", "les laisses", "une laisse", "mes laisses", "f" ),
array( "Lait", "le lait", "les laits", "un lait", "mes laits", "m" ),
array( "Lame", "la lame", "les lames", "une lame", "mes lames", "f" ),
array( "Lampe", "la lampe", "les lampes", "une lampe", "mes lampes", "f" ),
array( "Langue", "la langue", "les langues", "une langue", "mes langues", "f" ),
array( "Lapin", "le lapin", "les lapins", "un lapin", "mes lapins", "m" ),
array( "Larme", "la larme", "les larmes", "une larme", "mes larmes", "f" ),
array( "Lavabo", "le lavabo", "les lavabos", "un lavabo", "mes lavabos", "m" ),
array( "Lave-linge", "le lave-linge", "les lave-linges", "un lave-linge", "mes lave-linges", "m" ),
array( "Lecture", "la lecture", "les lectures", "une lecture", "mes lectures", "f" ),
array( "Légume", "le légume", "les légumes", "un légume", "mes légumes", "m" ),
array( "Lessive", "la lessive", "les lessives", "une lessive", "mes lessives", "f" ),
array( "Lettre", "la lettre", "les lettres", "une lettre", "mes lettres", "f" ),
array( "Lèvre", "la lèvre", "les lèvres", "une lèvre", "mes lèvres", "f" ),
array( "Lézard", "le lézard", "les lézards", "un lézard", "mes lézards", "m" ),
array( "Ligne", "la ligne", "les lignes", "une ligne", "mes lignes", "f" ),
array( "Linge", "le linge", "les linges", "un linge", "mes linges", "m" ),
array( "Lion", "le lion", "les lions", "un lion", "mes lions", "m" ),
array( "Liquide", "le liquide", "les liquides", "un liquide", "mes liquides", "m" ),
array( "Liste", "la liste", "les listes", "une liste", "mes listes", "f" ),
array( "Lit", "le lit", "les lits", "un lit", "mes lits", "m" ),
array( "Litre", "le litre", "les litres", "un litre", "mes litres", "m" ),
array( "Livre", "le livre", "les livres", "un livre", "mes livres", "m" ),
array( "Louche", "la louche", "les louches", "une louche", "mes louches", "f" ),
array( "Loup", "le loup", "les loups", "un loup", "mes loups", "m" ),
array( "Loupe", "la loupe", "les loupes", "une loupe", "mes loupes", "f" ),
array( "Luge", "la luge", "les luges", "une luge", "mes luges", "f" ),
array( "Lumière", "la lumière", "les lumières", "une lumière", "mes lumières", "f" ),
array( "Lundi", "le lundi", "les lundis", "un lundi", "mes lundis", "m" ),
array( "Lune", "la lune", "les lunes", "une lune", "mes lunes", "f" ),
array( "Lunettes", "la lunettes", "les lunettes", "une lunettes", "mes lunettes", "f" ),
array( "Lutin", "le lutin", "les lutins", "un lutin", "mes lutins", "m" ),
array( "Machine", "la machine", "les machines", "une machine", "mes machines", "f" ),
array( "Madame", "la madame", "les madames", "une madame", "mes madames", "f" ),
array( "Magasin", "le magasin", "les magasins", "un magasin", "mes magasins", "m" ),
array( "Magazine", "le magazine", "les magazines", "un magazine", "mes magazines", "m" ),
array( "Magicien", "le magicien", "les magiciens", "un magicien", "mes magiciens", "m" ),
array( "Magie", "la magie", "les magies", "une magie", "mes magies", "f" ),
array( "Magnétoscope", "le magnétoscope", "les magnétoscopes", "un magnétoscope", "mes magnétoscopes", "m" ),
array( "Maillot", "le maillot", "les maillots", "un maillot", "mes maillots", "m" ),
array( "Main", "la main", "les mains", "une main", "mes mains", "f" ),
array( "Maison", "la maison", "les maisons", "une maison", "mes maisons", "f" ),
array( "Maître", "le maître", "les maîtres", "un maître", "mes maîtres", "m" ),
array( "Maîtresse", "la maîtresse", "les maîtresses", "une maîtresse", "mes maîtresses", "f" ),
array( "Maman", "la maman", "les mamans", "une maman", "mes mamans", "f" ),
array( "Manche", "le manche", "les manches", "un manche", "mes manches", "m" ),
array( "Manège", "le manège", "les manèges", "un manège", "mes manèges", "m" ),
array( "Manteau", "le manteau", "les manteaux", "un manteau", "mes manteaux", "m" ),
array( "Maquillage", "le maquillage", "les maquillages", "un maquillage", "mes maquillages", "m" ),
array( "Marchand", "le marchand", "les marchands", "un marchand", "mes marchands", "m" ),
array( "Marche", "la marche", "les marches", "une marche", "mes marches", "f" ),
array( "Mardi", "le mardi", "les mardis", "un mardi", "mes mardis", "m" ),
array( "Mare", "la mare", "les mares", "une mare", "mes mares", "f" ),
array( "Marguerite", "la marguerite", "les marguerites", "une marguerite", "mes marguerites", "f" ),
array( "Mari", "le mari", "les maris", "un mari", "mes maris", "m" ),
array( "Mariage", "le mariage", "les mariages", "un mariage", "mes mariages", "m" ),
array( "Marin", "le marin", "les marins", "un marin", "mes marins", "m" ),
array( "Marionnette", "la marionnette", "les marionnettes", "une marionnette", "mes marionnettes", "f" ),
array( "Marron", "le marron", "les marrons", "un marron", "mes marrons", "m" ),
array( "Marteau", "le marteau", "les marteaux", "un marteau", "mes marteaux", "m" ),
array( "Masque", "le masque", "les masques", "un masque", "mes masques", "m" ),
array( "Matelas", "le matelas", "les matelas", "un matelas", "mes matelas", "m" ),
array( "Maternelle", "la maternelle", "les maternelles", "une maternelle", "mes maternelles", "f" ),
array( "Matin", "le matin", "les matins", "un matin", "mes matins", "m" ),
array( "Médecin", "le médecin", "les médecins", "un médecin", "mes médecins", "m" ),
array( "Médicament", "le médicament", "les médicaments", "un médicament", "mes médicaments", "m" ),
array( "Melon", "le melon", "les melons", "un melon", "mes melons", "m" ),
array( "Ménage", "le ménage", "les ménages", "un ménage", "mes ménages", "m" ),
array( "Mensonge", "le mensonge", "les mensonges", "un mensonge", "mes mensonges", "m" ),
array( "Menton", "le menton", "les mentons", "un menton", "mes mentons", "m" ),
array( "Mer", "la mer", "les mers", "une mer", "mes mers", "f" ),
array( "Mercredi", "le mercredi", "les mercredis", "un mercredi", "mes mercredis", "m" ),
array( "Mère", "la mère", "les mères", "une mère", "mes mères", "f" ),
array( "Métal", "le métal", "les métaux", "un métal", "mes métaux", "m" ),
array( "Mètre", "le mètre", "les mètres", "un mètre", "mes mètres", "m" ),
array( "Meuble", "le meuble", "les meubles", "un meuble", "mes meubles", "m" ),
array( "Micro", "le micro", "les micros", "un micro", "mes micros", "m" ),
array( "Midi", "le midi", "les midis", "un midi", "mes midis", "m" ),
array( "Mie", "la mie", "les mies", "une mie", "mes mies", "f" ),
array( "Miel", "le miel", "les miels", "un miel", "mes miels", "m" ),
array( "Milieu", "le milieu", "les milieux", "un milieu", "mes milieux", "m" ),
array( "Mine", "la mine", "les mines", "une mine", "mes mines", "f" ),
array( "Minuit", "le minuit", "les minuits", "un minuit", "mes minuits", "m" ),
array( "Minute", "la minute", "les minutes", "une minute", "mes minutes", "f" ),
array( "Modèle", "le modèle", "les modèles", "un modèle", "mes modèles", "m" ),
array( "Moineau", "le moineau", "les moineaux", "un moineau", "mes moineaux", "m" ),
array( "Mois", "le mois", "les mois", "un mois", "mes mois", "m" ),
array( "Moitié", "la moitié", "les moitiés", "une moitié", "mes moitiés", "f" ),
array( "Moment", "le moment", "les moments", "un moment", "mes moments", "m" ),
array( "Monde", "le monde", "les mondes", "un monde", "mes mondes", "m" ),
array( "Monnaie", "la monnaie", "les monnaies", "une monnaie", "mes monnaies", "f" ),
array( "Monsieur", "le monsieur", "les monsieurs", "un monsieur", "mes monsieurs", "m" ),
array( "Montagne", "la montagne", "les montagnes", "une montagne", "mes montagnes", "f" ),
array( "Montre", "la montre", "les montres", "une montre", "mes montres", "f" ),
array( "Monument", "le monument", "les monuments", "un monument", "mes monuments", "m" ),
array( "Morceau", "le morceau", "les morceaux", "un morceau", "mes morceaux", "m" ),
array( "Morceau de pain", "le morceau de pain", "les morceaux de pain", "un morceau de pain", "mes morceaux de pain", "m" ),
array( "Mot", "le mot", "les mots", "un mot", "mes mots", "m" ),
array( "Moteur", "le moteur", "les moteurs", "un moteur", "mes moteurs", "m" ),
array( "Moto", "la moto", "les motos", "une moto", "mes motos", "f" ),
array( "Mouche", "la mouche", "les mouches", "une mouche", "mes mouches", "f" ),
array( "Mouchoir", "le mouchoir", "les mouchoirs", "un mouchoir", "mes mouchoirs", "m" ),
array( "Mouette", "la mouette", "les mouettes", "une mouette", "mes mouettes", "f" ),
array( "Moufle", "le moufle", "les moufles", "un moufle", "mes moufles", "m" ),
array( "Moule", "la moule", "les moules", "une moule", "mes moules", "f" ),
array( "Moulin", "le moulin", "les moulins", "un moulin", "mes moulins", "m" ),
array( "Mousse", "la mousse", "les mousses", "une mousse", "mes mousses", "f" ),
array( "Moustache", "la moustache", "les moustaches", "une moustache", "mes moustaches", "f" ),
array( "Moustique", "le moustique", "les moustiques", "un moustique", "mes moustiques", "m" ),
array( "Mouton", "le mouton", "les moutons", "un mouton", "mes moutons", "m" ),
array( "Muguet", "le muguet", "les muguets", "un muguet", "mes muguets", "m" ),
array( "Mur", "le mur", "les murs", "un mur", "mes murs", "m" ),
array( "Mur d’escalade", "le mur d’escalade", "les murs d’escalade", "un mur d’escalade", "mes murs d’escalade", "m" ),
array( "Mûre", "la mûre", "les mûres", "une mûre", "mes mûres", "f" ),
array( "Muscle", "le muscle", "les muscles", "un muscle", "mes muscles", "m" ),
array( "Musique", "la musique", "les musiques", "une musique", "mes musiques", "f" ),
array( "Nappe", "la nappe", "les nappes", "une nappe", "mes nappes", "f" ),
array( "Navet", "le navet", "les navets", "un navet", "mes navets", "m" ),
array( "Navire", "le navire", "les navires", "un navire", "mes navires", "m" ),
array( "Neige", "la neige", "les neiges", "une neige", "mes neiges", "f" ),
array( "Nez", "le nez", "les nez", "un nez", "mes nez", "m" ),
array( "Nid", "le nid", "les nids", "un nid", "mes nids", "m" ),
array( "Noël", "Noël", "les Noëls", "Noël", "mes Noëls", "m" ),
array( "Noeud", "le noeud", "les noeuds", "un noeud", "mes noeuds", "m" ),
array( "Noisette", "la noisette", "les noisettes", "une noisette", "mes noisettes", "f" ),
array( "Noix", "la noix", "les noix", "une noix", "mes noix", "f" ),
array( "Nom", "le nom", "les noms", "un nom", "mes noms", "m" ),
array( "Nombre", "le nombre", "les nombres", "un nombre", "mes nombres", "m" ),
array( "Nourriture", "la nourriture", "les nourritures", "une nourriture", "mes nourritures", "f" ),
array( "Noyau", "le noyau", "les noyaux", "un noyau", "mes noyaux", "m" ),
array( "Nuage", "le nuage", "les nuages", "un nuage", "mes nuages", "m" ),
array( "Nuit", "la nuit", "les nuits", "une nuit", "mes nuits", "f" ),
array( "Numéro", "le numéro", "les numéros", "un numéro", "mes numéros", "m" ),
array( "Objet", "l'objet", "les objets", "un objet", "mes objets", "m" ),
array( "Odeur", "l'odeur", "les odeurs", "une odeur", "mes odeurs", "f" ),
array( "Oeil", "l'oeil", "les yeux", "un oeil", "mes yeux", "m" ),
array( "Oeuf", "l'oeuf", "les oeufs", "un oeuf", "mes oeufs", "m" ),
array( "Ogre", "l'ogre", "les ogres", "un ogre", "mes ogres", "m" ),
array( "Oie", "l'oie", "les oies", "une oie", "mes oies", "f" ),
array( "Oignon", "l'oignon", "les oignons", "un oignon", "mes oignons", "m" ),
array( "Oiseau", "l'oiseau", "les oiseaux", "un oiseau", "mes oiseaux", "m" ),
array( "Ombre", "l'ombre", "les ombres", "une ombre", "mes ombres", "f" ),
array( "Ongle", "l'ongle", "les ongles", "un ongle", "mes ongles", "m" ),
array( "Or", "l'or", "les ors", "un or", "mes ors", "m" ),
array( "Orage", "l'orage", "les orages", "un orage", "mes orages", "m" ),
array( "Orange", "l'orange", "les oranges", "une orange", "mes oranges", "f" ),
array( "Orchestre", "l'orchestre", "les orchestres", "un orchestre", "mes orchestres", "m" ),
array( "Ordinateur", "l'ordinateur", "les ordinateurs", "un ordinateur", "mes ordinateurs", "m" ),
array( "Ordonnance", "l'ordonnance", "les ordonnances", "un ordonnance", "mes ordonnances", "f" ),
array( "Ordre", "l'ordre", "les ordres", "un ordre", "mes ordres", "m" ),
array( "Oreille", "l'oreille", "les oreilles", "une oreille", "mes oreilles", "f" ),
array( "Oreiller", "l'oreiller", "les oreillers", "un oreiller", "mes oreillers", "m" ),
array( "Os", "l'os", "les os", "un os", "mes os", "m" ),
array( "Ouragan", "l'ouragan", "les ouragans", "un ouragan", "mes ouragans", "m" ),
array( "Ours", "l'ours", "les ours", "un ours", "mes ours", "m" ),
array( "Outil", "l'outil", "les outils", "un outil", "mes outils", "m" ),
array( "Ouvrier", "l'ouvrier", "les ouvriers", "un ouvrier", "mes ouvriers", "m" ),
array( "Page", "la page", "les pages", "une page", "mes pages", "f" ),
array( "Paille", "la paille", "les pailles", "une paille", "mes pailles", "f" ),
array( "Pain", "le pain", "les pains", "un pain", "mes pains", "m" ),
array( "Paire", "la paire", "les paires", "une paire", "mes paires", "f" ),
array( "Paix", "la paix", "les guerres", "une paix", "mes guerres", "f" ),
array( "Palais", "le palais", "les palais", "un palais", "mes palais", "m" ),
array( "Pamplemousse", "le pamplemousse", "les pamplemousses", "un pamplemousse", "mes pamplemousses", "m" ),
array( "Panda", "le panda", "les pandas", "un panda", "mes pandas", "m" ),
array( "Panier", "le panier", "les paniers", "un panier", "mes paniers", "m" ),
array( "Panne", "la panne", "les pannes", "une panne", "mes pannes", "f" ),
array( "Panneau", "le panneau", "les panneaux", "un panneau", "mes panneaux", "m" ),
array( "Pansement", "le pansement", "les pansements", "un pansement", "mes pansements", "m" ),
array( "Pantalon", "le pantalon", "les pantalons", "un pantalon", "mes pantalons", "m" ),
array( "Panthère", "la panthère", "les panthères", "une panthère", "mes panthères", "f" ),
array( "Papa", "le papa", "les papas", "un papa", "mes papas", "m" ),
array( "Papier", "le papier", "les papiers", "un papier", "mes papiers", "m" ),
array( "Papillon", "le papillon", "les papillons", "un papillon", "mes papillons", "m" ),
array( "Pâquerette", "la pâquerette", "les pâquerettes", "une pâquerette", "mes pâquerettes", "f" ),
array( "Paquet", "le paquet", "les paquets", "un paquet", "mes paquets", "m" ),
array( "Parapluie", "le parapluie", "les parapluies", "un parapluie", "mes parapluies", "m" ),
array( "Parasol", "le parasol", "les parasols", "un parasol", "mes parasols", "m" ),
array( "Parc", "le parc", "les parcs", "un parc", "mes parcs", "m" ),
array( "Parcours", "le parcours", "les parcours", "un parcours", "mes parcours", "m" ),
array( "Pardon", "le pardon", "les pardons", "un pardon", "mes pardons", "m" ),
array( "Parent", "le parent", "les parents", "un parent", "mes parents", "m" ),
array( "Parfum", "le parfum", "les parfums", "un parfum", "mes parfums", "m" ),
array( "Parking", "le parking", "les parkings", "un parking", "mes parkings", "m" ),
array( "Part", "la part", "les parts", "une part", "mes parts", "f" ),
array( "Partie", "la partie", "les parties", "une partie", "mes parties", "f" ),
array( "Pas", "le pas", "les pas", "un pas", "mes pas", "m" ),
array( "Passage", "le passage", "les passages", "un passage", "mes passages", "m" ),
array( "Passerelle", "la passerelle", "les passerelles", "une passerelle", "mes passerelles", "f" ),
array( "Pâte", "la pâte", "les pâtes", "une pâte", "mes pâtes", "f" ),
array( "Pâte à modeler", "la pâte à modeler", "les pâtes à modeler", "une pâte à modeler", "mes pâtes à modeler", "f" ),
array( "Pâtisserie", "la pâtisserie", "les pâtisseries", "une pâtisserie", "mes pâtisseries", "f" ),
array( "Patte", "la patte", "les pattes", "une patte", "mes pattes", "f" ),
array( "Pays", "le pays", "les pays", "un pays", "mes pays", "m" ),
array( "Paysage", "le paysage", "les paysages", "un paysage", "mes paysages", "m" ),
array( "Peau", "la peau", "les peaux", "une peau", "mes peaux", "f" ),
array( "Pêche", "la pêche", "les pêches", "une pêche", "mes pêches", "f" ),
array( "Pêcheur", "le pêcheur", "les pêcheurs", "un pêcheur", "mes pêcheurs", "m" ),
array( "Pédale", "la pédale", "les pédales", "une pédale", "mes pédales", "f" ),
array( "Peigne", "le peigne", "les peignes", "un peigne", "mes peignes", "m" ),
array( "Peinture", "la peinture", "les peintures", "une peinture", "mes peintures", "f" ),
array( "Pelle", "la pelle", "les pelles", "une pelle", "mes pelles", "f" ),
array( "Peluche", "la peluche", "les peluches", "une peluche", "mes peluches", "f" ),
array( "Pendule", "la pendule", "les pendules", "une pendule", "mes pendules", "f" ),
array( "Pente", "la pente", "les pentes", "une pente", "mes pentes", "f" ),
array( "Père", "le père", "les pères", "un père", "mes pères", "m" ),
array( "Perle", "la perle", "les perles", "une perle", "mes perles", "f" ),
array( "Perroquet", "le perroquet", "les perroquets", "un perroquet", "mes perroquets", "m" ),
array( "Persil", "le persil", "les persils", "un persil", "mes persils", "m" ),
array( "Personne", "la personne", "les personnes", "une personne", "mes personnes", "f" ),
array( "Petit pois", "le petit pois", "les petits pois", "un petit pois", "mes petits pois", "m" ),
array( "Petite-fille", "la petite-fille", "les petites-filles", "une petite-fille", "mes petites-filles", "f" ),
array( "Petit-enfant", "le petit-enfant", "les petits-enfants", "un petit-enfant", "mes petits-enfants", "m" ),
array( "Petit-fils", "le petit-fils", "les petits-fils", "un petit-fils", "mes petits-fils", "m" ),
array( "Peur", "la peur", "les peurs", "une peur", "mes peurs", "f" ),
array( "Pharmacie", "la pharmacie", "les pharmacies", "une pharmacie", "mes pharmacies", "f" ),
array( "Pharmacien", "le pharmacien", "les pharmaciens", "un pharmacien", "mes pharmaciens", "m" ),
array( "Phoque", "le phoque", "les phoques", "un phoque", "mes phoques", "m" ),
array( "Photo", "la photo", "les photos", "une photo", "mes photos", "f" ),
array( "Pied", "le pied", "les pieds", "un pied", "mes pieds", "m" ),
array( "Pierre", "la pierre", "les pierres", "une pierre", "mes pierres", "f" ),
array( "Pigeon", "le pigeon", "les pigeons", "un pigeon", "mes pigeons", "m" ),
array( "Pile", "la pile", "les piles", "une pile", "mes piles", "f" ),
array( "Pilote", "le pilote", "les pilotes", "un pilote", "mes pilotes", "m" ),
array( "Pin", "le pin", "les pins", "un pin", "mes pins", "m" ),
array( "Pinceau", "le pinceau", "les pinceaux", "un pinceau", "mes pinceaux", "m" ),
array( "Pion", "le pion", "les pions", "un pion", "mes pions", "m" ),
array( "Piqûre", "la piqûre", "les piqûres", "une piqûre", "mes piqûres", "f" ),
array( "Piscine", "la piscine", "les piscines", "une piscine", "mes piscines", "f" ),
array( "Placard", "le placard", "les placards", "un placard", "mes placards", "m" ),
array( "Place", "la place", "les places", "une place", "mes places", "f" ),
array( "Plafond", "le plafond", "les plafonds", "un plafond", "mes plafonds", "m" ),
array( "Plage", "la plage", "les plages", "une plage", "mes plages", "f" ),
array( "Planche", "la planche", "les planches", "une planche", "mes planches", "f" ),
array( "Plante", "la plante", "les plantes", "une plante", "mes plantes", "f" ),
array( "Plat", "le plat", "les plats", "un plat", "mes plats", "m" ),
array( "Plateau", "le plateau", "les plateaux", "un plateau", "mes plateaux", "m" ),
array( "Plâtre", "le plâtre", "les plâtres", "un plâtre", "mes plâtres", "m" ),
array( "Pli", "le pli", "les plis", "un pli", "mes plis", "m" ),
array( "Pliage", "le pliage", "les pliages", "un pliage", "mes pliages", "m" ),
array( "Plongeoir", "le plongeoir", "les plongeoirs", "un plongeoir", "mes plongeoirs", "m" ),
array( "Pluie", "la pluie", "les pluies", "une pluie", "mes pluies", "f" ),
array( "Plume", "la plume", "les plumes", "une plume", "mes plumes", "f" ),
array( "Pneu", "le pneu", "les pneus", "un pneu", "mes pneus", "m" ),
array( "Poche", "la poche", "les poches", "une poche", "mes poches", "f" ),
array( "Poêle", "la poêle", "les poêles", "une poêle", "mes poêles", "f" ),
array( "Poignet", "le poignet", "les poignets", "un poignet", "mes poignets", "m" ),
array( "Poing", "le poing", "les poings", "un poing", "mes poings", "m" ),
array( "Point", "le point", "les points", "un point", "mes points", "m" ),
array( "Pointe", "la pointe", "les pointes", "une pointe", "mes pointes", "f" ),
array( "Poire", "la poire", "les poires", "une poire", "mes poires", "f" ),
array( "Poireau", "le poireau", "les poireaux", "un poireau", "mes poireaux", "m" ),
array( "Poison", "le poison", "les poisons", "un poison", "mes poisons", "m" ),
array( "Poisson", "le poisson", "les poissons", "un poisson", "mes poissons", "m" ),
array( "Police", "la police", "les polices", "une police", "mes polices", "f" ),
array( "Policier", "le policier", "les policiers", "un policier", "mes policiers", "m" ),
array( "Pomme", "la pomme", "les pommes", "une pomme", "mes pommes", "f" ),
array( "Pomme de terre", "la pomme de terre", "les pommes de terre", "une pomme de terre", "mes pommes de terre", "f" ),
array( "Pompe", "la pompe", "les pompes", "une pompe", "mes pompes", "f" ),
array( "Pompier", "le pompier", "les pompiers", "un pompier", "mes pompiers", "m" ),
array( "Poney", "le poney", "les poneys", "un poney", "mes poneys", "m" ),
array( "Pont", "le pont", "les ponts", "un pont", "mes ponts", "m" ),
array( "Port", "le port", "les ports", "un port", "mes ports", "m" ),
array( "Porte", "la porte", "les portes", "une porte", "mes portes", "f" ),
array( "Portemanteau", "le portemanteau", "les portemanteaux", "un portemanteau", "mes portemanteaux", "m" ),
array( "Portière", "la portière", "les portières", "une portière", "mes portières", "f" ),
array( "Poste", "la poste", "les postes", "une poste", "mes postes", "f" ),
array( "Poster", "le poster", "les posters", "un poster", "mes posters", "m" ),
array( "Pot", "le pot", "les pots", "un pot", "mes pots", "m" ),
array( "Potage", "le potage", "les potages", "un potage", "mes potages", "m" ),
array( "Poubelle", "la poubelle", "les poubelles", "une poubelle", "mes poubelles", "f" ),
array( "Pouce", "le pouce", "les pouces", "un pouce", "mes pouces", "m" ),
array( "Pouf", "le pouf", "les poufs", "un pouf", "mes poufs", "m" ),
array( "Poule", "la poule", "les poules", "une poule", "mes poules", "f" ),
array( "Poulet", "le poulet", "les poulets", "un poulet", "mes poulets", "m" ),
array( "Poupée", "la poupée", "les poupées", "une poupée", "mes poupées", "f" ),
array( "Poussette", "la poussette", "les poussettes", "une poussette", "mes poussettes", "f" ),
array( "Poussière", "la poussière", "les poussières", "une poussière", "mes poussières", "f" ),
array( "Poussin", "le poussin", "les poussins", "un poussin", "mes poussins", "m" ),
array( "Poutre d’équilibre", "la poutre d’équilibre", "les poutres d’équilibre", "une poutre d’équilibre", "mes poutres d’équilibre", "f" ),
array( "Prairie", "la prairie", "les prairies", "une prairie", "mes prairies", "f" ),
array( "Préau", "le préau", "les préaux", "un préau", "mes préaux", "m" ),
array( "Prénom", "le prénom", "les prénoms", "un prénom", "mes prénoms", "m" ),
array( "Prince", "le prince", "les princes", "un prince", "mes princes", "m" ),
array( "Princesse", "la princesse", "les princesses", "une princesse", "mes princesses", "f" ),
array( "Prise", "la prise", "les prises", "une prise", "mes prises", "f" ),
array( "Prix", "le prix", "les prix", "un prix", "mes prix", "m" ),
array( "Promenade", "la promenade", "les promenades", "une promenade", "mes promenades", "f" ),
array( "Prune", "la prune", "les prunes", "une prune", "mes prunes", "f" ),
array( "Pull-over", "le pull-over", "les pull-overs", "un pull-over", "mes pull-overs", "m" ),
array( "Purée", "la purée", "les purées", "une purée", "mes purées", "f" ),
array( "Puzzle", "le puzzle", "les puzzles", "un puzzle", "mes puzzles", "m" ),
array( "Pyjama", "le pyjama", "les pyjamas", "un pyjama", "mes pyjamas", "m" ),
array( "Quai", "le quai", "les quais", "un quai", "mes quais", "m" ),
array( "Quartier", "le quartier", "les quartiers", "un quartier", "mes quartiers", "m" ),
array( "Question", "la question", "les questions", "une question", "mes questions", "f" ),
array( "Queue", "la queue", "les queues", "une queue", "mes queues", "f" ),
array( "Radiateur", "le radiateur", "les radiateurs", "un radiateur", "mes radiateurs", "m" ),
array( "Radio", "la radio", "les radios", "une radio", "mes radios", "f" ),
array( "Radis", "le radis", "les radis", "un radis", "mes radis", "m" ),
array( "Raisin", "le raisin", "les raisins", "un raisin", "mes raisins", "m" ),
array( "Rampe", "la rampe", "les rampes", "une rampe", "mes rampes", "f" ),
array( "Rangée", "la rangée", "les rangées", "une rangée", "mes rangées", "f" ),
array( "Râpe", "la râpe", "les râpes", "une râpe", "mes râpes", "f" ),
array( "Raquette", "la raquette", "les raquettes", "une raquette", "mes raquettes", "f" ),
array( "Rasoir", "le rasoir", "les rasoirs", "un rasoir", "mes rasoirs", "m" ),
array( "Rat", "le rat", "les rats", "un rat", "mes rats", "m" ),
array( "Râteau", "le râteau", "les râteaux", "un râteau", "mes râteaux", "m" ),
array( "Rayon", "le rayon", "les rayons", "un rayon", "mes rayons", "m" ),
array( "Rayure", "la rayure", "les rayures", "une rayure", "mes rayures", "f" ),
array( "Recette", "la recette", "les recettes", "une recette", "mes recettes", "f" ),
array( "Récréation", "la récréation", "les récréations", "une récréation", "mes récréations", "f" ),
array( "Réfrigérateur", "le réfrigérateur", "les réfrigérateurs", "un réfrigérateur", "mes réfrigérateurs", "m" ),
array( "Regard", "le regard", "les regards", "un regard", "mes regards", "m" ),
array( "Reine", "la reine", "les reines", "une reine", "mes reines", "f" ),
array( "Renard", "le renard", "les renards", "un renard", "mes renards", "m" ),
array( "Rentrée", "la rentrée", "les rentrées", "une rentrée", "mes rentrées", "f" ),
array( "Repas", "le repas", "les repas", "un repas", "mes repas", "m" ),
array( "Requin", "le requin", "les requins", "un requin", "mes requins", "m" ),
array( "Restaurant", "le restaurant", "les restaurants", "un restaurant", "mes restaurants", "m" ),
array( "Retard", "le retard", "les retards", "un retard", "mes retards", "m" ),
array( "Retour", "le retour", "les retours", "un retour", "mes retours", "m" ),
array( "Réveil", "le réveil", "les réveils", "un réveil", "mes réveils", "m" ),
array( "Rhinocéros", "le rhinocéros", "les rhinocéros", "un rhinocéros", "mes rhinocéros", "m" ),
array( "Rideau", "le rideau", "les rideaux", "un rideau", "mes rideaux", "m" ),
array( "Rivière", "la rivière", "les rivières", "une rivière", "mes rivières", "f" ),
array( "Riz", "le riz", "les riz", "un riz", "mes riz", "m" ),
array( "Robe", "la robe", "les robes", "une robe", "mes robes", "f" ),
array( "Robinet", "le robinet", "les robinets", "un robinet", "mes robinets", "m" ),
array( "Rocher", "le rocher", "les rochers", "un rocher", "mes rochers", "m" ),
array( "Roi", "le roi", "les rois", "un roi", "mes rois", "m" ),
array( "Rond", "le rond", "les ronds", "un rond", "mes ronds", "m" ),
array( "Rondelle", "la rondelle", "les rondelles", "une rondelle", "mes rondelles", "f" ),
array( "Rosé", "le rosé", "les rosés", "un rosé", "mes rosés", "m" ),
array( "Roue", "la roue", "les roues", "une roue", "mes roues", "f" ),
array( "Roulade", "la roulade", "les roulades", "une roulade", "mes roulades", "f" ),
array( "Rouleau", "le rouleau", "les rouleaux", "un rouleau", "mes rouleaux", "m" ),
array( "Route", "la route", "les routes", "une route", "mes routes", "f" ),
array( "Ruban", "le ruban", "les rubans", "un ruban", "mes rubans", "m" ),
array( "Rue", "la rue", "les rues", "une rue", "mes rues", "f" ),
array( "Sable", "le sable", "les sables", "un sable", "mes sables", "m" ),
array( "Sac", "le sac", "les sacs", "un sac", "mes sacs", "m" ),
array( "Sac en plastique", "le sac en plastique", "les sacs en plastique", "un sac en plastique", "mes sacs en plastique", "m" ),
array( "Saison", "la saison", "les saisons", "une saison", "mes saisons", "f" ),
array( "Salade", "la salade", "les salades", "une salade", "mes salades", "f" ),
array( "Saladier", "le saladier", "les saladiers", "un saladier", "mes saladiers", "m" ),
array( "Salle", "la salle", "les salles", "une salle", "mes salles", "f" ),
array( "Samedi", "le samedi", "les samedis", "un samedi", "mes samedis", "m" ),
array( "Sang", "le sang", "les sangs", "un sang", "mes sangs", "m" ),
array( "Santé", "la santé", "les santés", "une santé", "mes santés", "f" ),
array( "Sapin", "le sapin", "les sapins", "un sapin", "mes sapins", "m" ),
array( "Sardine", "la sardine", "les sardines", "une sardine", "mes sardines", "f" ),
array( "Saut", "le saut", "les sauts", "un saut", "mes sauts", "m" ),
array( "Savon", "le savon", "les savons", "un savon", "mes savons", "m" ),
array( "Scie", "la scie", "les scies", "une scie", "mes scies", "f" ),
array( "Seau", "le seau", "les seaux", "un seau", "mes seaux", "m" ),
array( "Sel", "le sel", "les sels", "un sel", "mes sels", "m" ),
array( "Semaine", "la semaine", "les semaines", "une semaine", "mes semaines", "f" ),
array( "Semelle", "la semelle", "les semelles", "une semelle", "mes semelles", "f" ),
array( "Sens", "le sens", "les sens", "un sens", "mes sens", "m" ),
array( "Serpent", "le serpent", "les serpents", "un serpent", "mes serpents", "m" ),
array( "Serrure", "la serrure", "les serrures", "une serrure", "mes serrures", "f" ),
array( "Serviette", "la serviette", "les serviettes", "une serviette", "mes serviettes", "f" ),
array( "Shampoing", "le shampoing", "les shampoings", "un shampoing", "mes shampoings", "m" ),
array( "Siège", "le siège", "les sièges", "un siège", "mes sièges", "m" ),
array( "Sieste", "la sieste", "les siestes", "une sieste", "mes siestes", "f" ),
array( "Sifflet", "le sifflet", "les sifflets", "un sifflet", "mes sifflets", "m" ),
array( "Signe", "le signe", "les signes", "un signe", "mes signes", "m" ),
array( "Silence", "le silence", "les silences", "un silence", "mes silences", "m" ),
array( "Singe", "le singe", "les singes", "un singe", "mes singes", "m" ),
array( "Ski", "le ski", "les skis", "un ski", "mes skis", "m" ),
array( "Soeur", "la soeur", "les soeurs", "une soeur", "mes soeurs", "f" ),
array( "Soif", "la soif", "les soifs", "une soif", "mes soifs", "f" ),
array( "Soir", "le soir", "les soirs", "un soir", "mes soirs", "m" ),
array( "Sol", "le sol", "les sols", "un sol", "mes sols", "m" ),
array( "Soldat", "le soldat", "les soldats", "un soldat", "mes soldats", "m" ),
array( "Sole", "la sole", "les soles", "une sole", "mes soles", "f" ),
array( "Soleil", "le soleil", "les soleils", "un soleil", "mes soleils", "m" ),
array( "Sommeil", "le sommeil", "les sommeils", "un sommeil", "mes sommeils", "m" ),
array( "Sommet", "le sommet", "les sommets", "un sommet", "mes sommets", "m" ),
array( "Sonnette", "la sonnette", "les sonnettes", "une sonnette", "mes sonnettes", "f" ),
array( "Sorcière", "la sorcière", "les sorcières", "une sorcière", "mes sorcières", "f" ),
array( "Sortie", "la sortie", "les sorties", "une sortie", "mes sorties", "f" ),
array( "Soupe", "la soupe", "les soupes", "une soupe", "mes soupes", "f" ),
array( "Sourcil", "le sourcil", "les sourcils", "un sourcil", "mes sourcils", "m" ),
array( "Sourire", "le sourire", "les sourires", "un sourire", "mes sourires", "m" ),
array( "Souris", "la souris", "les souris", "une souris", "mes souris", "f" ),
array( "Spectacle", "le spectacle", "les spectacles", "un spectacle", "mes spectacles", "m" ),
array( "Sport", "le sport", "les sports", "un sport", "mes sports", "m" ),
array( "Square", "le square", "les squares", "un square", "mes squares", "m" ),
array( "Squelette", "le squelette", "les squelettes", "un squelette", "mes squelettes", "m" ),
array( "Stylo", "le stylo", "les stylos", "un stylo", "mes stylos", "m" ),
array( "Sucre", "le sucre", "les sucres", "un sucre", "mes sucres", "m" ),
array( "Suivant", "le suivant", "les suivants", "un suivant", "mes suivants", "m" ),
array( "Surprise", "la surprise", "les surprises", "une surprise", "mes surprises", "f" ),
array( "Table", "la table", "les tables", "une table", "mes tables", "f" ),
array( "Tableau", "le tableau", "les tableaux", "un tableau", "mes tableaux", "m" ),
array( "Tablier", "le tablier", "les tabliers", "un tablier", "mes tabliers", "m" ),
array( "Tabouret", "le tabouret", "les tabourets", "un tabouret", "mes tabourets", "m" ),
array( "Tache", "la tache", "les taches", "une tache", "mes taches", "f" ),
array( "Taille", "la taille", "les tailles", "une taille", "mes tailles", "f" ),
array( "Taille-crayon", "le taille-crayon", "les taille-crayons", "un taille-crayon", "mes taille-crayons", "m" ),
array( "Talon", "le talon", "les talons", "un talon", "mes talons", "m" ),
array( "Tambour", "le tambour", "les tambours", "un tambour", "mes tambours", "m" ),
array( "Tampon", "le tampon", "les tampons", "un tampon", "mes tampons", "m" ),
array( "Tapis", "le tapis", "les tapis", "un tapis", "mes tapis", "m" ),
array( "Tarte", "la tarte", "les tartes", "une tarte", "mes tartes", "f" ),
array( "Tartine", "la tartine", "les tartines", "une tartine", "mes tartines", "f" ),
array( "Tas", "le tas", "les tas", "un tas", "mes tas", "m" ),
array( "Tasse", "la tasse", "les tasses", "une tasse", "mes tasses", "f" ),
array( "Taupe", "la taupe", "les taupes", "une taupe", "mes taupes", "f" ),
array( "Télécommande", "la télécommande", "les télécommandes", "une télécommande", "mes télécommandes", "f" ),
array( "Téléphone", "le téléphone", "les téléphones", "un téléphone", "mes téléphones", "m" ),
array( "Télévision", "la télévision", "les télévisions", "une télévision", "mes télévisions", "f" ),
array( "Tempête", "la tempête", "les tempêtes", "une tempête", "mes tempêtes", "f" ),
array( "Temps", "le temps", "les temps", "un temps", "mes temps", "m" ),
array( "Tente", "la tente", "les tentes", "une tente", "mes tentes", "f" ),
array( "Terrain", "le terrain", "les terrains", "un terrain", "mes terrains", "m" ),
array( "Terre", "la terre", "les terres", "une terre", "mes terres", "f" ),
array( "Terrier", "le terrier", "les terriers", "un terrier", "mes terriers", "m" ),
array( "Tête", "la tête", "les têtes", "une tête", "mes têtes", "f" ),
array( "Thé", "le thé", "les thés", "un thé", "mes thés", "m" ),
array( "Thermomètre", "le thermomètre", "les thermomètres", "un thermomètre", "mes thermomètres", "m" ),
array( "Ticket", "le ticket", "les tickets", "un ticket", "mes tickets", "m" ),
array( "Tige", "la tige", "les tiges", "une tige", "mes tiges", "f" ),
array( "Tigre", "le tigre", "les tigres", "un tigre", "mes tigres", "m" ),
array( "Timbre", "le timbre", "les timbres", "un timbre", "mes timbres", "m" ),
array( "Tiroir", "le tiroir", "les tiroirs", "un tiroir", "mes tiroirs", "m" ),
array( "Tissu", "le tissu", "les tissus", "un tissu", "mes tissus", "m" ),
array( "Titre", "le titre", "les titres", "un titre", "mes titres", "m" ),
array( "Toboggan", "le toboggan", "les toboggans", "un toboggan", "mes toboggans", "m" ),
array( "Toilette", "la toilette", "les toilettes", "une toilette", "mes toilettes", "f" ),
array( "Toit", "le toit", "les toits", "un toit", "mes toits", "m" ),
array( "Tomate", "la tomate", "les tomates", "une tomate", "mes tomates", "f" ),
array( "Tonnerre", "le tonnerre", "les tonnerres", "un tonnerre", "mes tonnerres", "m" ),
array( "Torchon", "le torchon", "les torchons", "un torchon", "mes torchons", "m" ),
array( "Tortue", "la tortue", "les tortues", "une tortue", "mes tortues", "f" ),
array( "Tour", "la tour", "les tours", "une tour", "mes tours", "f" ),
array( "Tournevis", "le tournevis", "les tournevis", "un tournevis", "mes tournevis", "m" ),
array( "Tracteur", "le tracteur", "les tracteurs", "un tracteur", "mes tracteurs", "m" ),
array( "Train", "le train", "les trains", "un train", "mes trains", "m" ),
array( "Traîneau", "le traîneau", "les traîneaux", "un traîneau", "mes traîneaux", "m" ),
array( "Trait", "le trait", "les traits", "un trait", "mes traits", "m" ),
array( "Trampoline", "le trampoline", "les trampolines", "un trampoline", "mes trampolines", "m" ),
array( "Tranche", "la tranche", "les tranches", "une tranche", "mes tranches", "f" ),
array( "Travail", "le travail", "les travaux", "un travail", "mes travaux", "m" ),
array( "Trésor", "le trésor", "les trésors", "un trésor", "mes trésors", "m" ),
array( "Tricot", "le tricot", "les tricots", "un tricot", "mes tricots", "m" ),
array( "Tricycle", "le tricycle", "les tricycles", "un tricycle", "mes tricycles", "m" ),
array( "Trompette", "la trompette", "les trompettes", "une trompette", "mes trompettes", "f" ),
array( "Trottoir", "le trottoir", "les trottoirs", "un trottoir", "mes trottoirs", "m" ),
array( "Trou", "le trou", "les trous", "un trou", "mes trous", "m" ),
array( "Trousse", "la trousse", "les trousses", "une trousse", "mes trousses", "f" ),
array( "Tube", "le tube", "les tubes", "un tube", "mes tubes", "m" ),
array( "Tulipe", "la tulipe", "les tulipes", "une tulipe", "mes tulipes", "f" ),
array( "Tunnel", "le tunnel", "les tunnels", "un tunnel", "mes tunnels", "m" ),
array( "Tuyau", "le tuyau", "les tuyaux", "un tuyau", "mes tuyaux", "m" ),
array( "Uniforme", "l'uniforme", "les uniformes", "un uniforme", "mes uniformes", "m" ),
array( "Univers", "l'univers", "les univers", "un univers", "mes univers", "m" ),
array( "Usine", "l'usine", "les usines", "une usine", "mes usines", "f" ),
array( "Vache", "la vache", "les vaches", "une vache", "mes vaches", "f" ),
array( "Vague", "la vague", "les vagues", "une vague", "mes vagues", "f" ),
array( "Vaisselle", "la vaisselle", "les vaisselles", "une vaisselle", "mes vaisselles", "f" ),
array( "Valise", "la valise", "les valises", "une valise", "mes valises", "f" ),
array( "Vase", "le vase", "les vases", "un vase", "mes vases", "m" ),
array( "Véhicule", "le véhicule", "les véhicules", "un véhicule", "mes véhicules", "m" ),
array( "Vélo", "le vélo", "les vélos", "un vélo", "mes vélos", "m" ),
array( "Vendredi", "le vendredi", "les vendredis", "un vendredi", "mes vendredis", "m" ),
array( "Vent", "le vent", "les vents", "un vent", "mes vents", "m" ),
array( "Ventre", "le ventre", "les ventres", "un ventre", "mes ventres", "m" ),
array( "Ver", "le ver", "les vers", "un ver", "mes vers", "m" ),
array( "Verre", "le verre", "les verres", "un verre", "mes verres", "m" ),
array( "Veste", "la veste", "les vestes", "une veste", "mes vestes", "f" ),
array( "Vêtement", "le vêtement", "les vêtements", "un vêtement", "mes vêtements", "m" ),
array( "Vétérinaire", "le vétérinaire", "les vétérinaires", "un vétérinaire", "mes vétérinaires", "m" ),
array( "Viande", "la viande", "les viandes", "une viande", "mes viandes", "f" ),
array( "Village", "le village", "les villages", "un village", "mes villages", "m" ),
array( "Ville", "la ville", "les villes", "une ville", "mes villes", "f" ),
array( "Vin", "le vin", "les vins", "un vin", "mes vins", "m" ),
array( "Virage", "le virage", "les virages", "un virage", "mes virages", "m" ),
array( "Vis", "la vis", "les vis", "une vis", "mes vis", "f" ),
array( "Visage", "le visage", "les visages", "un visage", "mes visages", "m" ),
array( "Vitesse", "la vitesse", "les vitesses", "une vitesse", "mes vitesses", "f" ),
array( "Vitre", "la vitre", "les vitres", "une vitre", "mes vitres", "f" ),
array( "Voile", "le voile", "les voiles", "un voile", "mes voiles", "m" ),
array( "Voisin", "le voisin", "les voisins", "un voisin", "mes voisins", "m" ),
array( "Voiture", "la voiture", "les voitures", "une voiture", "mes voitures", "f" ),
array( "Voix", "la voix", "les voix", "une voix", "mes voix", "f" ),
array( "Volet", "le volet", "les volets", "un volet", "mes volets", "m" ),
array( "Voyage", "le voyage", "les voyages", "un voyage", "mes voyages", "m" ),
array( "Wagon", "le wagon", "les wagons", "un wagon", "mes wagons", "m" ),
array( "WC", "le WC", "les WCs", "un WC", "mes WCs", "m" ),
array( "Xylophone", "le xylophone", "les xylophones", "un xylophone", "mes xylophones", "m" ),
array( "Yaourt", "le yaourt", "les yaourts", "un yaourt", "mes yaourts", "m" ),
array( "Zèbre", "le zèbre", "les zèbres", "un zèbre", "mes zèbres", "m" ),
array( "Zéro", "le zéro", "les zéros", "un zéro", "mes zéros", "m" ),
array( "Zigzag", "le zigzag", "les zigzags", "un zigzag", "mes zigzags", "m" ),
array( "Zoo", "le zoo", "les zoos", "un zoo", "mes zoos", "m" ),  
);
  
private $verbes = array
(
"abandonné",
"accepté",
"accompagné",
"acheté",
"adoré",
"aidé",
"aimé",
"ajouté",
"amené",
"amusé",
"annoncé",
"aperçu",
"fait apparaître",
"appelé",
"apporté",
"appris",
"approché",
"arrangé",
"arrêté",
"assis",
"assuré",
"attaqué",
"atteint",
"attendu",
"avancé",
"eu",
"baissé",
"battu",
"bu",
"bougé",
"brûlé",
"caché",
"calmé",
"cassé",
"fait cesser",
"changé",
"chanté",
"chargé",
"cherché",
"choisi",
"commencé",
"compris",
"compté",
"conduit",
"connu",
"couché",
"coupé",
"couvert",
"craint",
"cru",
"fait danser",
"décidé",
"découvert",
"dégagé",
"demandé",
"descendu",
"détesté",
"détruit",
"deviné",
"fait disparaître",
"donné",
"endormi",
"écouté",
"écrit",
"éloigné",
"embrassé",
"emmené",
"empêché",
"emporté",
"enlevé",
"entendu",
"envoyé",
"essayé",
"évité",
"excusé",
"expliqué",
"fermé",
"fini",
"foutu",
"fourré",
"frappé",
"gagné",
"gardé",
"glissé",
"habité",
"ignoré",
"imaginé",
"importé",
"inquiété",
"installé",
"invité",
"jeté",
"juré",
"lâché",
"laissé",
"lancé",
"levé",
"lu",
"maintenu",
"mangé",
"manqué",
"marié",
"mené",
"mis",
"monté",
"montré",
"obligé",
"occupé",
"offert",
"osé",
"oublié",
"ouvert",
"payé",
"pensé",
"perdu",
"permis",
"pleuré",
"porté",
"posé",
"poussé",
"préféré",
"pris",
"préparé",
"présenté",
"prévenu",
"promis",
"proposé",
"protégé",
"quitté",
"raconté",
"ramené",
"rappelé",
"reçu",
"reconnu",
"réfléchi",
"refusé",
"regardé",
"rejoint",
"remarqué",
"remis",
"remonté",
"rencontré",
"rendu",
"rentré",
"reposé",
"repris",
"retenu",
"retiré",
"retourné",
"retrouvé",
"réveillé",
"rêvé",
"revu",
"roulé",
"sauté",
"sauvé",
"secoué",
"senti",
"séparé",
"serré",
"servi",
"sorti",
"suivi",
"fait taire",
"tendu",
"tenu",
"tenté",
"terminé",
"tiré",
"fait tomber",
"touché",
"tourné",
"traîné",
"traité",
"fait travailler",
"traversé",
"trompé",
"trouvé",
"tué",
"utilisé",
"vendu",
"vu",
"volé",
"voulu",
);


public function genererNiemoller($strophes = 1, $retourChariot = "\n", $conclusion = false)
{
$verbe = $this->verbes[$this->getRandomArrayIndex($this->verbes)];
$text = "";

for ($s = 0; $s < $strophes; $s++)
{
$nomID = $this->getRandomArrayIndex($this->noms);

$text .= "Quand ils ont ".$verbe." ".$this->noms[$nomID][2].",".$retourChariot;
$text .= "je n'ai rien dit,".$retourChariot;
$text .= "je n'étais pas ".$this->noms[$nomID][3].".".$retourChariot.$retourChariot;
}

if ($conclusion)
{
 $text .= "Enfin ils m'ont ".$verbe.",".$retourChariot;
 $text .= "et il ne restait plus personne".$retourChariot;
 $text .= "pour me défendre.";
}

 return $text;
}

private function getRandomArrayIndex($arr) { return mt_rand(0, count($arr) - 1); }

}